### ISSUE TITLE
Propagate trace information across threads

### ISSUE THREAD

**Issue by rdpravin1895** [open-telemetry/opentelemetry-python-contrib#1010]
Is there a way to propagate trace information from a parent thread to a child thread (running through ThreadPoolExecutor)? Or should they be injected manually by extending the ThreadPoolExecutor class? Has anyone tried this? 

If #737 is implemented, that would suffice, but wanted to know if there is a workaround. Also, bit surprised that there are literally no github issues or stackoverflow questions about this.

**Comment by ocelotl** [comment]
> Is there a way to propagate trace information from a parent thread to a child thread (running through ThreadPoolExecutor)? Or should they be injected manually by extending the ThreadPoolExecutor class? Has anyone tried this?
> 
> If #737 is implemented, that would suffice, but wanted to know if there is a workaround. Also, bit surprised that there are literally no github issues or stackoverflow questions about this.

Hey, @rdpravin1895, thanks for reporting. Since #737 would solve this issue, I am closing this one in order to avoid duplication. Please add any other comments you may have regarding this in #737 :v:
