### ISSUE TITLE
[instrumentation-requests] Restore metrics

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#1039]
The requests instrumentation used to produce metrics: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/metrics/instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py

This issue is to restore that functionality.

**Comment by ashu658** [comment]
@codeboten Can you assign this issue to me?

**Comment by codeboten** [comment]
@ashu658 done!
