### ISSUE TITLE
[instrumentation-urllib] Restore metrics

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#1041]
The urllib instrumentation used to produce metrics: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/metrics/instrumentation/opentelemetry-instrumentation-urllib/src/opentelemetry/instrumentation/urllib/__init__.py

This issue is to restore that functionality.

**Comment by osherv** [comment]
Can you please assign this to me? :)
