### ISSUE TITLE
Add instrumentation for Faust stream processing library

### ISSUE THREAD

**Issue by sanketmehta28** [open-telemetry/opentelemetry-python-contrib#1047]
**Describe the solution you'd like**
It would be great to have auto instrumentation for [Faust](https://github.com/robinhood/faust): python streaming library along side kafka-python.

**Describe alternatives you've considered**
I have considered using tracing SDK to manually instrument it

**Additional context**
Faust ports the idea of kafka streaming to python. It has a great demand in stream processing and event processing applications similar to kafka streams, apache spark, storm etc. Faust is used for event processing, distributed joins & aggregations, machine learning, asynchronous tasks distributed computing, data Denormalization, intrusion detection, realtime web & web sockets etc.

**Comment by srikanthccv** [comment]
duplicate of #800

**Comment by sanketmehta28** [comment]
closing this as this is duplicate of #800
