### ISSUE TITLE
Issue to track Sanket's work for contrib approver

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1053]
He has been contributing actively for quite sometime and expressed interest in becoming contrib [approver](https://github.com/open-telemetry/community/blob/main/community-membership.md#approver) on 14th April SIG meeting. @sanketmehta28 Please use this issue to list/track your contributions.

**Comment by sanketmehta28** [comment]
Hi @srikanthccv ,
Thank you for this opportunity.
Here is my contribution:
#832 
#869 
#899 
#903 
#1004 
#1024 
#1032 
#1046 

PRs I have reviewed:
#1022 
#925 

Issues Created:
#1025 
#1047 

Current Issues:
#1043

**Comment by srikanthccv** [comment]
+1 from me. Appreciate your contributions to the SIG.

**Comment by lzchen** [comment]
+1 from me :D

**Comment by sanketmehta28** [comment]
Received and Accepted with both hands. Thank you guys for this honour.
Looking forward to contribute more going forward!!
