### ISSUE TITLE
Issue to track Ashu's contributions for contrib approver

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1054]
Ashutosh has been contributing actively for quite sometime and expressed interest in becoming contrib [approver](https://github.com/open-telemetry/community/blob/main/community-membership.md#approver). @ashu658  Please use this issue to list/track your contributions.

**Comment by ashu658** [comment]
Thanks @srikanthccv for opening this issue 😄 
Here is the list of my contributions:
PRs authored:
#1032 
#1022 
#1003 
#952 
#950 
#928 
#925 
#898
#897 
#889 
#867 
#828 
Reviewed PRs:
#1032 
#1004
Currently working on:
#1040 (My first issue to understand python metrics SDK)

Please let me know if any more info is needed.

**Comment by lzchen** [comment]
+1 for my nomination :)

**Comment by srikanthccv** [comment]
+1 from me.

**Comment by ocelotl** [comment]
@ashu658 I sent you an invite :v:

**Comment by ashu658** [comment]
Thanks for the invite @ocelotl and thanks for the support @srikanthccv @lzchen 
Looking forward to contribute more to the project. 😄
