### ISSUE TITLE
Running opentelemetry-instrument sets the service.name to unknown_service

### ISSUE THREAD

**Issue by jonathan-s** [open-telemetry/opentelemetry-python-contrib#1068]
**Describe your environment**

Python 3.7.2
opentelemetry-api==1.11.0
opentelemetry-distro==0.30b0
opentelemetry-exporter-otlp-proto-http==1.11.0
opentelemetry-instrumentation==0.30b0
opentelemetry-instrumentation-flask==0.30b0
opentelemetry-instrumentation-requests 0.30b0
opentelemetry-instrumentation-wsgi==0.30b0
opentelemetry-proto==1.11.0
opentelemetry-sdk==1.11.0
opentelemetry-semantic-conventions==0.30b0
opentelemetry-util-http==0.30b0

**Steps to reproduce**
The code I'm running. 

```
import flask
import requests

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.flask import FlaskInstrumentor
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor,
)
from opentelemetry.sdk.resources import (
    SERVICE_NAME,
    DEPLOYMENT_ENVIRONMENT,
    Resource
)


app = flask.Flask(__name__)


def request_hook(span, environ):
    if span and span.is_recording():
        pass


def response_hook(span, status: str, response_headers):
    if span and span.is_recording():
        span.set_attribute("custom.label", "hello world")


resource = Resource.create(attributes={
    SERVICE_NAME: "my-service",
    DEPLOYMENT_ENVIRONMENT: "local-dev"
})
tracer_provider = TracerProvider(resource=resource)
trace.set_tracer_provider(tracer_provider)

FlaskInstrumentor().instrument_app(
    app,
    tracer_provider=tracer_provider,
    request_hook=request_hook,
    response_hook=response_hook
)

exporter = OTLPSpanExporter()
tracer_provider.add_span_processor(
    BatchSpanProcessor(exporter)
)


@app.route("/")
def hello():
    requests.get("http://www.example.com")
    return "hello"


if __name__ == '__main__':
    app.run(port=5000)
```

Set the following environment variables

OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_ENDPOINT=https://apm-server-internal.your-host.com:4318
OTEL_TRACES_EXPORTER=otlp_proto_http

- copy the code into example.py
- run the following command
```
python example.py
```
- visit /
- Notice that the data has been sent into your apm machine, notice also that the service name is `my-service`, you also have the custom attribute that you set after the request. . 

Next up! 
- run the command `opentelemetry-instrument python example.py`
- visit /
- Notice that data has been sent to the apm machine, but the service is now `unknown_service`. No custom attribute is set.

**What is the expected behavior?**
In the documentation it says that you should be able to use the automatic instrumentation together with manual instrumentation. I'm expecting that to be the case. 

I'm expecting that the service would be called `my-service` whether I use opentelemetry-instrument or running the python command cleanly. 

**What is the actual behavior?**
- When I run `opentelemetry-instrument python example.py`, the service is called "unknown_service" and there are no attributes set. 
- When I run `python example.py`, the service is called "my-service", and there are attributes set. 

**Additional context**

**Comment by codeboten** [comment]
Can you try using the `--service_name` or `OTEL_SERVICE_NAME` to set the name? "unknown_service" is the default set by the SDK if no service name is set.

**Comment by jonathan-s** [comment]
@codeboten What I find perplexing is that I am setting the service name here in the resource. 

```
resource = Resource.create(attributes={
    SERVICE_NAME: "my-service",
    DEPLOYMENT_ENVIRONMENT: "local-dev"
})
```

Which I provide to `tracer_provider`. Even if I were to set the service name through the SDK, that doesn't answer why the custom attributes are dropped when running through the `opentelemetry-instrument` SDK.

**Comment by srikanthccv** [comment]
The global provider can only be set once and it is set as a part of auto-instrumentation by `opentelemetry-instrument`. So your call to set tracer provider is rejected with warning _Overriding of current TracerProvider is not allowed_. You could set the `OTEL_RESOURCE_ATTRIBUTES=a=b,c=d` to get the auto-instrumention to pick the custom resource attributes.

**Comment by codeboten** [comment]
@jonathan-s ah i see... the attribute names should be coming from the semconv package. Here's an example:

```
from opentelemetry.semconv.resource import ResourceAttributes
from opentelemetry.semconv.trace import SpanAttributes
from local_machine_resource_detector import LocalMachineResourceDetector


def configure_tracer(name, version):
    exporter = ConsoleSpanExporter()
    span_processor = BatchSpanProcessor(exporter)
    local_resource = LocalMachineResourceDetector().detect()
    resource = local_resource.merge(
        Resource.create(
            {
                ResourceAttributes.SERVICE_NAME: name,
                ResourceAttributes.SERVICE_VERSION: version,
            }
        )
    )
```

**Comment by codeboten** [comment]
🤔 @jonathan-s now I'm really confused... I just tried the code locally and got the following resource attributes:

```
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.0",
        "service.name": "my-service",
        "deployment.environment": "local-dev"
    }
```

**Comment by codeboten** [comment]
@jonathan-s ah i see... I was missing the `opentelemetry-distro` package locally, which is causing the tracer provider to be configured as per @srikanthccv's comment.

**Comment by jonathan-s** [comment]
@codeboten Good stuff! I got that `opentelemetry-distro` from this tutorial section > https://opentelemetry.io/docs/instrumentation/python/automatic/#install

So perhaps it might be worth writing a notification / warning section that, that package has that behaviour, if you were to mix things with manual instrumentation.  

There is one remaining thing, when running `opentelemetry-instrument` my custom attribute is not set, the one you can see below. Whereas running without that, it is set. 

```
def response_hook(span, status: str, response_headers):
    if span and span.is_recording():
        span.set_attribute("custom.label", "hello world")

```

**Comment by jonathan-s** [comment]
I now see that when the following code is triggered here > https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-flask/src/opentelemetry/instrumentation/flask/__init__.py#L380-L410

It's testing `if not app._is_instrumented_by_opentelemetry` and presumably by using `opentelemetry-instrument` to run the application it will set `_is_instrumented_by_opentelemetry` to True, and thus never set the response hooks...

**Comment by jonathan-s** [comment]
Trying to uninstrument the app, and then instrument the app again doesn't seem to work either.

**Comment by srikanthccv** [comment]
>So perhaps it might be worth writing a notification / warning section that, that package has that behaviour, if you were to mix things with manual instrumentation.

Good point +1

> It's testing if not app._is_instrumented_by_opentelemetry and presumably by using opentelemetry-instrument to run the application it will set _is_instrumented_by_opentelemetry to True, and thus never set the response hooks

Flask instrumentation has some quirky detail related the importing in auto-instrumentation, You are probably running into that issue?

 > Trying to uninstrument the app, and then instrument the app again doesn't seem to work either.

Can you share an example what you are trying to do?

**Comment by jonathan-s** [comment]
@srikanthccv I created this gist > https://gist.github.com/jonathan-s/3117c4a987db741dbb160c23b4b10aa8
The first commit is the code above, the second revision is me trying to uninstrument the app. 

Running with `opentelemetry-instrument` won't instrument the app. My reasoning was that perhaps I could uninstrument the app to again instrument the app so I could get the response and request hooks.

**Comment by srikanthccv** [comment]
As I mentioned earlier you can't manually the _set_ tracer provider in your code if you are already using the auto-instrumentation. There are number of environment variable that help users configure the behaviour [here](https://opentelemetry-python.readthedocs.io/en/latest/sdk/environment_variables.html) and [here](https://opentelemetry-python.readthedocs.io/en/latest/api/environment_variables.html). As you would already know the auto-instrumentation for large number of packages is achieved by monkey-patching, which comes with problems And the order of things change the behaviour, which is the main issue here. I have added updated version as a comment in your gist. I would encourage you to not to use both `opentelemetry-instrument` auto instrumentation and your semi-auto instrumentation work i.e instantiating and calling `...instrument()`.

**Comment by jonathan-s** [comment]
Thanks @srikanthccv, I think it would be worth mentioning that in the docs too as a caveat what to expect.

**Comment by jonathan-s** [comment]
I submitted a patch with a suggestion on how I would phrase it in the documentation here > https://github.com/open-telemetry/opentelemetry.io/pull/1311

**Comment by jonathan-s** [comment]
Closing this now, thanks for all the pointers.
