### ISSUE TITLE
DD propagator fails to inject a NonRecordingSpan

### ISSUE THREAD

**Issue by eladidan** [open-telemetry/opentelemetry-python-contrib#1078]
If the context being injected is of a non-recording span, e.g. if the service is merely forwarding the extracted span without creating a new one, or if the span was not sampled, then it will fail to inject with:

> AttributeError: 'NonRecordingSpan' object has no attribute 'context'

This seems to be a simple issue with using [`span.context`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/propagator.py#L97) instead of the `span_context`  retrieved in the beginning of [`inject`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/propagator.py#L94)

I'll create a PR shortly with the fix

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
A `NonRecordingSpan` should inject if it is valid.

**What is the actual behavior?**
An exception is thrown, failing the grpc/http request handler if the user isn't wrapping around the propagator

**Additional context**
I think additionally we should add a top level try/except to not allow the `inject` to throw and fail the handler but just log a warning.

**Comment by sanketmehta28** [comment]
@eladidan : do you want this to be assigned to you?
