### ISSUE TITLE
Aiopg instrumentation not compatible with latest aiopg (1.2.1)

### ISSUE THREAD

**Issue by cdvv7788** [open-telemetry/opentelemetry-python-contrib#1085]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.
Using aiopg 1.2.1 I am getting the following error:
`ImportError: cannot import name '_PoolContextManager' from 'aiopg.utils' (/usr/local/lib/python3.9/site-packages/aiopg/utils.py)`

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Just enable the `AiopgInstrumentor` in a project with the latest aiopg.

**What is the expected behavior?**
What did you expect to see?
Working instrumentation

**What is the actual behavior?**
What did you see instead?
Import error

**Additional context**

**Comment by ocelotl** [comment]
Can you provide a specific example @cdvv7788, please? I ran the `opentelemetry-instrumentation-aiopg` tests which instantiate an `AiopgInstrumentor` using version 1.2.1 and they pass.

**Comment by freudenberg** [comment]
The error happens since version 1.3.0. `aiopg.utils._PoolContextManager` has been reomved in https://github.com/aio-libs/aiopg/commit/187d13a06581054e1f910961b8238837e7c8bd0b.

**Comment by sgomez** [comment]
Maybe that logic was moved to this other file?

https://github.com/aio-libs/aiopg/blob/master/aiopg/pool.py#L58

**Comment by thomasleveil** [comment]
This seems to be now fixed, probably with https://github.com/open-telemetry/opentelemetry-python-contrib/commit/5af3519f369e5cfa8d9a8928572b9d7bdcadf297

**Comment by ocelotl** [comment]
Ran tests with 1.3.0 and 1.2.1, both passed, closing. Please reopen if necessary.
