### ISSUE TITLE
[instrumentation-django] - empty span name

### ISSUE THREAD

**Issue by shaykeren** [open-telemetry/opentelemetry-python-contrib#1098]
**Describe your environment** 
opentelemetry-instrumentation-django==0.30b1
django==4.0.4

**Steps to reproduce**
Having the following URL patterns:
`from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
]`
Please note that the path route has an empty value.

**What is the expected behavior?**
The expected behavior is not having an empty span name for this endpoint.
Also, consider returning http.route  attribute with value '/'

**What is the actual behavior?**
* Got an empty span name
* No http.route attribute returned

**Comment by srikanthccv** [comment]
What do you expect the span name if not empty?

**Comment by shaykeren** [comment]
if an empty route has the same meaning of a route with a value of '/' then I would consider setting both the route and the name to '/'
