### ISSUE TITLE
java call python tracing broken

### ISSUE THREAD

**Issue by tonycody** [open-telemetry/opentelemetry-python-contrib#1122]
<img width="1949" alt="image" src="https://user-images.githubusercontent.com/6773121/172588517-01e152eb-1884-4bcd-b058-343ba276f4e8.png">

java call python

python pip list
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6773121/172588696-30d5958b-2b57-4ad9-bddd-892ec8cca0ae.png">

python automic instrument
```shell
opentelemetry-instrument \
      --exporter_jaeger_endpoint http://172.37.66.191:14268/api/traces?format=jaeger.thrift \
      --service_name "python-test" \
      --traces_exporter jaeger_thrift,console \
      python ipaas_start.py
```

java debug
<img width="903" alt="image" src="https://user-images.githubusercontent.com/6773121/172589162-ac6e8f78-8475-4c56-ac59-3fbecbd8c69e.png">

java trace
<img width="1793" alt="image" src="https://user-images.githubusercontent.com/6773121/172804760-687205cd-fb8e-41ba-a657-ec2add90d7fc.png">

python debug
```json
{
    "name": "/execute",
    "context": {
        "trace_id": "0x86a051a6f50d2a5a4deb3d3fd82b9496",
        "span_id": "0x0c94c833eec2a358",
        "trace_state": "[]"
    },
    "kind": "SpanKind.SERVER",
    "parent_id": null,
    "start_time": "2022-06-08T09:57:43.379825Z",
    "end_time": "2022-06-08T09:57:43.381147Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "http.method": "POST",
        "http.server_name": "0.0.0.0",
        "http.scheme": "http",
        "net.host.port": 8080,
        "http.host": "ipaas-a34d5480-2468-429b-8e6a-03663169489f.dev3.svc.cluster.local",
        "http.target": "/execute",
        "net.peer.ip": "10.100.57.170",
        "http.user_agent": "Apache-HttpClient/4.5.13 (Java/1.8.0_212)",
        "net.peer.port": 47458,
        "http.flavor": "1.1",
        "http.route": "/execute",
        "http.status_code": 200
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.1",
        "service.name": "python-test",
        "telemetry.auto.version": "0.30b1"
    }
}
```

The trace ID is different

**Comment by lytao123** [comment]
I use Tornado  v6.1, not use Flask

**Comment by lytao123** [comment]
My problem is solved.  

add
`TornadoInstrumentor().instrument()`

**Comment by lytao123** [comment]
> Currently, the source of the request in Python is retrieved, but parent_id is empty, and traceId is inconsistent with source
> 
> ```shell
> "attributes": {
>         "http.method": "POST",
>         "http.server_name": "0.0.0.0",
>         "http.scheme": "http",
>         "net.host.port": 8080,
>         "http.host": "ipaas-a34d5480-2468-429b-8e6a-03663169489f.dev3.svc.cluster.local",
>         "http.target": "/execute",
>         "net.peer.ip": "10.100.57.170",
>         "http.user_agent": "Apache-HttpClient/4.5.13 (Java/1.8.0_212)",
>         "net.peer.port": 47458,
>         "http.flavor": "1.1",
>         "http.route": "/execute",
>         "http.status_code": 200
>     }
> ```

code add:
```
TornadoInstrumentor().instrument()
```

**Comment by srikanthccv** [comment]
@tonycody can you answer what the configured propagators are for both python and java?

**Comment by srikanthccv** [comment]
@tonycody is this still an issue? Can you share more details requested? Otherwise please close the issue.

**Comment by tonycody** [comment]
python instrumentation is strongly related to different python package versions. When tracing cannot be obtained, you can try to change the package of a lower version.
