### ISSUE TITLE
Instrument SQLAlchemy engine connection phase

### ISSUE THREAD

**Issue by shahargl** [open-telemetry/opentelemetry-python-contrib#1133]
** Is your feature request related to a problem? **
The SQLAlchemy instrumentation does not trace the actual connection to the database

**Describe the solution you'd like**
I want that `connect` function will also be traced

**Describe alternatives you've considered**
Which alternative solutions or features have you considered?

**Additional context**
We are working with SQLAlchemy (snowflake db) and we implemented a solution where we can see the `connect` span also as attached in the screenshot (the span is `database-connect`)
![image](https://user-images.githubusercontent.com/12069200/173789203-b75f42d2-7ae6-4c11-aa0c-4937ede75422.png)

**Comment by shahargl** [comment]
I've created a PR adding this functionality - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1134
I've tested this only for our infrastructure so I'll be happy if you will help me with testing this (or tell me how to do the tests my self)

**Comment by theobouwman** [comment]
Does this suggest that it creates a connection for each query?
Because if thats the case then I probably found out why with multiple request our API responses are around 1second right?

![Screenshot 2023-11-08 at 15 47 56](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/16098190/e47da7ae-7b03-4348-bd37-6fa5e3700d25)
![Screenshot 2023-11-08 at 15 48 00](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/16098190/5fc0ce95-b994-4750-9963-87037bc5ba27)


![Screenshot 2023-11-08 at 15 46 50](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/16098190/b2dfce36-3228-4d03-9032-d5e33e63efc4)

**Comment by shahargl** [comment]
From your image it looks like there is a `connect` before `SELECT` but I don't have the full context to say if that's the reason.

**Comment by theobouwman** [comment]
@shahargl so it creates a `connection` for each `select` here right? Because then my FastAPI SQLAlchemy implementation is not right. Should just have a share connection pool i guess.

**Comment by theobouwman** [comment]
```python

class Database:

    def __init__(self, db_url: str) -> None:
        self._engine = create_engine(
            db_url,
            echo=get_config().QUERY_ECHO,
            json_serializer=_custom_json_serializer,
            pool_pre_ping=True,
            pool_size=get_config().DB_POOL_SIZE,
        )
        self._session_factory = orm.scoped_session(
            orm.sessionmaker(
                autocommit=False,
                autoflush=False,
                bind=self._engine,
            ),
        )

    def create_database(self) -> None:
        Base.metadata.create_all(self._engine)

    @contextmanager
    def session(self) -> Callable[..., AbstractContextManager[Session]]:
        session: Session = self._session_factory()
        try:
            yield session
        except Exception as e:
            # logger.exception("Session rollback because of exception")
            session.rollback()
            raise e
        finally:
            session.close()

```

and our dependency injector:
```python
from dependency_injector import containers, providers

class Container(containers.DeclarativeContainer):

    wiring_config = containers.WiringConfiguration(packages=[
        "api.routes",
        "tasks.routes",
        "common.observability"
    ])

    config = providers.Configuration()

    db = providers.Singleton(Database, db_url=get_config().DB_URL())
```

And then our Repository uses:

```python
event_repository = providers.Factory(EventRepository, session_factory=db.provided.session)
```
