### ISSUE TITLE
Metrics instrumentation sqlalchemy

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1143]
Spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/database-metrics.md

**Comment by awuorm** [comment]
Hi, I'd like to work on this issue

**Comment by shalevr** [comment]
Hi, [awuorm](https://github.com/awuorm) Do you working on this or can I take this issue?

**Comment by srikanthccv** [comment]
@awuorm since there is no (draft) work so far and no response to previous comment I am unassigning you. Feel free to come back and pick something else when you get some time to contribute.
