### ISSUE TITLE
Metrics instrumentation starlette

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1146]
HTTP Server semconv https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server

**Comment by sanketmehta28** [comment]
Hi Can you assign it to me?

**Comment by rahulmukherjee68** [comment]
hey @srikanthccv Can you assign this to me .

**Comment by sanketmehta28** [comment]
@rahulmukherjee68 I have assigned it to you
