### ISSUE TITLE
Metrics instrumentation pyramid

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1149]
HTTP metrics semconv: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md

**Comment by ashu658** [comment]
Can you assign this to me?

**Comment by ashu658** [comment]
I am a bit busy these days. Does someone wants to take up this issue?

**Comment by TheAnshul756** [comment]
Hello @ashu658 
I'm willing to work on this issue. Can you please assign this to me?

**Comment by ashu658** [comment]
Thanks @TheAnshul756 
Assigned!
