### ISSUE TITLE
Metrics instrumentation asgi

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1160]
HTTP Metrics: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md

**Comment by mmalecki** [comment]
I started working on this by following WSGI's package's lead. I can't really make any promises as I'm having some trouble setting up my dev environment, but thought I'd drop a note here.

**Comment by srikanthccv** [comment]
I am going to assign this to you. If you can't work on it anymore just leave a comment.

**Comment by TheAnshul756** [comment]
@mmalecki If you have not yet started working on it or if you are stuck, I would like to pick this issue. Also this issue is a blocker for #1156 assigned to me.
c.c.: @srikanthccv

**Comment by mmalecki** [comment]
Please do @TheAnshul756. I got stuck, sadly.
