### ISSUE TITLE
Sqlalchemy uninstrument function doesnt work as expected 

### ISSUE THREAD

**Issue by liorzmetis** [open-telemetry/opentelemetry-python-contrib#1163]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version: 3.9

**Steps to reproduce**
 Just create a SQLAlchemy instrumentation and call `uninstrument` function
 Example:
```python
db_url = os.environ['DATABASE_URI']

engine = create_engine(db_url)

instrumentation = SQLAlchemyInstrumentor()
instrumentation.instrument(
    engine=engine
)

def set_interval(func, sec):
    def func_wrapper():
        # set_interval(func, sec)
        func()

    t = threading.Timer(sec, func_wrapper)
    t.start()
    return t


def instrument():
    print("instrument")
    instrumentation.instrument_app(app, engine)


def uninstrument():
    print("uninstrument")
    instrumentation.uninstrument()


set_interval(instrument, 1)
set_interval(uninstrument, 20)

```

**What is the expected behavior?**
Don't collect spans 

**What is the actual behavior?**
Still recording and collecting spans

**Additional context**

**Comment by avzis** [comment]
I don't think this is still relevant.
validated by this PR: #1471 

On a side note, you should call `instrument()` instead of `instrument_app()` when instrumenting

**Comment by srikanthccv** [comment]
@liorzmetis please share fully reproducible example that still have issue.

**Comment by shalevr** [comment]
I think I get the problem, The problem is with the Engine.
inside the Engine we call listen on events:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/c92ba14316a90db2a8e8a7702aa21ce114a581a5/instrumentation/opentelemetry-instrumentation-sqlalchemy/src/opentelemetry/instrumentation/sqlalchemy/engine.py#L108
But no one call remove on the events after the instrument
and for the uninstrument test, I created a new engine after uninstrument so the test missed this

**Comment by devopsmetis** [comment]
> I think I get the problem, The problem is with the Engine. inside the Engine we call listen on events:
> 
> https://github.com/open-telemetry/opentelemetry-python-contrib/blob/c92ba14316a90db2a8e8a7702aa21ce114a581a5/instrumentation/opentelemetry-instrumentation-sqlalchemy/src/opentelemetry/instrumentation/sqlalchemy/engine.py#L108
> 
> 
> But no one call remove on the events after the uninstrument
> and for the uninstrument test, I created a new engine after uninstrument so the test missed this
> I will fix this

Yeap, the engine still receiving events after uninstrument function has been called 
In the mean time i fixed it on my project side by remove the event listener from the current engine:
```
    def _uninstrument(self, **kwargs):
        super()._uninstrument(**kwargs)
        engine = self.exporter_tracer.engine
        event.remove(engine, "before_cursor_execute", self.before_query_hook)
        event.remove(engine, "after_cursor_execute", _after_cur_exec)
        event.remove(engine, "handle_error", _handle_error)
```

**Comment by liorzmetis** [comment]
> I think I get the problem, The problem is with the Engine. inside the Engine we call listen on events:
> 
> https://github.com/open-telemetry/opentelemetry-python-contrib/blob/c92ba14316a90db2a8e8a7702aa21ce114a581a5/instrumentation/opentelemetry-instrumentation-sqlalchemy/src/opentelemetry/instrumentation/sqlalchemy/engine.py#L108
> 
> 
> But no one call remove on the events after the uninstrument
> and for the uninstrument test, I created a new engine after uninstrument so the test missed this
> I will fix this

Yeap, the engine still receiving events after uninstrument function has been called 
In the mean time i fixed it on my project side by remove the event listener from the current engine:
```
    def _uninstrument(self, **kwargs):
        super()._uninstrument(**kwargs)
        engine = self.exporter_tracer.engine
        event.remove(engine, "before_cursor_execute", self.before_query_hook)
        event.remove(engine, "after_cursor_execute", _after_cur_exec)
        event.remove(engine, "handle_error", _handle_error)
```
