### ISSUE TITLE
AsyncPG Instrumentation Span Names are too long when using query string

### ISSUE THREAD

**Issue by theelderbeever** [open-telemetry/opentelemetry-python-contrib#1170]
**Is your feature request related to a problem?**
Not a problem per se however, the `asyncpg` instrumentation uses sets span names as the query string which results in some very messing looking trace names in jaeger, datadog, etc and outright doesn't work with promscale due to long queries exhaust the available bytes for btree indexes.

**Describe the solution you'd like**
- The ability to change the name of the span with a hook or something similar. The `httpx` instrumentation provides hooks that receive the span and the name can be updated there.
- Just use a shorter or truncated version of the query as the name.

Which alternative solutions or features have you considered?
Not using the `asyncpg` instrumentation and manually instrumenting specific queries.

**Comment by krnr** [comment]
psycopg instrumentation uses only [the first word of the statement](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-psycopg2/src/opentelemetry/instrumentation/psycopg2/__init__.py#L218-L219). i think i can do the same with asyncpg.

**Comment by srikanthccv** [comment]
span name shouldn't be a high cardinal value such as a statement. feel free to send a patch.
