### ISSUE TITLE
Feature Request: opentelemetry-instrumentation-urllib3 add support for custom span names via callback

### ISSUE THREAD

**Issue by ZachTB123** [open-telemetry/opentelemetry-python-contrib#1175]
`opentelemetry-instrumentation-urllib3` always uses a default span name [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-urllib3/src/opentelemetry/instrumentation/urllib3/__init__.py#L164). It would be nice if a custom name callback was supported like `opentelemetry-instrumentation-requests` does [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py#L164-L165).

**Comment by avzis** [comment]
hi, can you assign this to me? thanks :)

**Comment by lzchen** [comment]
@avzis 
We are actually getting rid of span name callbacks in favor of request/response hooks. PTAL at https://github.com/open-telemetry/opentelemetry-python-contrib/issues/411 and implement it using hooks instead of callbacks if you are still interested in working on this.

**Comment by pgadige** [comment]
@lzchen PR #576 implements it using hooks. Is there additional work to add on top of these changes?
cc: @srikanthccv

**Comment by srikanthccv** [comment]
I believe this is no longer required.
