### ISSUE TITLE
opentelemetry-instrumentation-remoulade is >= 3.7 .. breaks opentelemetry-contrib-instrumentations install on 3.6

### ISSUE THREAD

**Issue by whardier** [open-telemetry/opentelemetry-python-contrib#1185]
Need to add in a python version exclusion in https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-contrib-instrumentations/setup.cfg for remoulade.

**Comment by ocelotl** [comment]
@whardier just to let you know, we just removed support for 3.6

**Comment by srikanthccv** [comment]
This shouldn't be an issue anymore since we no longer support 3.6
