### ISSUE TITLE
HTTP instrumentations 0.32b0  compatibility issue with opentelemetry-api 1.11.1

### ISSUE THREAD

**Issue by mariojonke** [open-telemetry/opentelemetry-python-contrib#1190]
The latest release added the `_SUPPRESS_HTTP_INSTRUMENTATION_KEY` to the `opentelemetry.context` module in the `opentelemetry-api`.
Instrumentations `botocore`, `requests`, `urllib`, and `urllib3` are importing this key in their latest version. These packages however claim to be compatible with `opentelemetry-api ~= 1.3`

Since the latest `opentelemetry-api` (1.12.rc2) is only available as release candidate installing the latest e.g. requests instrumentation will result in an installation with `opentelemetry-instrumentation-requests` in version 0.32b0 with `opentelemetry-api` in version 1.11.1

Trying to import the instrumenation package will now result in an import error:
```
from opentelemetry.instrumentation import requests

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 64, in <module>
    from opentelemetry.context import _SUPPRESS_HTTP_INSTRUMENTATION_KEY
ImportError: cannot import name '_SUPPRESS_HTTP_INSTRUMENTATION_KEY' from 'opentelemetry.context' (.venv/lib/python3.8/site-packages/opentelemetry/context/__init__.py)

```

**Comment by ocelotl** [comment]
This should be solved once we release metrics as stable instead of as a RC.

**Comment by srikanthccv** [comment]
@mariojonke the old versions had incompatibility because of the metrics RC version. This shouldn't be a problem with the latest stable release. Please re-open if the issue still exists.
