### ISSUE TITLE
`metrics_exporter none` is required when using `opentelemetry-instrument` without metrics

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry-python-contrib#1192]
This was noted in a PR here: https://github.com/open-telemetry/opentelemetry.io/pull/1545

I'm happy to approve the docs PR in the interim, but without the changes it proposes there will be a runtime error thrown when using `opentelemetry-instrument` as-documented. I think it's kind of surprising - if I'm not using metrics, I wouldn't expect to have to set `metrics_exporter none` to avoid an error message. Is that by design?

**Comment by srikanthccv** [comment]
I think I know the issue here. We have released the fix with exporter entry point with default to grpc in rc2 but the pip doesn't install release candidate unless you explicitly pin it to rc. So the users still run with 1.11.1 which had the issue.

**Comment by ocelotl** [comment]
@cartermp please try installing the latest RC2 and running again.

**Comment by srikanthccv** [comment]
@cartermp it is quite sometime since this issue opened and we have released the 1.2 with public metrics. This shouldn't be an issue anymore with the latest release. Please feel free to reopen if it is not resolved.
