### ISSUE TITLE
Add instrumentor for PyMongo

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#12]
Add instrumentor for PyMongo. Below are existing instrumentor implementations:

[DataDog](https://github.com/open-telemetry/opentelemetry-auto-instr-python/tree/master/ddtrace/contrib/pymongo)
[SignalFx](https://github.com/signalfx/signalfx-python-tracing/tree/master/signalfx_tracing/libraries/pymongo_)

**Comment by codeboten** [comment]
Started looking at porting the pymongo instrumentation from https://github.com/open-telemetry/opentelemetry-python/tree/master/ext/opentelemetry-ext-pymongo
