### ISSUE TITLE
boto3sqs: Do not override propagator-determined key

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-python-contrib#1202]
The boto3sqs instrumentation prepends "otel." to all attributes it adds to SQS messages (relevant code: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/7c75b3867bb81d59037e7a3f5ab5c3dfe1bb5733/instrumentation/opentelemetry-instrumentation-boto3sqs/src/opentelemetry/instrumentation/boto3sqs/__init__.py#L56-L82). This will make it impossible to write a propagator that works with instrumentations (of OTel or other vendors) that don't use this prefix.

The reasons cited at https://www.oxeye.io/blog/diving-into-opentelemetrys-specs:

* Prevents propagators setting keys that start with AWS. or Amazon., which would be rejected -- a rather weak reason IMHO as this is very unlikely to happen and there are other, perhaps more likely, rules that keys must adhere to that are not addressed.
* Keys needed for extraction, or prefix thereof, must be known before calling the receive API which requires a list of attributes to receive -- this can be solved by using [`TextMapPropagator.fields`](https://github.com/open-telemetry/opentelemetry-python/blob/v1.11.1/opentelemetry-api/src/opentelemetry/propagators/textmap.py#L185-L196), although it is meant for listing injected fields, these will usually be the same as extracted ones. This is also what Node.Js does: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/1db1fecc16ecb3dbad530de530418260e54c087a/plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts#L71-L75

So I suggest to remove the `otel.` prefix and instead use  [`TextMapPropagator.fields`](https://github.com/open-telemetry/opentelemetry-python/blob/v1.11.1/opentelemetry-api/src/opentelemetry/propagators/textmap.py#L185-L196) to ensure the required attributes are fetched.

CC @oxeye-nikolay

**Comment by melvinkcx** [comment]
Hi, I stumbled upon this while looking into the right way of "propagating" context across queues and other asynchronous means. It doesn't seem like the spec [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md) covers such use cases. It is apparent that we already have a divergence in handling such propagation. 

Just a suggestion, wouldn't it makes more sense if we could somehow agree upon the details and make it part of the spec (or recommendations)? I'm not familiar with how things work when it comes to OTEL spec, any insights will be much appreciated =)

**Comment by Oberon00** [comment]
> It is apparent that we already have a divergence in handling such propagation.

This instrumentation is the first I have seen that came up with modifying the key names determined by the propagator. There is discussion on context propagation for messaging in general at https://github.com/open-telemetry/oteps/pull/192, but it doesn't cover the particular details about how to transport the context either. You could add a comment there.

**Comment by oxeye-nikolay** [comment]
Hey, I apologize it took me a while to get to it.
I am very happy this is being brought up. It is an issue I was discussing a lot and honestly, no one has brought up the [TextMapPropagator.fields](https://github.com/open-telemetry/opentelemetry-python/blob/v1.11.1/opentelemetry-api/src/opentelemetry/propagators/textmap.py#L185-L196) solution. It still doesn't handle the `AWS/Amazon` prefix issue, but as you said it is less likely.
Let's get this PR merged
