### ISSUE TITLE
instrumentation-aiohttp-client: Number of created spans per request increases by 1 with every new request

### ISSUE THREAD

**Issue by mariojonke** [open-telemetry/opentelemetry-python-contrib#1207]
Latest release 0.32b0 introduced a bug where an additional span is created every time a new aiohttp ClientSession is created. This leads to 1 span per request when the first session is created, 2 spans when the second session gets created, ... and so on.

When `AioHttpClientInstrumentor.instrument()` the instrumentor intercepts the `ClientSession.__init__` call and injects a TraceConfig instance into the parameters that are passed to the ClientSession. With the latest release an additional parameter `trace_configs` was added to the `AioHttpClientInstrumentor.instrument()` method.
The problem is that the `trace_configs` argument is now injected into every newly created ClientSession but it is also shared between all ClientSessions. 
Every time a new ClientSession is created the instrumented `__init__` call now adds one additional trace_config to the shared `trace_configs` argument (associated code can be found [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/v0.32b0/instrumentation/opentelemetry-instrumentation-aiohttp-client/src/opentelemetry/instrumentation/aiohttp_client/__init__.py#L281-L282)). Since one trace_config defines the hooks to create and end one span, every added trace_config will produce an additional span per request.

**Steps to reproduce**
Instrument the aiohttp-client with `AioHttpClientInstrumentor.instrument()`.  Create at least two ClientSessions and make one HTTP request to some arbitrary URL. The produced spans increase with every new ClientSession that is created.

Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
One span per HTTP request independent of the number of ClientSessions that are created.

**What is the actual behavior?**
Number of created spans increase with each newly created ClientSession.

**Comment by mariojonke** [comment]
Thinking about it some more i don't quite see the purpose of the newly added `trace_configs` parameter in `AioHttpClientInstrumentor.instrument()`. 
A `TraceConfig` is the mechanism that aiohttp provides to trace requests by registering callbacks for all kind of events (start, end, exception, ...). This is what the instrumentor already uses to create and end spans accordingly. From an OpenTelemetry point of view adding further TraceConfigs would just mean creating more spans. So imo the `trace_configs` parameter to externally add additional TraceConfigs doesn't make much sense.

**Comment by n0nvme** [comment]
Same problem with 0.33b0 release

**Comment by srikanthccv** [comment]
@mariojonke if the last change is not necessary feel free to send a pull request with fix.
