### ISSUE TITLE
LICENCE file missing from the opentelemetry-instrumentation-aio-pika

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-python-contrib#1219]
LICENCE file missing from the below location:

[opentelemetry-instrumentation-aio-pika](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aio-pika)

**Comment by srikanthccv** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/893
