### ISSUE TITLE
MANIFEST file missing form the opentelemetry-instrumentation-aio-pika/

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-python-contrib#1221]
Manifest file missing from the location:

[opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)/[instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation)/opentelemetry-instrumentation-aio-pika/

**Comment by srikanthccv** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/893
