### ISSUE TITLE
Update package metadata for all packages

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1259]
Following this https://github.com/open-telemetry/opentelemetry-python/pull/2867, remove setup.py, setup.cfg in favor of pyproject.toml to specify metadata for all packages. This issue can be used as a overall tracking issue. Feel free to open up individual issues per package and link them to this one.

**Comment by ofek** [comment]
Progress:

- `_template/setup.cfg` (PR )
- `exporter/opentelemetry-exporter-datadog` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1261)
- `exporter/opentelemetry-exporter-richconsole` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1262)
- `instrumentation/opentelemetry-instrumentation-aio-pika` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1263)
- `instrumentation/opentelemetry-instrumentation-aiohttp-client` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1264)
- `instrumentation/opentelemetry-instrumentation-aiopg` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1265)
- `instrumentation/opentelemetry-instrumentation-asgi` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1266)
- `instrumentation/opentelemetry-instrumentation-asyncpg` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1267)
- `instrumentation/opentelemetry-instrumentation-aws-lambda` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1268)
- `instrumentation/opentelemetry-instrumentation-boto` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1269)
- `instrumentation/opentelemetry-instrumentation-boto3sqs` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1270)
- `instrumentation/opentelemetry-instrumentation-botocore` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1271)
- `instrumentation/opentelemetry-instrumentation-celery` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1272)
- `instrumentation/opentelemetry-instrumentation-confluent-kafka` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1273)
- `instrumentation/opentelemetry-instrumentation-dbapi` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1274)
- `instrumentation/opentelemetry-instrumentation-django` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1275)
- `instrumentation/opentelemetry-instrumentation-elasticsearch` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1276)
- `instrumentation/opentelemetry-instrumentation-falcon` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1277)
- `instrumentation/opentelemetry-instrumentation-fastapi` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1278)
- `instrumentation/opentelemetry-instrumentation-flask` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1279)
- `instrumentation/opentelemetry-instrumentation-grpc` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1280)
- `instrumentation/opentelemetry-instrumentation-httpx` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1281)
- `instrumentation/opentelemetry-instrumentation-jinja2` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1282)
- `instrumentation/opentelemetry-instrumentation-kafka-python` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1283)
- `instrumentation/opentelemetry-instrumentation-logging` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1284)
- `instrumentation/opentelemetry-instrumentation-mysql` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1285)
- `instrumentation/opentelemetry-instrumentation-pika` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1286)
- `instrumentation/opentelemetry-instrumentation-psycopg2` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1287)
- `instrumentation/opentelemetry-instrumentation-pymemcache` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1288)
- `instrumentation/opentelemetry-instrumentation-pymongo` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1289)
- `instrumentation/opentelemetry-instrumentation-pymysql` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1290)
- `instrumentation/opentelemetry-instrumentation-pyramid` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1291)
- `instrumentation/opentelemetry-instrumentation-redis` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1292)
- `instrumentation/opentelemetry-instrumentation-requests` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1293)
- `instrumentation/opentelemetry-instrumentation-sklearn` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1294)
- `instrumentation/opentelemetry-instrumentation-sqlalchemy` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1295)
- `instrumentation/opentelemetry-instrumentation-sqlite3` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1296)
- `instrumentation/opentelemetry-instrumentation-starlette` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1297)
- `instrumentation/opentelemetry-instrumentation-system-metrics` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1298)
- `instrumentation/opentelemetry-instrumentation-tornado` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1299)
- `instrumentation/opentelemetry-instrumentation-urllib` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1300)
- `instrumentation/opentelemetry-instrumentation-urllib3` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1301)
- `instrumentation/opentelemetry-instrumentation-wsgi` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1302)
- `opentelemetry-contrib-instrumentations` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1303)
- `opentelemetry-distro` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1304)
- `opentelemetry-instrumentation` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1305)
- `propagator/opentelemetry-propagator-aws-xray` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1306)
- `propagator/opentelemetry-propagator-ot-trace` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1307)
- `sdk-extension/opentelemetry-sdk-extension-aws` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1308)
- `util/opentelemetry-util-http` (PR https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1309)

**Comment by ofek** [comment]
@srikanthccv @ocelotl Everything is passing except for `py*-test-instrumentation-grpc` which is failing on all new PRs

**Comment by srikanthccv** [comment]
Have seen this happen intermittently. I will look into it.

**Comment by srikanthccv** [comment]
I think the [generate](https://github.com/open-telemetry/opentelemetry-python-contrib/runs/8156565370?check_suite_focus=true) workflow is failing for the same reason described here https://github.com/open-telemetry/opentelemetry-python/issues/2920

**Comment by ofek** [comment]
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1318

**Comment by ofek** [comment]
all pass now

**Comment by srikanthccv** [comment]
The generate works is still failing https://github.com/open-telemetry/opentelemetry-python-contrib/runs/8234810892?check_suite_focus=true

**Comment by srikanthccv** [comment]
@ofek this script [file](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/scripts/eachdist.py) needs to be updated to use the global config. We can't merge the PR unless that workflow also passes.

**Comment by ofek** [comment]
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1322

**Comment by ofek** [comment]
oops need to reopen

**Comment by ofek** [comment]
complete 😄

**Comment by srikanthccv** [comment]
I will close this after this gets merged https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1329

**Comment by ofek** [comment]
ah ok, fyi my source was https://github.com/open-telemetry/opentelemetry-python-contrib/pull/853/files

**Comment by ofek** [comment]
take care!
