### ISSUE TITLE
Address lint failures

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#127]
During the shift of instrumentation and exporter packages to the contrib repo, some issues were found in the linting, see failures here: 

https://github.com/open-telemetry/opentelemetry-python-contrib/runs/1349549074

See discussion in gitter: https://gitter.im/open-telemetry/opentelemetry-python?at=5fa1b98bbf955735eb595894

**Comment by NathanielRN** [comment]
Specifically, this command in `eachdist.py` is the lint command that is failing. For some reason it says the items in the `insturmentation/` package are not lint compliant, even though they were compliant when they were in the Core repo and this was directly brought over from the Contrib repo.

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/5c9e043d6921550d82668788e3758a733fb11cb8/scripts/eachdist.py#L518-L522
