### ISSUE TITLE
FalconInstrumentor().uninstrument() method do not uninstrument existing Falcon Apps

### ISSUE THREAD

**Issue by TheAnshul756** [open-telemetry/opentelemetry-python-contrib#1325]
Similar to #1256  in FastAPI, falcon uninstrument method do not uninstrument existing falcon instrumented apps, which is not the expected behaviour.

**Comment by TheAnshul756** [comment]
@srikanthccv Please assign this to me.

**Comment by TheAnshul756** [comment]
Hello @srikanthccv 
Looks like there is no method to manually uninstrument an api/app in falcon similar to [`uninstrument_app` in fastapi](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L201). Should I implement one, as it will be required to uninstrument existing instances?

**Comment by srikanthccv** [comment]
To reduce the scope of this issue just add a private helper which can pop the middleware. The `instrument_app`/`uninstrument_app` can be a feature request to address in separate ticket.
