### ISSUE TITLE
Getting ZeroDivisionError  in Swap Utilization

### ISSUE THREAD

**Issue by lucasteles** [open-telemetry/opentelemetry-python-contrib#1337]
**Describe your environment**
Python: 3.9
opentelemetry-instrumentation-psycopg2 = "^0.33b0"
opentelemetry-instrumentation-django = "^0.33b0"
opentelemetry-instrumentation-celery = "^0.33b0"
opentelemetry-exporter-otlp-proto-grpc = "^1.12.0"
Running on ECS (Docker)

The problem is with system metrics in this line, the when container is configured without swap memory
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/76a565e8bde7f81a04315eae8431d21fc6e79383/instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py#L503

**Steps to reproduce**
Create a container with 0 Swap memory and run with system metrics

**What is the expected behavior?**
Just work

**What is the actual behavior?**
Giving ZeroDivisionError

**Comment by yulin-li** [comment]
Got same issue, sent out a PR #1345 to fix
