### ISSUE TITLE
Decide what to do about the deprecated packages on main

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1358]
Their versions are not updated but they remain on the main branch. This means the scripts need to keep a list of packages that needs skipping and special treatment makes them prone to issues.

**Comment by ocelotl** [comment]
If a package is declared deprecated (this meaning it won't receive any more changes of any kind) we should remove them in the next release. The less code the better and if someone needs that package source code for any reason they can read the changelog and check out the repo at the last version that included that package.

**Comment by lzchen** [comment]
@ocelotl 
I agree with this, at least remove them from main. If we need further discussion, feel free to add this to Thursday's agenda topics.
