### ISSUE TITLE
confluent-kafka-python produce headers could be dict or a list

### ISSUE THREAD

**Issue by owenhaynes** [open-telemetry/opentelemetry-python-contrib#1364]
Environment

Python 3.10
confluent-kafka[avro]==1.9.2
opentelemetry-instrumentation-confluent-kafka==0.34b0

**Steps to reproduce**
Pass a dict of headers to the producer 

**What is the expected behavior?**
To not crash and handle using a list or a dict for the headers

**What is the actual behavior?**
crashes because of calling append on a dict of headers in KafkaContextSetter

**Additional context**
The docs say produce can take a dict or a list https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.produce

**Comment by avzis** [comment]
hi, can you assign this to me?

**Comment by alolita** [comment]
@srikanthccv @lzchen can you please assign @mrajashree to this issue since there is no PR submission from the current assignee. Thanks!

**Comment by srikanthccv** [comment]
@avzis let us know if you had already worked on this. I will assign @mrajashree otherwise. @mrajashree can you please a leave a comment here.

**Comment by avzis** [comment]
I'm not working on it, you can assign this to him

**Comment by mrajashree** [comment]
thanks, glad to pick it up
