### ISSUE TITLE
Recurring python version conflict error after every release

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-python-contrib#1375]
**Describe your environment** 
This issue is created to kick off the discussion and lead to possible solution for the version conflict error. 

After a new release in `otel-python` and `otel-python-contrib` the usage of the instrumentation in previous releases is leading to version conflct error. While using the instrumentations of previous release `1.12.0` has broken when using the current Release `1.13.0`  
it is suspected that pinned version requirement dependency of opentelemetry-sdk in [opentelemetry-distro](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-distro/pyproject.toml#L28) might be the reason.

Use compatible Runtime `~=` for dependencies like [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/sdk-extension/opentelemetry-sdk-extension-aws/pyproject.toml#L27) ? in opentelemetry-distro and any other similar places. 

**What is the expected behavior?**
No Version conflict and ease to use the instrumentation of previous release version.
 
**What is the actual behavior?**
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/41936996/194120450-21110772-2cd3-40fa-b6b2-74875bcde070.png">

**Additional context**
For more context [requirements.txt](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/src/otel/otel_sdk/requirements.txt)
[Relevant slack thread](https://cloud-native.slack.com/archives/C01PD4HUVBL/p1661927606492329)

**Comment by srikanthccv** [comment]
Feel free to send a PR. I don't see any reason for hard pinning sdk version in distro package since unless they need to use latest changes from SDK release.
