### ISSUE TITLE
Add hook to set custom span name in django instrumentation

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#138]
Similar to [wsgi](https://github.com/open-telemetry/opentelemetry-python/blob/master/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L210), accept a callback function in `DjangoInstrumentor().instrument` to be able to pass custom span name.

The [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name) say "MAY" for this feature, but we should be consistent across our instrumentations.

Part of https://github.com/open-telemetry/opentelemetry-python/issues/1297

**Comment by NickSulistio** [comment]
I can take on this issue! @nicksulistio

cc @alolita

**Comment by owais** [comment]
@NickSulistio I added request/response hooks to Django instrumentation. They can be used to set span name (among other things) on the server span. I think adding a special hook just for span name would be redundant after these changes. Sorry about not notifying you earlier about this. 

Good news is that we need similar request/response hooks for all web server instrumentations such as flask, falcon, tornado etc and you can implement that if you'd like. Let me know if that's interesting to you and we can discuss it.

**Comment by owais** [comment]
More details: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/408

**Comment by NickSulistio** [comment]
Hi @owais, do you think that these would be good first issues? This is the first time I'm contributing to an open source project, so I think that if this issues are not too complicated then I would be willing to take them!

**Comment by owais** [comment]
Yes, they're the same complexity as the span name callback was. They're very similar actually. Feel free to ping me on slack if you need help with anything.
