### ISSUE TITLE
Make sure rpc instrumentations follow semantic conventions

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#139]
Specs: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md

**Comment by alertedsnake** [comment]
I'm on this one - I did most of the re-implementation anyway, and it was pretty easy to do.
Will have a PR up as soon as I look into #173 as well.
