### ISSUE TITLE
aiohttp-client: Allow overriding of span status

### ISSUE THREAD

**Issue by nils-borrmann-y42** [open-telemetry/opentelemetry-python-contrib#1393]
Version 0.34b0

In the aiohttp-client instrumentation, the `response_hook` is [called before setting the status and the status_code of the span](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/75953f3b25c2ffb5427371aaf065671b441aca26/instrumentation/opentelemetry-instrumentation-aiohttp-client/src/opentelemetry/instrumentation/aiohttp_client/__init__.py#L235). This means the user cannot set a custom status on the span, as it will be immediately overridden by the default value. 

In my specific usecase I am making requests as a cache, where a cache-miss returns a 404 response. These spans are than tagged with the `StatusCode.ERROR`, which is a bit annoying to me as these responses are completely expected and accepted. Therefore I would like to override the StatusCode on those requests in the response_hook.

I am happy to provide a fix for this.

**What is the expected behavior?**
`reponse_hook` should be called after setting the span status, to allow for overriding it.

**What is the actual behavior?**
`reponse_hook` is called before setting the span status

**Additional context**
I compared this with the httpx and requests instrumentation. In those instrumentations, overriding the status in the hook is possible.

**Comment by srikanthccv** [comment]
It's because the semantic conventions enforce it for the HTTP clients https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status.

**Comment by nils-borrmann-y42** [comment]
> It's because the semantic conventions enforce it for the HTTP clients [open-telemetry/opentelemetry-specification@`main`/specification/trace/semantic_conventions/http.md#status](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md?rgh-link-date=2022-10-21T15%3A07%3A09Z#status).

Which is fine, but otel could still let the user decide to override it in specific cases (which is what most other implementations already do).
