### ISSUE TITLE
Setting OTEL_TRACES_EXPORTER=none does not stop the trace exporter

### ISSUE THREAD

**Issue by kwmlodozeniec** [open-telemetry/opentelemetry-python-contrib#1396]
In my environment I set OTEL_TRACES_EXPORTER to none during local development but I still get repeated exceptions in the logs as traces are being exported. Any ideas how to disable the export completely?

My stack uses FastAPI and Requests instrumentation and the exception I'm getting is

```
ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4318): Max retries exceeded with url: /v1/traces
```

**Comment by srikanthccv** [comment]
Please provide a simple reproducible example.

**Comment by kwmlodozeniec** [comment]
requirements
```
fastapi
opentelemetry-api
opentelemetry-sdk
opentelemetry-exporter-otlp-proto-http
opentelemetry-instrumentation-fastapi
uvicorn
structlog
```

`app.py`
```
import fastapi
import structlog
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

logger = structlog.get_logger("logger")


app = fastapi.FastAPI()

provider = TracerProvider()
batch_processor = BatchSpanProcessor(OTLPSpanExporter())

provider.add_span_processor(batch_processor)

trace.set_tracer_provider(provider)
FastAPIInstrumentor.instrument_app(app)


@app.get("/")
async def home():
    return {"msg": "Some message"}
```

Create the env, place `app.py` in some dir for example `sample`, install dependecies, and run with
```
export OTEL_TRACES_EXPORTER="none"
uvicorn sample.app:app --host 0.0.0.0 --port 8001
```

hit the root endpoint and after a few seconds the logs should have this exception
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa780672ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by srikanthccv** [comment]
No, that works when you use the auto instrumentation and set the env, and it doesn't prevent you from setting the trace pipeline with the exporter manually. What would it mean to use `jaeger` for `OTEL_TRACES_EXPORTER`  with the above code? Does it magically change the exporter from OTLP to Jaeger? 

This is working as expected.

**Comment by kwmlodozeniec** [comment]
Okay, so it seems I've misunderstood the mechanism. Is there a way of
disabling the exporter through an env variable? Or would it be a matter of
checking for a config and then instrumenting or not?

**Comment by srikanthccv** [comment]
If you are not interested in exporting in above program you shouldn't set the tracer provider. Alternatively you may want to look at the `opentelemetry-instrument` auto instrument command which honours the env var.
