### ISSUE TITLE
Add instrumentor for Requests

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#14]
Add instrumentor for Requests. Below are existing instrumentor implementations:

[DataDog](https://github.com/open-telemetry/opentelemetry-auto-instr-python/tree/master/ddtrace/contrib/requests)
[SignalFx](https://github.com/signalfx/signalfx-python-tracing/tree/master/signalfx_tracing/libraries/requests_)

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/open-telemetry/opentelemetry-python/pull/597.
