### ISSUE TITLE
Automate release workflow

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#1437]
Similar to [this](https://github.com/open-telemetry/opentelemetry-python/pull/2649) for the core repo, automate the release workflow for contrib. This might be a bit tricky if we want to still require builds needing to pass for release branches (since the whole relationship between the core and contrib releases needing to change SHAs). We can either 1. Not require builds to pass for releases or 2. Change the SHAs automatically as part of the release workflow.

@srikanthccv @ocelotl

**Comment by srikanthccv** [comment]
@lzchen, here is what I am thinking about updating the SHAs. We will create a new workflow that runs a script to update the SHA automatically. This script takes the branch name for core/contrib and updates `test.yaml` with the latest commit ID. First, we will let the bot create the release branches and then run another workflow to update SHA. What do you think?

**Comment by lzchen** [comment]
@srikanthccv 

Would a new PR be created to update the SHA on the release branches or will that automatically be done committed?

**Comment by srikanthccv** [comment]
The way I was thinking was the prepare-release workflow creates PRs in core and contrib. And then you would add a label `update-sha` which runs another workflow, and the bot updates the SHA for its corresponding core/contrib repo.

**Comment by lzchen** [comment]
Adding a label makes sense to me. So the flow for maintainers when releasing would be:

1. Run release workflow for core, 2 PRs will be created (one against the release branch, one against main)
2. Run release workflow for contrib (when we automate it eventually), 2 PRS will be created as well
3. Add `update-sha` label to core repo release branch PR, OT bot will pull the latest SHA from contrib release branch PR and update `test.yml`. Builds should pass now for core.
4. Add `update-sha` label to contrib repo release branch PR, OT bot will pull the latest SHA from core release branch PR and update `test.yml`. Builds should pass now for contrib.
5. Merge both PRs.
6. Run release workflow and continue the workflow as [is](https://github.com/open-telemetry/opentelemetry-python/blob/main/RELEASING.md#making-the-release)
