### ISSUE TITLE
Resource detection for container properties in Flask

### ISSUE THREAD

**Issue by sanketmehta28** [open-telemetry/opentelemetry-python-contrib#1446]
**Problem**
Detect the container id in Resource in flask framework

**Describe the solution you'd like**
Collect the container.id the application is running in and pass it as resource attribute in the tracer_provider

**Comment by srikanthccv** [comment]
This is not particularly related to Flask instrumentation. Flask instrumentation works with the tracer provided or obtained from the global provider. Hence closing. See my comment here https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1372#issuecomment-1319422292
