### ISSUE TITLE
Resource detection for container properties in FastAPI

### ISSUE THREAD

**Issue by sanketmehta28** [open-telemetry/opentelemetry-python-contrib#1452]
**Problem**
Detect the container id in Resource in FastAPI framework

**Describe the solution you'd like**
Collect the container.id the application is running in and pass it as resource attribute in the tracer_provider

**Comment by srikanthccv** [comment]
Same explanation as others, this is not really related to the instrumentation of specific libraries. We support a new resource detector and it can be used anywhere.
