### ISSUE TITLE
Resource detection for container properties in Tornado

### ISSUE THREAD

**Issue by sanketmehta28** [open-telemetry/opentelemetry-python-contrib#1454]
**Problem**
Detect the container id in Resource in Tornado framework

**Describe the solution you'd like**
Collect the container.id the application is running in and pass it as resource attribute in the tracer_provider

**Comment by srikanthccv** [comment]
See comment here https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1372#issuecomment-1319422292
