### ISSUE TITLE
fastapi instrumentation: add possibility to exclude some routes

### ISSUE THREAD

**Issue by guillaume-chervet** [open-telemetry/opentelemetry-python-contrib#147]
Hi,
Thank you for that awesome lib 😊

Jaegger is crumbling under my logs because I have a “/health” route that is called every second on more than 20 services. Is it possible to add the possibility of excluding routes?

Idea exemple :

```
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

@FastAPIInstrumentor.exclude()
@app.get("/health")
async def health():
    return {"status": "OK"}

```
Or
```
FastAPIInstrumentor.instrument_app(app, ["/health"])
```

**Comment by guillaume-thomas** [comment]
Hello ! 

Thank you for this ! Do you know when the next release will be out ? We'd love to use this feature 👍 

Have a nice day !

**Comment by lonewolf3739** [comment]
From @codeboten  on [gitter](https://gitter.im/open-telemetry/opentelemetry-python?at=60007e794498e01bbfa9a52e) channel 
>the next release will be going out either today or tomorrow

// @guillaume-thomas
