### ISSUE TITLE
Add hook to set custom span name in requests instrumentation

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#149]
Similar to [wsgi](https://github.com/open-telemetry/opentelemetry-python/blob/master/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L210), accept a callback function in `RequestsInstrumentor().instrument` to be able to pass custom span name.

The [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name) say "MAY" for this feature, but we should be consistent across our instrumentations.

Part of https://github.com/open-telemetry/opentelemetry-python/issues/1297

**Comment by danielbraun89** [comment]
The requests name_callback does not accept neither method nor url as inputs. The user dont have any info to generate the name from. Shouldnt this issue remain open until the functionality is completed?

**Comment by lzchen** [comment]
@danielbraun89 
Shouldn't the user always have access to `method` and `url`? They can simply use those within the callback itself, they don't need to be passed in.

**Comment by lonewolf3739** [comment]
@lzchen I don't think user would know the `method` and `url` with `requests` instrumentation. We had discussion on whether to pass environ with [flask](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/152#discussion_r519871454) name_callback. With Flask `flask.request` is accessible to user always.

**Comment by lzchen** [comment]
Oh that is true, I misunderstood the question. I will create an issue for it.
