### ISSUE TITLE
ConfluentKafkaInstrumentor's ProxiedConsumer does not support commit

### ISSUE THREAD

**Issue by jeehun-pas** [open-telemetry/opentelemetry-python-contrib#1506]
**Describe your environment**
Python 3.8
confluent-kafka[avro]==1.9.2
opentelemetry-instrumentation-confluent-kafka==0.35b0

**Steps to reproduce**
Call ProxiedConsumer.commit

**What is the expected behavior?**
Message is committed in Kafka cluster

**What is the actual behavior?**
Get an exception with message "Consumer closed"

**Additional context**
ProxiedConsumer is not an actual Consumer but using a private internal Consumer instance to do poll, consume, etc. It is missing an over-ridden version of ProxiedConsumer.commit which calls the private Consumer's commit.

**Comment by alolita** [comment]
@srikanthccv @lzchen can you please assign @mrajashree to this issue :-) She's working on a PR for this. Thanks!

**Comment by srikanthccv** [comment]
Can you ask them to leave a comment? Username doesn't show up in the assignees dropdown otherwise.

**Comment by mrajashree** [comment]
Thanks @alolita @srikanthccv for assigning me this issue (hope my username will now show up :-) )
