### ISSUE TITLE
Add Datadog metrics exporter

### ISSUE THREAD

**Issue by ocervell** [open-telemetry/opentelemetry-python-contrib#154]
Add an exporter to ship OT metrics to Datadog. Currently only the trace exporter is available.

**Comment by alertedsnake** [comment]
I'm working on this one!

**Comment by ocervell** [comment]
@alertedsnake Any updates for this ? Gentle ping :)

**Comment by alertedsnake** [comment]
Not really - I spent a lot of time working on the [bugs](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/262) that prevented me from using this stuff for real, and then just ran out of time.  I do have a branch where I started working on it, but I'm not sure I'm going to continue - my company has been shifting towards Prometheus, so I think that exporter is going to handle our use-case once we get to using this in production.

Here's the branch if someone wants to take over:
https://github.com/alertedsnake/opentelemetry-python-contrib/tree/datadog-metrics

**Comment by srikanthccv** [comment]
See https://github.com/open-telemetry/opentelemetry-python-contrib/pull/900
