### ISSUE TITLE
Redis async calls not measured correctly

### ISSUE THREAD

**Issue by Lugoues** [open-telemetry/opentelemetry-python-contrib#1561]
I may be missing something as I am not super knowledgeable about python coroutines....
But when using the redis async client it seems that spans are not measuring the full execution time of a call and instead measures just the creation time of the coroutine.

I think the cause is [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/1f96608388711edcf251052be982dea32c033703/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/__init__.py#L158) and is due to how the redis client client wraps async calls. It ends up causing the instrumentation wrapper to not await the nested redis coroutine. In effect the span is only measuring the creation of the coroutine instead of the actual execution.  

**Steps to reproduce**
Compare the "outer" span with the "GET" span (created by the instrumentation). They should be almost equal in duration.
```
RedisInstrumentor().instrument()
redis_client = redis.Redis(port=6379)
with tracer.start_as_current_span("get_cache"):
    redis_client.get("some_key")
```
<img width="413" alt="image" src="https://user-images.githubusercontent.com/372610/210502897-f29a250f-1ad3-4d45-87f4-9cff54be9fea.png">

**What is the expected behavior?**
Span measures the entirety of the redis call.

**What is the actual behavior?**
Span only measures the time to create the coroutine

**Comment by shalevr** [comment]
Thanks for reporting this
There is an issue duplication so I'm closing this one, you can check #1829
