### ISSUE TITLE
Make sure database instrumentations follow semantic conventions

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#159]
From [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md).

**Comment by lonewolf3739** [comment]
Hi @lzchen , I tried to address this [here](https://github.com/open-telemetry/opentelemetry-python/pull/1354).

@toumorokoshi left some comments _I think there's still some reconciliation that needs to happen on the specification and the fields emitted, especially on the MongoDB side_.

Some db specific call level attributes are added which are not mentioned in spec. What are you thoughts on this?

**Comment by toumorokoshi** [comment]
Hey @lonewolf3739! Sorry about the hassle, but would you mind sending your PR again? I think the libraries moved to this repo while this PR was still in discussion.

Regarding:

>  I think there's still some reconciliation that needs to happen on the specification and the fields emitted, especially on the MongoDB side.

[Here's a spec ticket](https://github.com/open-telemetry/opentelemetry-specification/issues/1218) to start a discussion. I think some of this may be follow-up work as well, so the PR as-is would be great to merge in.

**Comment by lonewolf3739** [comment]
@toumorokoshi I don't mind opening PR here again. I just wanted to see if others can chime in and share their opinions.

**Comment by lzchen** [comment]
@lonewolf3739 

> I don't mind opening PR here again. I just wanted to see if others can chime in and share their opinions.

The extra attributes not defined in the specs can be left until the specs are finalized.

**Comment by awssandra** [comment]
Are there any more remaining?

**Comment by lonewolf3739** [comment]
@awssandra We haven't made any changes since last time. I think there should be some gaps between the specification and current implementation.

**Comment by srikanthccv** [comment]
I will create a new issue with the same title and epic containing all the db instrumentations.
