### ISSUE TITLE
Add instrumentor for Tornado

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#16]
Add instrumentor for Tornado. Below are existing instrumentor implementations:

[DataDog](https://github.com/open-telemetry/opentelemetry-auto-instr-python/tree/master/ddtrace/contrib/tornado)
[SignalFx](https://github.com/signalfx/signalfx-python-tracing/tree/master/signalfx_tracing/libraries/tornado_)

**Comment by codeboten** [comment]
Closing in favour of https://github.com/open-telemetry/opentelemetry-python/issues/627
