### ISSUE TITLE
Nominate @shalevr for contrib approvers

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1615]
@shalevr has been active in the contrib repo contributions and reviews. They have got 14 PRs merged in total https://github.com/open-telemetry/opentelemetry-python-contrib/pulls?q=is%3Apr+author%3Ashalevr+is%3Amerged. They have volunteered themselves to be the component owner of 3 instrumentations https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/.github/component_owners.yml#L41-L48. They have expressed interested in taking on the contrib approver responsibilities. 

Some of our current approvers have been inactive for over months and don't actively engage with the project. I would like to appreciate @shalevr's contributions on behalf of the maintainer's team and encourage them to keep doing it. 

cc // @open-telemetry/opentelemetry-python-contrib-maintainers

**Comment by ocelotl** [comment]
Sounds great! I approve 😎✌️

**Comment by lzchen** [comment]
I approve.

**Comment by shalevr** [comment]
Thank you for the opportunity
I accept the nomination, and I am looking forward to contributing more 😄
