### ISSUE TITLE
Flask Instrumentation : traceparent header not propagating

### ISSUE THREAD

**Issue by CeeBeeCee** [open-telemetry/opentelemetry-python-contrib#162]
I have a Flask app instrumented with opentelemetry-instrumentation-flask==0.13b0 using the default Trace Context propagation.  When it receives a request with a traceparent header as you can see in the curl command below (copied from a browser trace instrumented with opentelemetry-js), I am expecting the resulting trace from the Flask app to have the browser trace id as the parent. But the parent id is blank and the browser and Flask traces are getting disjoined/orphaned. Can someone please tell me if this a defect or am I missing a configuration?

**Request**
curl 'http://127.0.0.1:5000/api/graphql' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: http://localhost:8080/somepage' \
  -H 'DNT: 1' \
  **-H 'traceparent: 00-a9c3b99a95cc045e573e163c3ac80a77-d99d251a8caecd06-01' \**
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.70' \
  -H 'Content-Type: application/json'

**Trace Generated**

   "name":"graphql",
   "context":{
      **"trace_id":"0xe38556c630a25daafab10524bab79d43",**
      "span_id":"0x2eeb581ee82ec68d",
      "trace_state":"{}"
   },
   "kind":"SpanKind.SERVER",
   **"parent_id":null,**
   "start_time":"2020-10-08T21:05:00.359514Z",
   "end_time":"2020-10-08T21:05:03.863810Z",
   "status":{
   }

Code snippet :

`from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.trace import SpanKind

from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import (
    BatchExportSpanProcessor,
    ConsoleSpanExporter,
    SimpleExportSpanProcessor
)

from opentelemetry.exporter.otlp.trace_exporter import OTLPSpanExporter

from opentelemetry.instrumentation.wsgi import OpenTelemetryMiddleware
from opentelemetry.instrumentation.flask import FlaskInstrumentor
trace.set_tracer_provider(TracerProvider(resource=resource))
FlaskInstrumentor().instrument_app(app)
`

**Comment by lonewolf3739** [comment]
@CeeBeeCee I was unable to replicate this issue. Here are the steps I tried to reproduce this. 

# Dependencies
```
aiocontextvars==0.2.2
click==7.1.2
contextvars==2.4
Flask==1.1.2
immutables==0.14
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
opentelemetry-api==0.13b0
opentelemetry-instrumentation==0.13b0
opentelemetry-instrumentation-flask==0.13b0
opentelemetry-instrumentation-wsgi==0.13b0
opentelemetry-sdk==0.13b0
pkg-resources==0.0.0
Werkzeug==1.0.1
wrapt==1.12.1
```

# Sample app code
```python
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    ConsoleSpanExporter,
    SimpleExportSpanProcessor,
)

from flask import Flask
from opentelemetry.instrumentation.flask import FlaskInstrumentor


trace.set_tracer_provider(TracerProvider())
trace.get_tracer_provider().add_span_processor(
    SimpleExportSpanProcessor(ConsoleSpanExporter())
)


app = Flask(__name__)

FlaskInstrumentor().instrument_app(app)

@app.route("/")
def hello():
    return "Hello!"

if __name__ == "__main__":
    app.run(debug=True)

```

# cURL request:
```curl
curl 'http://127.0.0.1:5000' \
    -H 'Accept: application/json, text/plain, /' \
    -H 'Referer: http://localhost:8080/somepage' \
    -H 'DNT: 1' \
    -H 'traceparent: 00-a9c3b99a95cc045e573e163c3ac80a77-d99d251a8caecd06-01' \
    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome85.0.4183.121 Safari/537.36 Edg/85.0.564.70' \
    -H 'Content-Type: application/json'
```

# Span recorded
```json

{
    "name": "hello",
    "context": {
        "trace_id": "0xa9c3b99a95cc045e573e163c3ac80a77",
        "span_id": "0xaba3f97ed89827cf",
        "trace_state": "{}"
    },
    "kind": "SpanKind.SERVER",
    "parent_id": "0xd99d251a8caecd06",
    "start_time": "2020-12-24T12:54:38.151321Z",
    "end_time": "2020-12-24T12:54:38.153032Z",
    "status": {
        "canonical_code": "OK"
    },
    "attributes": {
        "component": "http",
        "http.method": "GET",
        "http.server_name": "127.0.0.1",
        "http.scheme": "http",
        "host.port": 5000,
        "http.host": "127.0.0.1:5000",
        "http.target": "/",
        "net.peer.ip": "127.0.0.1",
        "http.user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome85.0.4183.121 Safari/537.36 Edg/85.0.564.70",
        "net.peer.port": 36834,
        "http.flavor": "1.1",
        "http.route": "/",
        "http.status_text": "OK",
        "http.status_code": 200
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "0.13b0"
    }
}
```
As you can see from the above span recorded it is clear that parent is set and is not null.

**Comment by CeeBeeCee** [comment]
@lonewolf3739 : Thanks for looking into this. This issue is fixed now. Turns out that the JS instrumentation was using B3 headers and Python was using OTLP headers. Once we removed the B3 propagation, it defaulted to W3C headers and we see parent-child traces.

**Comment by CeeBeeCee** [comment]
@lonewolf3739 : Thanks for looking into this. This issue is fixed now. Turns out that the JS instrumentation was using B3 headers and Python was using OTLP headers. Once we removed the B3 propagation, it defaulted to W3C headers and we see parent-child traces.
