### ISSUE TITLE
Add instrumentation for the kafka-python library

### ISSUE THREAD

**Issue by chgl** [open-telemetry/opentelemetry-python-contrib#164]
**Is your feature request related to a problem?**

There is currently no instrumentation support for the [kafka-python](https://github.com/dpkp/kafka-python) library.

**Describe the solution you'd like**

Add support for instrumenting the python-kafka library. The instrumentation support should inject the current trace context into the message headers when `KafkaProducer.send` is called and should set the current span if a consumed message contains appropriate headers.

**Describe alternatives you've considered**

Manually implementing the tracing support in each client, which looked something like this:

```python
 for msg in consumer:
    with tracer.start_as_current_span("consuming"):
        # ...
        with tracer.start_as_current_span("sending"):
            headers = {}
            propagators.inject(type(headers).__setitem__, headers)
            headers = [(k, v.encode()) for k, v in headers.items()]
            producer.send("msg", value=msg.value, key=None, headers=headers)
```

**Comment by cartermp** [comment]
Slightly confused, Can this issue be closed because the instrumentation library exists? https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-kafka-python

**Comment by srikanthccv** [comment]
I think this can be closed now.
