### ISSUE TITLE
Add More Detail to urllib Auto-Instrumentation Span Name

### ISSUE THREAD

**Issue by kennytrytek-wf** [open-telemetry/opentelemetry-python-contrib#1651]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
The span name for urllib auto-instrumented spans is non-descript, appearing as `HTTP {method_name}`. When viewing spans (for example, in New Relic), it looks like this:

![Screen Shot 2023-02-08 at 3 55 08 PM](https://user-images.githubusercontent.com/1466480/217660130-139e2a87-7e6e-4c96-8b37-f26f2e970fd7.png)

This makes it hard to understand at a glance what is going on with the application.

**Describe the solution you'd like**
I would like the URL to be included in the span name, so that the application flow is more easily understood. For example, three subsequent spans might look like:
```
HTTP GET https://some-website.com/
HTTP GET https://my-dads-basement.com/tools/
HTTP POST https://usps.com/to-santa
```

I would like to omit the query and fragment, since the purpose is to easily understand which host being contacted without having to inspect each span's details.

**Describe alternatives you've considered**
1. Only include the hostname:
```
HTTP GET some-website.com
HTTP GET my-dads-basement.com
HTTP POST usps.com
```
This idea seems insufficient to provide enough context to discern what is happening, particularly if the same site is hit several times consecutively.

**Additional context**
This feature could be hidden behind a feature flag / environment variable in order to not break existing usages.

**Comment by kennytrytek-wf** [comment]
A workaround might look like this:
```
class BatchSpanNameProcessor(BatchSpanProcessor):
    http_op_re = re.compile(r"^HTTP [A-Z]+$")

    def on_start(self, span: Span, parent_context: Optional[Context] = None) -> None:
        try:
            if self.http_op_re.match(span.name):
                url = span._attributes.get(SpanAttributes.HTTP_URL)
                if not url:
                    logging.info(f"No URL attribute for span: {span.name}")
                    return

                purl = parse_url(url)
                purl = Url(
                    scheme=purl.scheme,
                    auth=None,
                    host=purl.host,
                    port=purl.port,
                    path=purl.path,
                    query=None,
                    fragment=None,
                )
                span.update_name(f"{span.name} {purl}")
        except Exception as e:
            logging.warning("Exception in span name processor. " + str(e))
```

This is not recommended, due to the `_attributes` access circumventing the intent of the OpenTelemetry span implementation, but does get the job done for auto-instrumented HTTP requests.

**Comment by srikanthccv** [comment]
The `HTTP {method_name}` follows the semantic conventions spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name.

If you want to change the name please use request/response hooks instead https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-urllib/src/opentelemetry/instrumentation/urllib/__init__.py#L36-L57. 

```
def my_hook(span, r):
  span.set_name(...)
```

**Comment by kennytrytek-wf** [comment]
Aha, thanks for the pointer. I did not know about request/response hooks. That approach could work for `urllib` instrumentation, but still fails for `urllib3`. `urllib3` does not provide helpful information like the request path or HTTP method, so the span attributes remain the only way to get at it.
```
http_op_re = re.compile(r"^HTTP [A-Z]+$")

def request_hook(
    span: Span,
    conn: urllib3.connectionpool.HTTPConnectionPool,
    headers: Dict,
    body: Optional[str],
):
    try:
        if http_op_re.match(span.name):
            url = span._attributes.get(SpanAttributes.HTTP_URL)
            if not url:
                logging.info(f"No URL attribute for span: {span.name}")
                return

            purl = parse_url(url)
            purl = Url(
                scheme=purl.scheme,
                auth=None,
                host=purl.host,
                port=purl.port,
                path=purl.path,
                query=None,
                fragment=None,
            )
            span.update_name(f"{span.name} {purl}")
    except Exception as e:
        logger.warning("Exception in span name hook. " + str(e))
```

**Comment by kennytrytek-wf** [comment]
Regardless, `urllib3` is following the spec, although server spans _always_ assume there is no low-cardinality `http.route`.
>HTTP server span names SHOULD be {http.method} {http.route} if there is a (low-cardinality) http.route available. HTTP server span names SHOULD be {http.method} if there is no (low-cardinality) http.route available. HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the "route", and therefore HTTP client spans SHOULD use {http.method}. Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name

It would be convenient if there were some way to indicate that `http.route` is desired in the span name.

**Comment by srikanthccv** [comment]
I think instrumentation follows the spec conventions, and any customization can be done via hooks. I think this can be closed. Please re-open if I misunderstood something.
