### ISSUE TITLE
Spans are nonrecording when run with python vs flask

### ISSUE THREAD

**Issue by aschuhl** [open-telemetry/opentelemetry-python-contrib#1675]
**Describe your environment** 
Following along with the opentel guide: https://opentelemetry.io/docs/instrumentation/python/getting-started/ works as expected. 

There is a deeper section here: https://opentelemetry.io/docs/instrumentation/python/automatic/ which doesn't work when the app from the getting started is ran with python command instead of the flask command.

**Steps to reproduce**
Run the app with the flaskcommand: 
```
OTEL_SERVICE_NAME=your-service-name \ 
OTEL_TRACES_EXPORTER=console \
OTEL_METRICS_EXPORTER=console \
opentelemetry-instrument \
    flask run
```
will work with spans outputted to the console. Additionally I added a print statement on trace.get_current_span()t: 

```_Span(name="do_roll", context=SpanContext(trace_id=0x6ce8f0934cab943a9f1e5968c40a7662, span_id=0x0e5d092b44e6aafe, trace_flags=0x01, trace_state=[], is_remote=False))```

when running with python app.py:
```
OTEL_SERVICE_NAME=your-service-name \
OTEL_TRACES_EXPORTER=console \
OTEL_METRICS_EXPORTER=console \
opentelemetry-instrument \
    python app.py
```
No traces are exported to the console and the get_current_span returns:
```
NonRecordingSpan(SpanContext(trace_id=0x00000000000000000000000000000000, span_id=0x0000000000000000, trace_flags=0x00, trace_state=[], is_remote=False))
```

So my question is how to get open telemetry to start recording a span when it isn't run with the flask command?

**Comment by srikanthccv** [comment]
Please do not run the app in debug mode, which I believe gets disabled with `flask run` command. If you still face issues, please share a reproducible example.

**Comment by aschuhl** [comment]
@srikanthccv okay i made some changes and removed the debug mode and now it does seem to be working!

So one follow-up, is it possible to start recording spans without the `opentelemetry-instrument` command? 

So:
```
OTEL_SERVICE_NAME=your-service-name \ 
OTEL_TRACES_EXPORTER=console \
OTEL_METRICS_EXPORTER=console \
    python app.py
```

instead of:
```
OTEL_SERVICE_NAME=your-service-name \ 
OTEL_TRACES_EXPORTER=console \
OTEL_METRICS_EXPORTER=console \
opentelemetry-instrument \
    python app.py
```

and instrument somewhere inside of app.py?

**Comment by srikanthccv** [comment]
Look at the manual instrumentation if you don't want to use the `opentelemetry-instrument` https://opentelemetry.io/docs/instrumentation/python/manual/
