### ISSUE TITLE
Help needed: Is there a way to supply instrumentation kwargs when using auto instrumentation?

### ISSUE THREAD

**Issue by danw-mpl** [open-telemetry/opentelemetry-python-contrib#1687]
I'm using `opentelemetry-instrument`.

I want to be able to set a kwarg to enable Redis sanitisation: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1572

Is there any way to supply kwargs to `opentelemetry-instrument`?  Environment variables would be a huge bonus.

**Comment by srikanthccv** [comment]
Not possible currently. Feel free to send a PR for adding support with env `OTEL_PYTHON_INSTRUMENTATION_SANITIZE_REDIS`.

**Comment by danw-mpl** [comment]
No worries, just checking!

**Comment by iTaybb** [comment]
I'm thinking about writing some generic solution for that.
So OTEL_PYTHON_{INSTRUMENT}_{ARG} will be passed automatically.
That way we won't have to implement ENV solution for each and each argument.

For example, `OTEL_PYTHON_PYMONGO_CAPTURE_STATEMENT=true` will instrument the pymongo instrumentation with `{'capture_statement': True}`.

@srikanthccv What do you say? Should I open a PR for that?

**Comment by srikanthccv** [comment]
It may work sometimes, but I think any attempt at a generic solution will likely fail when the args are diverse and non-trivial. A configuration schema is in progress to solve this kind of problem: https://github.com/open-telemetry/opentelemetry-configuration.
