### ISSUE TITLE
Add instrumentor for Psycopg2

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#17]
Add instrumentor for Psycopg2. Below are existing instrumentor implementations:

[DataDog](https://github.com/open-telemetry/opentelemetry-auto-instr-python/tree/master/ddtrace/contrib/psycopg)
[SignalFx](https://github.com/signalfx/signalfx-python-tracing/tree/master/signalfx_tracing/libraries/psycopg2_)

**Comment by codeboten** [comment]
closing in favour of https://github.com/open-telemetry/opentelemetry-python/issues/633
