### ISSUE TITLE
Enable documentation for Instrumentor classes

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [open-telemetry/opentelemetry-python-contrib#170]
Each integration should implement the `_instrument` and `_uninstrument` methods according to the `BaseInstrumentor` interface. Those methods are private and are not included in the documentation with the current configuration: https://opentelemetry-python.readthedocs.io/en/latest/ext/flask/flask.html#api.

We could enable them by using `:private-members:`, but probably it's too much and will include documentation of members we don't want to, another issue is that the documented name would include the underscore, and we want the user to call the method without it on the `BaseInstrumentor` class. Also, we don't have a way to document the parameters that those methods could take as they are declared as `**kwargs`.

**Comment by codeboten** [comment]
This is done now, docs live here: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/base/instrumentor.html
