### ISSUE TITLE
Support psycopg3

### ISSUE THREAD

**Issue by phillipuniverse** [open-telemetry/opentelemetry-python-contrib#1751]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

The existing Psycopg2 instrumentation works great. It's likely that we would be able to reuse most of that instrumentation code and refactor some concepts to share between the instrumentation.

It might be a bit complicated though because the artifact coordinates have changed from [psycopg2](https://pypi.org/project/psycopg2/) to [psycopg](https://pypi.org/project/psycopg/) with a version 3.x.

**Describe alternatives you've considered**

N/A

**Additional context**

Django 4.2 [now supports Psycopg3](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support)

**Comment by judahrand** [comment]
Is there any timeline for when a release with this instrumentation package will be released?
