### ISSUE TITLE
Make requests span attributes available to samplers for ASGI instrumentation

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1752]
Could we add an additional issue for [opentelemetry-instrumentation-asgi](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi)? I'd be happy to take that one.

_Originally posted by @tammy-baylis-swi in https://github.com/open-telemetry/opentelemetry-python-contrib/issues/936#issuecomment-1506113205_

**Comment by srikanthccv** [comment]
Please leave a comment so that I can assign this to you

**Comment by tammy-baylis-swi** [comment]
I'd like to take this one.
