### ISSUE TITLE
Remove `http.status_code` attribute from the `http.server.active_requests` metric

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1754]
Spec ref https://github.com/open-telemetry/opentelemetry-specification/pull/3366

**Comment by shalevr** [comment]
I Checked all the metrics instrumentation, and there is no http.server.active_requests metrics with http.status_code attribute.
It may be because the attribute was defined as Conditionally Required and not Required.
