### ISSUE TITLE
Update HTTP server/client instrumentation span names

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1757]
Ref: https://github.com/open-telemetry/opentelemetry-specification/pull/3165

HTTP Server

   - {http.route} to {http.method} {http.route} (when route is available)
   - HTTP {http.method} to {http.method} (when route is not available)

HTTP Client

   - HTTP {http.method} to {http.method}

**Comment by macieyng** [comment]
Hi 👋 I would love to work on that issue.

**Comment by macieyng** [comment]
I've wrote down the instrumentations that I think should be updated. @srikanthccv does it cover the proper scope?

SERVERS
- [ ] asgi
- [ ] aws-lambda
- [ ] django
- [ ] falcon
- [ ] flask
- [ ] pyramid
- [ ] tornado
- [ ] wsgi

CLIENTS
- [ ] aiohttp
- [ ] botocore
- [ ] httpx
- [ ] requests
- [ ] tornado
- [ ] urllib
- [ ] urllib3

**Comment by srikanthccv** [comment]
Yes, this sounds good to me.

**Comment by srikanthccv** [comment]
Yes, I think we should try to remain spec compliant. 

>But we could add django specific attribute (django.func_name and django.view_name)

 I don't have a strong opinion on this because it's specific to Django. Maybe we could use some known semantic convention to represent it.

**Comment by macieyng** [comment]
Okay, so I've found `code.function` and `code.namespace` that could be used in case of django view. The description does seem to fit in this case https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py#L518-L526

I would make that another issue though coz it's kind of a feature and does fit the current issue.

**Comment by cruisehall** [comment]
> I wrote down instrumentations that I think should be updated. 
@macieyng I think `fastapi` might need to be added to this list. It turns out that the `fastapi` instrumentor is building the span name itself by hooking into `asgi`'s `default_span_details` arg ([source](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/135280e5392534883e223035dc8b25c74dbc13e9/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L230)):
```py
class FastAPIInstrumentor(BaseInstrumentor):
  # ...
  @staticmethod
  def instrument_app(
    # ...
  ): 
    # ...
            app.add_middleware(
                OpenTelemetryMiddleware,
                excluded_urls=excluded_urls,
                default_span_details=_get_route_details,
                server_request_hook=server_request_hook,
                client_request_hook=client_request_hook,
                client_response_hook=client_response_hook,
                tracer_provider=tracer_provider,
                meter=meter,
            )
```
where `_get_route_details` builds a  span name using the `http.route`:
```py
def _get_route_details(scope):
    # ...
    app = scope["app"]
    route = None
    for starlette_route in app.routes:
        match, _ = starlette_route.matches(scope)
        if match == Match.FULL:
            route = starlette_route.path
            break
        if match == Match.PARTIAL:
            route = starlette_route.path
    # method only exists for http, if websocket
    # leave it blank.
    span_name = route or scope.get("method", "")
    attributes = {}
    if route:
        attributes[SpanAttributes.HTTP_ROUTE] = route
    return span_name, attributes
```
