### ISSUE TITLE
Error in urllib3 instrumentation example in instrumentation documentation

### ISSUE THREAD

**Issue by JM-ET** [open-telemetry/opentelemetry-python-contrib#1767]
**Describe your environment** 
https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/urllib3/urllib3.html
section: Request/Response hooks
Contains an error in example which causes pylint 
no-value-for-parameter (self)

**Steps to reproduce**
Current example on this page:
URLLib3Instrumentor.instrument(
    request_hook=request_hook, response_hook=response_hook)
)

**What is the expected behaviour?**
Works and runs successfully

**What is the actual behaviour?**
pylint - no-value-for-parameter (self)
And fails to run if disable lint check

**Correction**
Need to create an instance of URLLib3Instrumentor - missing () after class name

URLLib3Instrumentor().instrument(
    request_hook=request_hook, response_hook=response_hook)
)

example under section: Usage is correct, just not this example.

**Comment by srikanthccv** [comment]
Thanks for the report. Feel free to send a pull request.

**Comment by yashaswi2000** [comment]
can i pick this issue up, if this is not already being worked on. thanks!

**Comment by JM-ET** [comment]
Hello.
Sure; I can/could not determine the minimum acceptable level of
validation/testing required to accompany the change in a PR; admittedly a
very small change.
Kind regards
John
