### ISSUE TITLE
Support new stable http semantic conventions for http instrumentations - transition plan

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#1768]
Now that the community has decided to adopt ECS [conventions](https://github.com/open-telemetry/semantic-conventions/issues/1012), there is a push for stability for http semantic conventions. Part of this eventual work for languages is the eventual transition for instrumentations to update to the stable semantic conventions (which contain several breaking changes). This [issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3362) discusses the process of how languages will transition their instrumentations. The associated [PR](https://github.com/open-telemetry/opentelemetry-specification/pull/3404) proposes a plan to do so, including bumping instrumentations to major versions. This poses a couple of problems with how we currently version our packages:

1. We release packages in lockstep so these need to be decoupled if we want to update instrumentations separately
2. All instrumentations pin a version of the semantic conventions package -> how to support multiple semantic conventions
3. This only applies to http semantic conventions so we must ensure a clear path forward that doesn't affect transitioning other types of instrumentations.

Opening this issue to discuss how we can tackle this transition and whether we want to chime in to the community if this is not feasible.

**Comment by tammy-baylis-swi** [comment]
Hi there! I'd love to stay in the loop and work on the actual transition if/when the time comes.

So far I've been catching up on related issues. In May, a PR was merged outlining a transition helper variable, `OTEL_SEMCONV_STABILITY_OPT_IN`: https://github.com/open-telemetry/opentelemetry-specification/pull/3443 Setting `OTEL_SEMCONV_STABILITY_OPT_IN=http/dup` before the breaking major version release would "emit both the old and the stable HTTP and networking attributes". This might help with point 2 about supporting multiple semantic conventions.

**Comment by lzchen** [comment]
As discussed in the Python Sig 7/13

We will NOT be implementing the transition plan as defined [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3443). Instead, we will be sticking with our current instrumentation releases (bumping minor versions as appropriate) until we are ready to make a stable release since all of our instrumentations are not yet stable. As for updating to the new semantic conventions, we will be updating to the frozen version v1.21 [this pr] (https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1746) so as to only make a single breaking change. This will be followed by a MINOR version release as usual. Our message to users is that this will be a significant breaking change and we will assist them as needed when issues arise if they want to upgrade.

**Comment by aabmass** [comment]
Should https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1759 have been part of this effort? I think we should discuss in the SIG next week as it was already released.

**Comment by lzchen** [comment]
Created a [project board](https://github.com/orgs/open-telemetry/projects/66) to track this effort.

**Comment by lzchen** [comment]
[This](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1768#issuecomment-1634596141) message is outdated and the TC has advised the Python SIG to implement the [transition plan](https://github.com/open-telemetry/opentelemetry-specification/pull/3443). This issue will be used to track work related to that.

**Comment by lzchen** [comment]
For breaking changes that are [conflicting](https://github.com/open-telemetry/opentelemetry-specification/issues/3654#issuecomment-1676461568), the new semantic conventions will take priority. The only changes that should be affected by the migration plan are attribute related changes.

**Comment by lzchen** [comment]
Superseded by https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1986
