### ISSUE TITLE
make flask request attributes avaiable for sampler

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1779]
Hi again, could we add another issue for [opentelemetry-instrumentation-flask](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask)? I'd like to take that one too. The change is probably similar to the [recent Django update](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1730/files).

_Originally posted by @tammy-baylis-swi in https://github.com/open-telemetry/opentelemetry-python-contrib/issues/936#issuecomment-1530342636_

**Comment by srikanthccv** [comment]
Please leave a comment so that I can assign it to you.

**Comment by tammy-baylis-swi** [comment]
Thanks @srikanthccv ! I'd like to take this one.
