### ISSUE TITLE
Error importing opentelemetry-instrumentation-elasticsearch

### ISSUE THREAD

**Issue by JCMorente94** [open-telemetry/opentelemetry-python-contrib#1809]
Python version 3.10.6

opentelemetry-api==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-elasticsearch==0.38b0

elastic-transport==8.4.0
elasticsearch==8.7.0

**Steps to reproduce**
I just pip install elasticsearch[async] and opentelemetry-instrumentation-elasticsearch
when import them

```
import elasticsearch
from opentelemetry.instrumentation.elasticsearch import ElasticsearchInstrumentor

ElasticsearchInstrumentor().instrument()

es = elasticsearch.Elasticsearch()
```

I get the following error

`AttributeError: module 'elasticsearch' has no attribute 'Transport'`

**Comment by tammy-baylis-swi** [comment]
I'd like to take this issue.
