### ISSUE TITLE
Test case fails in Pypy

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#1839]
The test case [`test_urllib3_ip_support.py::TestURLLib3InstrumentorWithRealSocket::test_basic_http_success_using_connection_pool`](https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/5062916059/jobs/9088961227#step:6:3832) fails frequently when ran with PyPy, skip this run.

**Comment by srikanthccv** [comment]
See https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1826

**Comment by ocelotl** [comment]
Thanks, @srikanthccv, fixed by #1826, clsoing.
