### ISSUE TITLE
Propagate the B3-TraceId to a Celery task

### ISSUE THREAD

**Issue by felipebmendes** [open-telemetry/opentelemetry-python-contrib#1882]
### Describe your environment

Python 3.10
Libraries versions:
```
celery==5.3.1
fastapi==0.100.0
redis==4.6.0
uvicorn==0.22.0
opentelemetry-api==1.18.0
opentelemetry-sdk==1.18.0
opentelemetry-instrumentation==0.39b0
opentelemetry-exporter-otlp==1.18.0
opentelemetry-distro==0.39b0
opentelemetry-instrumentation-celery==0.39b0
opentelemetry-instrumentation-fastapi==0.39b0
opentelemetry-propagator-b3==1.18.0
opentelemetry-instrumentation-logging==0.39b0
```

### Steps to reproduce
Repository with a reproducible scenario:
https://github.com/felipebmendes/opentelemetry-celery-example

Running the containers in the docker-compose file, and then sending a request to the endpoint `http://localhost:8000/current_datetime` with  `X-B3-TraceId` and `X-B3-SpanId` headers:

```
docker-compose build

docker-compose up

curl -H "Accept: application/json" -H "Content-Type: application/json" -H "X-B3-TraceId: ebbbbc3573b75f01a465e445f295f648" -H "X-B3-SpanId: 23c7a7c7d462186c" -X GET http://localhost:8000/current_datetime

```

### What is the expected behavior?
How can I propagate the context from the controller to a Celery task?
I wish the logs from both the server and worker to present the same trace id, which was received in the request's headers.
I tried to do it using `@worker_process_init.connect` to instrument the Celery as mentioned in the documentation but it did not work as I expected.

### What is the actual behavior?
The server must return the current date time in ISO format in the request's response:
![Screenshot 2023-07-10 at 10 58 12](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/f372d0cb-ddd0-4e60-baa8-571f8c4240e7)

Checking the logs of the server and the worker, it's possible to see that the current trace in the server uses the trace id received in the request's headers:
![Screenshot 2023-07-10 at 10 57 24](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/dd978265-08a6-4204-b900-725a9211a2dc)

On the other hand, the Celery task cannot inherit this same trace id:
![Screenshot 2023-07-10 at 10 56 29](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/0aac146a-06c9-447c-bcef-ac97dd4a953b)

**Comment by hcavarsan** [comment]
It looks like the otel configuration isn't working as expected for a couple of reasons: 

1 - auto-instrumentation is set up in the app's startup command, as well as instrumentation in the code, which is causing duplicate instrumentations. 
2 - considering api and worker are two different applications, we need to configure otel for both. 

fixed this issue in this PR: <https://github.com/felipebmendes/opentelemetry-celery-example/pull/1/files>. 

could you please take a look and make sure it has been fixed?

**Comment by felipebmendes** [comment]
@hcavarsan yeah. Removing the duplicated instrumentation and configuring otel for both applications made it work as expected.

**Evidences:**

![Screenshot 2023-07-12 at 16 04 50](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/017e9de8-be27-4cca-9b3a-d302ef86fd41)

![Screenshot 2023-07-12 at 16 03 21](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/b819b345-2c8c-46d9-8ca3-479dab9e896c)

![Screenshot 2023-07-12 at 16 03 08](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/37848351/41c10231-9cb2-4276-9d1a-fc2e84b92b5c)


Thanks a lot.
