### ISSUE TITLE
Drop particular spans that are issued by opentelemetry-instrumentation-fastapi 

### ISSUE THREAD

**Issue by kamillle** [open-telemetry/opentelemetry-python-contrib#1910]
## **Is your feature request related to a problem?**
If so, provide a concise description of the problem.

I'd like to drop particular spans because my application uses WebSocket and opentelemetry-instrumentation-fastapi issues too many spans when Websocket request received or sent and the spans are cause of unnecessary charges.

## **Describe the solution you'd like**

Need an interface that allows to drop specified span.

```py
pattern = 'SOMETHING'
FastAPIInstrumentor.instrument_app(app, filter=pattern)
```

## **Describe alternatives you've considered**
Which alternative solutions or features have you considered?

## **Additional context**
Add any other context about the feature request here.

**Comment by kamillle** [comment]
Hi @macieyng !!

Below is an example.

One of our applications uses Websocket and receive many requests in per session that causes many spans are issued in per Trace ID. This capture is an example that shows around 700 spans were issued and most of spans were automatically created when WebSocket request is received or sent. It spends our money fast 💸 
<img width="704" alt="image" src="https://github.com/open-telemetry/opentelemetry-python-contrib/assets/32205171/ebcf98e3-2dde-4f27-b294-ac1f185c8bb6">

After posted this issue, I realized [OpenTelemetryMiddleware](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/9627f74a7360cafe7e6789d56b63798c0f29fe15/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L467) automatically creates these spans and I added own middleware inherited OpenTelemetryMiddleware to drop.

```py
from fastapi import FastAPI
from opentelemetry.instrumentation.asgi import OpenTelemetryMiddleware

class OtelMiddleware(OpenTelemetryMiddleware):
    def _get_otel_receive(self, _server_span_name, _scope, receive):
        return receive

    def _get_otel_send(self, _server_span, _server_span_name, _scope, send, _duration_attrs):
        @wraps(send)
        async def otel_send(message):
            await send(message)

        return otel_send

app = FastAPI()
app.add_middleware(OtelMiddleware, default_span_details=get_span_details)
```

I'd be happy to drop these spans by passing some arguments to `FastAPIInstrumentor.instrument_app`

**Comment by macieyng** [comment]
I kind of understand the issue. In my project we also have those send/receive spans that frankly are annoying and are eating up our budget. 

As of now, seems like what you did is a way to go. 

I think this is an issue that can be raised to the authors of specification - I think - because there is a good reason (money) for having those span disabled by default. If they don't agree then we can work out a solution for disabling this. 

@srikanthccv @shalevr @lzchen @ocelotl @jeremydvoss - what do you guys think about this issue?

**Comment by kamillle** [comment]
@srikanthccv @shalevr @lzchen @ocelotl @jeremydvoss Hello guys!! Could I get your opinion please?

**Comment by lzchen** [comment]
@kamillle 

If you want to exclude spans by route, @macieyng 's [suggestion](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1910#issuecomment-1680211939) of using `exclude_urls` is the only way to do so. If you want more granular control, your work around works as well. You can also probably use a custom span processor to check for websocket in the span name and drop it.

**Comment by macieyng** [comment]
If you would want to use custom processor here is something that may inspire you https://github.com/Azure/azure-sdk-for-python/issues/31292#issuecomment-1729462240. 
It ofc depends on how do you export spans.

**Comment by kamillle** [comment]
@

**Comment by kamillle** [comment]
Understand the situation, thank you for taking your time to make these responses!! @macieyng @lzchen
