### ISSUE TITLE
0.41b0 releases missing

### ISSUE THREAD

**Issue by davidhewitt** [open-telemetry/opentelemetry-python-contrib#1935]
I saw that `opentelemetry-sdk` 1.2.0 released yesterday with a new round of beta packages at version 0.41b0.

It looks like these beta versions were intended to be pushed here too but it looks like the release may have failed? https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/6076827813/job/16485481390

https://pypi.org/project/opentelemetry-instrumentation-asgi/ is still on 0.40b0

**Comment by txomon** [comment]
It seems like it was released now? https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.41b0

**Comment by davidhewitt** [comment]
Looks like it, yes 👍
