### ISSUE TITLE
0.35b0+ versions of opentelemetry-distro using 0.41b0 semantic-conventions

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-python-contrib#1938]
Related to #1935
All releases starting with 0.35b0 are using 0.41b0 of the opentelemetry-semantic-conventions package, this would be fine but it seems that the release for the instrumentation packages failed? And now there's a dependency conflict between the distro package and all instrumentation packages and they're now not usable. 

Why doesn't each version just use it's corresponding version of the dependency packages

**Comment by lzchen** [comment]
Should be fixed now.
