### ISSUE TITLE
Flask Instrumentation: skip traces for OPTIONS requests

### ISSUE THREAD

**Issue by tarmath** [open-telemetry/opentelemetry-python-contrib#199]
My Flask application is used through browsers, and therefore often gets a bunch of OPTIONS requests, generating traces that aren't really useful/needed in my opinion...

What would be a good way to skip these?

Perhaps, much like `OTEL_PYTHON_FLASK_EXCLUDED_URLS` is used to exclude certain urls, we could have `OTEL_PYTHON_FLASK_EXCLUDED_METHODS` which let us skip `OPTIONS` (and other) requests on the basis of their http method?

Would that be an acceptable feature to add? Or is there already another way to achieve this?

**Comment by lonewolf3739** [comment]
You could achieve it this way currently. The web browsers send these `OPTIONS` requests(preflight requests) when origin is not same. If you are using some reverse proxy server something like `nginx` you can modify `nginx.conf` to handle this.Then your application server doesn't receive these `OPTIONS` requests. 

This is not really specific to Flask. All web frameworks used for API development which are consumed by web clients from different origin will have this problem.
