### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by sakshi-1505** [open-telemetry/opentelemetry-python-contrib#1991]
The security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [x] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [ ] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [x] Repository security settings
  - [x] Security Policy ✅
  - [x] Security advisories ✅
  - [ ] Private vulnerability reporting ✅
  - [ ] Dependabot alerts ✅
  - [ ] Code scanning alerts ✅

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by sakshi-1505** [comment]
cc: @codeboten @lzchen

Please confirm if vulnerability reporting, dependabot alerts are configured for the repo as I don't have enough access to see those. I don't see us using any staticcode checker for Python, do you folks have any suggestion in mind for the same? I know we can use [Mypy](https://github.com/python/mypy) or [Pylint](https://github.com/pylint-dev/pylint).

**Comment by lzchen** [comment]
This repo follows the same security rules as the core repo so we can use the issue in the original repo to discuss.
