### ISSUE TITLE
Allow configuring header extraction via runtime parameters

### ISSUE THREAD

**Issue by adriangb** [open-telemetry/opentelemetry-python-contrib#2009]
Currently, web framework instrumentations only allow configuring header extraction via environment variables. I want to add the option to configure them via constructor parameters. I think the code should be quite straightforward but I want to check if this would be an acceptable change before making a  PR. Some background on why it wasn't implemented in the first place might also be helpful if it's something other than 'no one asked for it yet'.

**Comment by adriangb** [comment]
@lzchen @srikanthccv any thoughts? I don't see any reason why it couldn't be added as a runtime parameter as well.

**Comment by adriangb** [comment]
Thank you @ocelotl for merging the PR! Do you have any preferenece on how we pass these parameters to the Starlette and FastAPI middleware?

**Comment by srikanthccv** [comment]
Usually, we pass down the parameters as we do for the `*_hook` today. Do you have some other ideas?
