### ISSUE TITLE
Django Instrumentation fails to get settings

### ISSUE THREAD

**Issue by jeremydvoss** [open-telemetry/opentelemetry-python-contrib#2023]
**Describe your environment** Windows, Python 3.10

**Steps to reproduce LOCALLY**
- Clone https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart
Set up for local running

- Set `ALLOWED_HOSTS = ["127.0.0.1"]` in settings.py and production.py
- set `DEGUG = True` in settings.py and production.py
- set `SECRET_KEY=123abc` in .env.sample
- run `python manage.py runserver`
This should works. Next:

- Add `from opentelemetry.instrumentation.django import DjangoInstrumentor` and `DjangoInstrumentor().instrument()` to views.py
-  run `python veiws.py runserver` again
This does not work.

**What is the expected behavior?**
Should work the same but produce OTel telemetry

**What is the actual behavior?**
`CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.`
This is confusing to me. It's as if the django instrumentation erases the settings.

**Steps to reproduce ON APP SERVICE**
- Clone https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart
- Add `from opentelemetry.instrumentation.django import DjangoInstrumentor` and `DjangoInstrumentor().instrument()` to views.py
- Add Django instrumation to `requirements.txt`
- Deploy to App Service via vscode

**What is the expected behavior?**
Should work the same but produce OTel telemetry

**What is the actual behavior?**
`AttributeError: module 'django.conf.global_settings' has no attribute 'ROOT_URLCONF'`
Although it's a different setting, this still seems like the django instrumentation erases the settings.

**Additional context**
- This [issue](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1878) could be related
- This [file](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/3478831838ce54a972f7434ae6098f9bb28dc494/instrumentation/opentelemetry-instrumentation-django/tests/test_middleware.py#L104) is where ROOT_URLCONF is used in the django instrumentation

**Comment by jeremydvoss** [comment]
The instrumentation seems to work correctly if it is triggered in views.py instead of manage.py. However, this is still not acceptable because it means that auto-instrumentation does not work. So, we still need to figure out why the settings are being ignored.

**Comment by domino14** [comment]
doing something like this on the shell gives the same error: ``` opentelemetry-instrument --traces_exporter console --metrics_exporter none python manage.py runserver```

it thinks settings.DEBUG is false when it is not.

**Comment by jeremydvoss** [comment]
Issue was 2-fold: DJANGO_SETTINGS_MODULE needs to be set so that instrumentation code can see the settings. Plus, if you trigger sitecustomize via PYTHONPATH, you need to make sure that the app directory from which DJANGO_SETTINGS_MODULE gives a relative path is visible. You can do this by setting PYTHONPATH to include that working folder or adding it to sys.path at runtime.

@domino14 if DJANGO_SETTINGS_MODULE is set, then `opentelemetry-instrument` also works because it keeps the app folder as the working directory!

**Comment by sungmincs** [comment]
Thanks @jeremydvoss ! This helped me figure out why the app config is not properly loaded for my test app.

**Comment by golgor** [comment]
Just for anyone having the same issue. What @jeremydvoss mentions helped me solve my issue. Basically I added:
```yaml
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings
        - name: PYTHONPATH
          value: /app
```

It does not work if you try to set it using ConfigMap, for some reason.

Thanks @jeremydvoss!

**Comment by ikegentz** [comment]
Any other advice on this issue? Have been fighting it for a while, similar setup. I've tried both with `opentelemetry-instrument <my-run-command>`, which gives me the issue with `DEBUG`, as well as `DjangoInstrumentor().instrument()`, which just doesn't seem to do anything. I've tried setting `DJANGO_SETTINGS_MODULE` and `PYTHON_PATH` through various means (directly as env vars in my app's `deployment` manifest, directly in my Dockerfile, and even directly in my run command. It seems like `opentelemtry-instrument` clobbers all of my env vars.

FWIW, I'm using Poetry, so my run command looks like `poetry run opentelemetry-instrument python api/manage.py runserver 0.0.0.0:8000`

**Comment by golgor** [comment]
> Any other advice on this issue? Have been fighting it for a while, similar setup. I've tried both with `opentelemetry-instrument <my-run-command>`, which gives me the issue with `DEBUG`, as well as `DjangoInstrumentor().instrument()`, which just doesn't seem to do anything. I've tried setting `DJANGO_SETTINGS_MODULE` and `PYTHON_PATH` through various means (directly as env vars in my app's `deployment` manifest, directly in my Dockerfile, and even directly in my run command. It seems like `opentelemtry-instrument` clobbers all of my env vars.
> 
> FWIW, I'm using Poetry, so my run command looks like `poetry run opentelemetry-instrument python api/manage.py runserver 0.0.0.0:8000`
> 
> `opentelemtry-sdk` version is `1.30.0`

I am using the Python base image and then UV to set up a virtual environment with all my dependencies.

I noticed that I had to explicitly add environmental variables for both Django settings and the python path, otherwise it would try to execute things very weird.

Something like this in my container spec:

        env: 
         - name: DJANGO_SETTINGS_MODULE 
           value: config.settings 
         - name: PYTHONPATH 
           value: /app

**Comment by bradydean** [comment]
Same issue as @ikegentz, I've tried placing `DjangoInstrumentor().instrument()` in various places but it is not having any effect.

**Comment by Steve-MP** [comment]
I've found that following step 1, here https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html and setting `export DJANGO_SETTINGS_MODULE=my_app_name.settings` in the environment allowed the Django app to correctly load its config file when running under opentelemetry-instrument
