### ISSUE TITLE
ASGI instrumentation creates a 'type' attribute

### ISSUE THREAD

**Issue by adriangb** [open-telemetry/opentelemetry-python-contrib#2055]
See https://github.com/open-telemetry/opentelemetry-python-contrib/blob/7166de673fa9dd7abc178bec3103d4adebb05e0d/instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py#L681

This results in an attribute like `{'type': 'http.request.body'}`, which seems wrong. `type` is a _super_ generic key and I don't think leaking the details of the web framework spec (`http.request.body` is an ASGI specific string) is very helpful to users.

Can we get rid of this?

**Comment by samuelcolvin** [comment]
Any answer on this? I still see this apparently undocument `type` attribute everywhere and would love to understand why it's being included.

**Comment by bogdandrutu** [comment]
@open-telemetry/opentelemetry-python-contrib-approvers I think we should not use any generic word like "type" in our instrumentations.

**Comment by samuelcolvin** [comment]
Thanks @bogdandrutu, PR submitted #2145.
