### ISSUE TITLE
Does the FastAPI framework have a switch to control whether to enable tracing?

### ISSUE THREAD

**Issue by commonfurture** [open-telemetry/opentelemetry-python-contrib#2103]
Does the FastAPI framework have a switch like the Django framework, such as OTEL_PYTHON_DJANGO_INSTRUMENT, to control whether to enable distributed tracing?

**Comment by bourbonkk** [comment]
@commonfurture 

Hello. When doing auto instrumentation, you can disable certain instrumentors using the ['OTEL_PYTHON_DISABLED_INSTRUMENTATIONS' environment variable.](https://opentelemetry.io/docs/instrumentation/python/automatic/agent-config/#disabling-specific-instrumentations)

 For example:
`export OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=fastapi`

**Comment by commonfurture** [comment]
thank you very much
