### ISSUE TITLE
Should instrumentations have dependencies to the libraries they instrument?

### ISSUE THREAD

**Issue by mariojonke** [open-telemetry/opentelemetry-python-contrib#215]
As of now instrumentations directly reference the library they instrument. This might not actually be required since an application which wants to instrument a library with a certain instrumentation should already have the library installed, otherwise it wouldn't be able to use it. The instrumentation then would only require dependency for running tests (via `options.extras_require`)

Directly Including the dependency in the instrumentation might actually cause problems where the application and the instrumentation are installed separatly, e.g. in an AWS Lambda function a library could be deployed in one layer with version `x` and the instrumentation in another layer with the library in version `y`. Without the dependency the library would only be included in the lib layer but instrumentation would still work.

**Comment by lzchen** [comment]
Might be a stupid question but how would patching library specific methods work if the instrumentation doesn't take a dependency on the library? Like [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py#L75)?

**Comment by mariojonke** [comment]
Since in python everything is dynamic this shouldn't be a problem. E.g. having an application which uses `requests`. This application already must have a dependency to `requests` as otherwise it won't be able to use it. So if one wants to instrument this application with the `RequestsInstrumentor`, the instrumentation package does not need to have the dependency to requests since it is already fulfilled by the application. Using an instrumentor without the application having a dependency to the library which is being instrumented does not make much sense since the library won't be used by anyone.

**Comment by lzchen** [comment]
I don't like the idea of an instrumentation crashing on start up (even if this is not how it is "meant" to be used), it makes the software look "bad". I know it is obvious, but if we go this route, we have to enforce users to have these instrumented libraries installed or else the instrumentations will actually break. I would actually be fine with this if we can add checks to see if it is actually installed, and then patch the functions if so. This is contingent upon the use case listed above (with the different versions of instrumented libraries) to be an actual common problem.

**Comment by lonewolf3739** [comment]
Addressed in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/475
