### ISSUE TITLE
Add exemplar support to all WSGI based instrumentations

### ISSUE THREAD

**Issue by AlexisBRENON** [open-telemetry/opentelemetry-python-contrib#2158]
**Describe the solution you'd like**
I would like that recorded spans from the WSGI instrumentation (in particular the Flask one) also provide exemplars. Currently there is no link between the spans and the related metrics.

**Describe alternatives you've considered**
Up to now, I used custom histogram and custom spans (in my own request handler). But this is redundant with the more integrated instrumentation setup.

**Additional context**
According to [the OTel documentation](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#exemplar), any metric published inside an active span get linked as an exemplar. However, the latency of the handler seems [to be reported](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L596) after [the handler-span has ended](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py#L590). So no link is recorded between the span and the metric, while both are clearly related.

**Comment by aabmass** [comment]
Exemplars are not implemented in the Python SDK yet https://github.com/open-telemetry/opentelemetry-python/issues/2407

So the PR you sent won't have any effect right now, unfortunately.
