### ISSUE TITLE
Drop sklearn instrumentation

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#2176]
We should no longer publish the [sklearn](https://pypi.org/project/sklearn/) package sice it has been deprecated.

**Comment by dhpollack** [comment]
The sklearn package is just an alias of `scikit-learn` which is not deprecated.  Would you be open to having a scikit learn telemetry  package or was this dropped for another reason? @ocelotl

**Comment by lzchen** [comment]
@dhpollack 

Would be open to it if there is proper support for the instrumentation. We welcome contributors who are interested in creating one.
