### ISSUE TITLE
Remove pkg_resource and replace for importlib.metadata

### ISSUE THREAD

**Issue by Rodrigo-Novas** [open-telemetry/opentelemetry-python-contrib#2180]
**Describe your environment**

Docker environment
Image so: ubuntu:20.04
Python version: 3.9

Otel dependencies:

opentelemetry-api = "^1.14.0"
opentelemetry-semantic-conventions = "0.41b0"  # At the moment there are no releases without beta
opentelemetry-instrumentation-urllib3 = "0.41b0"  # At the moment there are no releases without beta
opentelemetry-instrumentation-httpx = "0.41b0" # At the moment there are no releases without beta

**Steps to reproduce**

Instrument any app and run it, it will throws a warning deprecation message about pkg_resource.

I created a CM of spans with something like this:

``` python
from opentelemetry import trace
@contextlib.contextmanager
def create_span(tracer: trace.Tracer) -> Generator:
    "Start the span as current span."
    name = "name"
    _kind = "kind"
    with tracer.start_as_current_span(
        name,
        kind=_kind,
        record_exception=False,
    ) as current_span:
        yield current_span
```

**What is the expected behavior?**

Otel doesnt throws a deprecationWarning

**What is the actual behavior?**

The output is a deprecation warning:

`DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html`

**Additional context**

[Use of pkg_resources is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html)

**Comment by Rodrigo-Novas** [comment]
I created a fix about this on https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2181

**Comment by theunkn0wn1** [comment]
FYI `pkg_resources` is deprecated AND REMOVED in modern python versions.
This package now depends on an undeclared dependency and is thus broken.

```
backend        |     from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
backend        |   File "/home/nonroot/.local/lib/python3.12/site-packages/opentelemetry/instrumentation/sqlalchemy/__init__.py", line 105, in <module>
backend        |     from opentelemetry.instrumentation.instrumentor import BaseInstrumentor
backend        |   File "/home/nonroot/.local/lib/python3.12/site-packages/opentelemetry/instrumentation/instrumentor.py", line 27, in <module>
backend        |     from opentelemetry.instrumentation.dependencies import (
backend        |   File "/home/nonroot/.local/lib/python3.12/site-packages/opentelemetry/instrumentation/dependencies.py", line 4, in <module>
backend        |     from pkg_resources import (
backend        | ModuleNotFoundError: No module named 'pkg_resources'

```
