### ISSUE TITLE
Remove [test] packages

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-python-contrib#2182]
We are using [`[test]` packages](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-flask/pyproject.toml#L41). This feature is not [intented to be used this way](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies), it is intended to be used to support _additional features_ of a package. Besides this, we are actually creating new packages that our users can install which I don't think is a good idea since it increases the amount of "things" we have to support.

There is [no standard way of defining the test dependencies or a package](https://discuss.python.org/t/development-dependencies-in-pyproject-toml/26149/24).

I suggest we use an extra file in every package to define the test dependencies for every package. This will also help with the additional problem that is the `tox.ini` file growing very large and hard to understand since all the package testing dependencies are there.

- [x] #2126
- [x] #2183
- [x] #2184
- [x] #2185
- [x] #2186
- [x] #2187
- [x] #2188
- [x] #2189
- [x] #2190
- [x] #2191
- [x] #2192
- [x] #2193
- [x] #2194
- [x] #2195
- [x] #2196
- [x] #2197
- [x] #2198
- [x] #2199
- [x] #2200
- [x] #2201
- [x] #2202
- [x] #2203
- [x] #2204
- [x] #2205
- [x] #2206
- [x] #2207
- [x] #2208
- [x] #2209
- [x] #2210
- [x] #2211
- [x] #2212
- [x] #2213
- [x] #2214
- [x] #2215
- [x] #2216
- [x] #2217
- [x] #2218
- [x] #2219
- [x] #2220
- [x] #2221
- [x] #2222
- [x] #2223
- [x] #2224
- [x] #2225
- [x] #2226
- [x] #2308
- [x] #2328

**Comment by federicobond** [comment]
We should remove the [test] package from psycopg instrumentation too.

**Comment by xrmx** [comment]
@ocelotl we can close this right?

**Comment by ocelotl** [comment]
Yes, closing.
