### ISSUE TITLE
Address DoS Vulnerability in opentelemetry-instrumentation-{instrumentation} Library

### ISSUE THREAD

**Issue by rahulhacker** [open-telemetry/opentelemetry-python-contrib#2350]
A DoS (Denial of Service) vulnerability has been identified in the opentelemetry-instrumentation-{instrumentation} library. This vulnerability arises due to uncontrolled resource consumption caused by unbound cardinality metrics.

**Link for reference**: https://github.com/open-telemetry/opentelemetry-python-contrib/security/advisories/GHSA-5rv5-6h4r-h22v

**Comment by rahulhacker** [comment]
@ocelotl Can you please help me on this??
As of now I am assigning this issue to myself

**Comment by rahulhacker** [comment]
@ocelotl : Can you please assign this to me??

**Comment by ocelotl** [comment]
[Closing](https://github.com/open-telemetry/opentelemetry-python-contrib/security/advisories/GHSA-5rv5-6h4r-h22v#advisory-comment-86304)
