### ISSUE TITLE
Can't install opentelemetry-instrumentation-psycopg

### ISSUE THREAD

**Issue by e-stepanov** [open-telemetry/opentelemetry-python-contrib#2365]
Can't install opentelemetry-instrumentation-psycopg because it's not in the PyPI.

**Steps to reproduce**
pip install opentelemetry-instrumentation-psycopg

**What is the expected behavior?**
opentelemetry-instrumentation-psycopg is installed

**What is the actual behavior?**
package is not found

**Comment by lzchen** [comment]
This instrumentation will be available in the next release.
