### ISSUE TITLE
Psycopg documentation is not up

### ISSUE THREAD

**Issue by Kludex** [open-telemetry/opentelemetry-python-contrib#2380]
Hi there!

The documentation link mentioned on the [Psycopg intrumentation page](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-psycopg) leads to a 404: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/psycopg/psycopg.html

**Comment by xrmx** [comment]
Looks like the build is broken https://readthedocs.org/projects/opentelemetry-python-contrib/builds/23234246/
