### ISSUE TITLE
Non-blocking IO configuration in the standard library

### ISSUE THREAD

**Issue by zcding4812** [open-telemetry/opentelemetry-python-contrib#2426]
When starting the program using the command `opentelemetry-instrument python program.py`, if `program.py` in the project needs to set `gevent.monkey.patch_ssl()`, it will conflict and trigger a `RecursionError`.   
Is it possible to add non-blocking IO configuration when starting opentelemetry-instrument?

**Comment by ddorian** [comment]
Can you do something similar like you start pytest with gevent `python -m gevent.monkey --module pytest` ?

**Comment by zcding4812** [comment]
Thanks, I'll try
