### ISSUE TITLE
Datadog exporter shouldn't parse span description to determine if there was an exception

### ISSUE THREAD

**Issue by alertedsnake** [open-telemetry/opentelemetry-python-contrib#244]
The Datadog exporter currently [parses the status description](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py#L252) to determine if an exception was raised, yet [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#record-exception) requires these to be recorded as events (and [the python code already does this](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L690-L715)), so the Datadog exporter should read this data from the event list instead of hoping the description is properly formatted.

The current code does say that [span events are not supported ](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py#L252), and while that would suggest that *reporting* events are not supported, we could certainly parse them for this data.

I'll probably tackle this, I'm already working on #154.  Also mentioned in #236, where I worked around the current behavior.

**Comment by owais** [comment]
//cc @majorgreys

**Comment by majorgreys** [comment]
Thanks for reporting this @alertedsnake! Your suggestion makes sense. If you end up tackling this, just give a heads up here and I'll check in before giving it a go myself.

**Comment by ericmustin** [comment]
@owais @majorgreys can you assign this to me? I'll try to address this and bring in line with spec compliane , sorry for the delay

**Comment by alertedsnake** [comment]
@ericmustin thanks!  I got bogged down trying to fix #262 that I haven't had a chance to look at this one.

**Comment by ericmustin** [comment]
@alertedsnake no worries, only one of us gets time during their day job to do this 🙃 . May ask for a review as my python is quite rusty, will ping on PR

**Comment by codeboten** [comment]
@ericmustin assigned!
