### ISSUE TITLE
opentelemetry-instrumentation-grpc depends on the SDK

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-python-contrib#2473]
opentelemetry-instrumentation-grpc takes a hard dependency on the opentelemetry-sdk package https://github.com/open-telemetry/opentelemetry-python-contrib/blob/3291f38e8dbde5d73ba2e0ba2a80fd3632faa1d7/instrumentation/opentelemetry-instrumentation-grpc/pyproject.toml#L29

**What is the expected behavior?**
Instrumentations should never depend directly on the SDK

**What is the actual behavior?**
There is a hard dep

**Additional context**
I haven't investigated why it's there. Hopefully it can be removed trivially.

**Comment by xrmx** [comment]
There's also systems-metrics:

```
instrumentation/opentelemetry-instrumentation-system-metrics/pyproject.toml:  "opentelemetry-sdk ~= 1.11",
```
