### ISSUE TITLE
opentelemetry-instrumentation-system-metrics depends on the SDK

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-python-contrib#2475]
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2493258af11df7f211567103635588f2813de7a3/instrumentation/opentelemetry-instrumentation-system-metrics/pyproject.toml#L29

**What is the expected behavior?**
Instrumentations should never depend directly on the SDK

**What is the actual behavior?**
There is a hard dep

**Additional context**
The only usage of the SDK in real code is or this util function https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2493258af11df7f211567103635588f2813de7a3/instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py#L94

This should be inlined or removed and the SDK dep removed

**Comment by emdneto** [comment]
Can work on this one
