### ISSUE TITLE
Error with the latest grpc version (v1.63.0)

### ISSUE THREAD

**Issue by VamsiKrishna1211** [open-telemetry/opentelemetry-python-contrib#2483]
**Describe your environment** 
When using the Otel grpc auto instrumentation, because of the implementation [here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/5116305f77bcd4c8ab18ef302a4351bb5b724c1e/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py#L263) in the `opentelemetry-python-contrib` the following error is thrown in the generated file `<proto_package>_pb2_grpc.py` file

`TypeError: unary_unary() got an unexpected keyword argument '_registered_method'`

**Steps to reproduce**
Install the latest (`v1.63.0`) grpc python version, generate the files. use them in a grpc client

**What is the expected behavior?**
There should be no error.

**What is the actual behavior?**
An error is thrown.

**Additional context**
Package versions used

```python
opentelemetry-instrumentation-grpc=0.44b0
grpcio=1.63.0

**Comment by ArpanSriv** [comment]
Facing the exact same issue.
