### ISSUE TITLE
opentelemetry-instrumentation-threading doesn't exist on pypi

### ISSUE THREAD

**Issue by ddorian** [open-telemetry/opentelemetry-python-contrib#2485]
**Describe your environment** 

According to docs https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-threading, it should exist, but it doesn't.

**Steps to reproduce**
`pip install opentelemetry-instrumentation-threading`

**What is the expected behavior?**
Exists.

**What is the actual behavior?**
```
❯ pip install opentelemetry-instrumentation-threading
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-threading (from versions: none)
ERROR: No matching distribution found for opentelemetry-instrumentation-threading
```

**Additional context**
Either the package should be on pypi or doc fixed.

**Comment by AmicoJoules** [comment]
It looks like it will be part of the 0.46b release since it was added very recently

**Comment by jackey90** [comment]
Encountering the same issue.

**Comment by aodj-kara** [comment]
Is there a timeline on the 0.46b release?

**Comment by DanielNoord** [comment]
Fixed: https://pypi.org/project/opentelemetry-instrumentation-threading/

😄 

@ddorian mind closing this issue to help the maintainers a little?
