### ISSUE TITLE
Add benchmarks to every type of package in `build` workflow

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-python-contrib#249]
In #243 we add performance tests for the AWS SDK Extension.

The AWS SDK extension falls under the category `sdkextension` of tests matched in the `build` workflow. For this reason, when the `jq` command looks through the entire repo after the workflow for `*-benchmark.json` files we are guaranteed to find at least ` file. This file is then given to the subsequent Github action to report on benchmarking results.

However, the `build` workflow also has `instrumentation` and `exporter` packages. These don't have performance tests yet so the `jq` command will fail. Even if we suppress the failure, the subsequent GitHub action will fail if no valid `output.json` file is created.

A temporary solution was to only run those 2 steps of the workflow `if: matrix.package == 'sdkextension'`. A more long-term solution will be to add benchmarks to `instrumentation` and `exporter`.

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/91bfc9afe5ae78bd203a78d0e301074059d54aef/.github/workflows/test.yml#L61-L62

and

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/91bfc9afe5ae78bd203a78d0e301074059d54aef/.github/workflows/test.yml#L68-L69

We know only these packages are required because as long as subsequent tests fit under these categories we won't have to keep adding `if` statements.

**Comment by NathanielRN** [comment]
We should probably keep this open until we have benchmarks for all relevant contrib packages (and a relevant way to force new packages to include them)!

@lzchen @codeboten

**Comment by lzchen** [comment]
@NathanielRN 
If you are interested in adding these benchmarks, feel free to create PRs for them and we'll be happy to review them :)
