### ISSUE TITLE
Fix new errors reported by pylint after upgrade.

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#251]
We upgraded pylint to latest version in this PR: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/248

New pylint reported new errors that we ended up silencing by adding them to the `disable=` section in pylintrc. All such rules are commented with ` # temp-pylint-upgrade`. We should go back to fix these issues and remove the ignore rules. 

If you want to work on this, feel free to create one PR per rule if that is easier.

**Comment by UrielMaD** [comment]
Hi @owais I'd like to take this issue

**Comment by owais** [comment]
Thanks @UrielMaD. It'd be really helpful. I'll ping you here once the PR is merged.
