### ISSUE TITLE
AWS Lambda event source key incorrect for SNS in instrumentation library.

### ISSUE THREAD

**Issue by mau-alex-ruiz** [open-telemetry/opentelemetry-python-contrib#2511]
**Description** 
This [line](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-aws-lambda/src/opentelemetry/instrumentation/aws_lambda/__init__.py#L311) is checking for the key `eventSource` which will never be satisfied for SNS. Per AWS [docs](https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html), the key is actually `EventSource`. The very simple fix would be to simply check for both `eventSource` and `EventSource`.

**What is the expected behavior?**
What did you expect to see?
`span_kind` for SNS event sources _should_ be set to `CONSUMER`

**What is the actual behavior?**
`span_kind` for SNS event sources are being set to `SERVER`

**Comment by Charlie-lizhihan** [comment]
Hi, Can I pick this one?

**Comment by emdneto** [comment]
@Charlie-lizhihan Please, feel free to open a PR!
