### ISSUE TITLE
Add a simple way to configure system-metrics from outside

### ISSUE THREAD

**Issue by xrmx** [open-telemetry/opentelemetry-python-contrib#2528]
**Is your feature request related to a problem?**

I would like to easily provide a different config for system metrics, i.e. to provide a subset of metrics, depending on an environment variable.

The instrumentation config can be passed to the instrumentation constructor.

Here's the config:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py#L99

In today SIG @aabmass suggested to take a look at [`BaseDistro.load_instrumentor()`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-instrumentation/src/opentelemetry/instrumentation/distro.py#L50) that may already do the trick

**Describe the solution you'd like**

No solution in mind

**Describe alternatives you've considered**

None

**Additional context**

**Comment by xrmx** [comment]
cc @jeremydvoss

**Comment by jeremydvoss** [comment]
load_instrumentor_kwargs seems to me like a method that can be entirely handled by the custom ElasticOpenTelemetryDistro. I think we should only change the sdk/api if it were preventing instrumentation kwarg configuration

**Comment by xrmx** [comment]
Would making it an internal helper ok? It would be useful as documentation at least.
