### ISSUE TITLE
`suppress_instrumentation` utils are not used consistently

### ISSUE THREAD

**Issue by alexmojaki** [open-telemetry/opentelemetry-python-contrib#2543]
Searching for `suppress_instrumentation` (https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib%20suppress_instrumentation&type=code) reveals places using the old plain string `"suppress_instrumentation"` context key, e.g:

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/f4f3042f85fa68565c4da3f96d437b15d78e1063/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L350

Since this is not how instrumentation is actually suppressed any more, this can lead to bugs.

There are also places checking/setting the key 'manually' instead of via the utility functions, which also seems error-prone.

Additionally, if it's allowed for a user to have different versions of `opentelemetry-instrumentation` and `opentelemetry-instrumentation-httpx` (or another specific library instrumentation package) installed, then the util functions `suppress_instrumentation` and `is_instrumentation_enabled` should also check the plain string key  `"suppress_instrumentation"` for backward compatibility.

**Comment by xrmx** [comment]
Nice catch, a PR would be great.
