### ISSUE TITLE
aiohttp vulnerable to Denial of Service when trying to parse malformed POST requests

### ISSUE THREAD

**Issue by Nanmozhi22** [open-telemetry/opentelemetry-python-contrib#2544]
Summary
An attacker can send a specially crafted POST (multipart/form-data) request. When the aiohttp server processes it, the server will enter an infinite loop and be unable to process any further requests.

Impact
An attacker can stop the application from serving requests after sending a single request.

**Comment by Nanmozhi22** [comment]
aiohttp version has been changed to 3.9.4 , Internal PR opened for the approval

**Comment by xrmx** [comment]
Fixed in 91a69d4c9
