### ISSUE TITLE
opentelemetry-instrumentation-tornado: Unhandled exception in _finish_tracing_callback

### ISSUE THREAD

**Issue by jgibo** [open-telemetry/opentelemetry-python-contrib#2555]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

No environmental factors - originally occurred in production (Linux VM, python 3.11), and reproduced locally on MacOS python3.11.

`future.result()` in [_finish_tracing_callback](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/client.py#L110-L114) throws an exception if the future result is an exception. This is expected behaviour for the future api, but based on how the code is structured, this appears to not be desired here.

The impact is the unhandled exception bubbles up to the asyncio runtime where it's logged. Which is undesired as this may be an error that the app normally expects and handles without logging.

**Steps to reproduce**
- Using tornado http client, make a request that causes the client to return a future containing an exception (response of 404, 500, etc...)

**What is the expected behavior?**
- _finish_tracing_callback gracefully handles a future with an exception result

**What is the actual behavior?**
- When _finish_tracing_callback reads a future with an exception result, it throws an exception that is ultimately unhandled by the lib, causing it to bubble up to the asyncio runtime.

**Comment by jgibo** [comment]
Attempted fix here https://github.com/open-telemetry/opentelemetry-python-contrib/compare/main...jgibo:opentelemetry-python-contrib:issue_2555 

Note: May move the fork to my company org instead of my personal account, will raise a PR once that is resolved.

**Comment by xrmx** [comment]
@jgibo thanks! please also add a test to avoid regressions.

**Comment by jgibo** [comment]
Tests added and [PR raised](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2563)
