### ISSUE TITLE
looks like process.open_file_descriptor.count is not implemented in python

### ISSUE THREAD

**Issue by nabheet** [open-telemetry/opentelemetry-python-contrib#2562]
**Is your feature request related to a problem?**

I do not see `process.open_file_descriptor.count` metric being collected in https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py. 

[This](https://opentelemetry.io/docs/specs/semconv/system/process-metrics/#metric-processopen_file_descriptorcount) says that it should be collected.

**Describe the solution you'd like**

`process.open_file_descriptor.count` metric should be collected.

**Describe alternatives you've considered**

N/A
**Additional context**

N/A

**Comment by arunk1988** [comment]
@nabheet I would like to take a look, Can you please assign this to me

**Comment by emdneto** [comment]
Hey @arunk1988 feel free to open a PR if you are making some progress

**Comment by arunk1988** [comment]
Hi @emdneto Sure...thanks

**Comment by arunk1988** [comment]
@shalevr Thanks for assigning. I have made some progress, will run the tests and proceed further

**Comment by arunk1988** [comment]
Hi @emdneto i had already completed the required change and tested as well, just need couple of days as it is going through internal approval process

**Comment by arunk1988** [comment]
![image](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/84958541/190b626b-3244-48a3-bd5c-2df29f32a978)

**Comment by arunk1988** [comment]
[](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2656)

**Comment by arunk1988** [comment]
Hi @emdneto, Just opened above PR
