### ISSUE TITLE
Use a newer Werkzeug (or alternative) for pyramid instrumentation tests

### ISSUE THREAD

**Issue by xrmx** [open-telemetry/opentelemetry-python-contrib#2604]
pyramid instrumentation tests are using an ancient version of Werkzeug, it would be nice to find a way to bump it to latest 3.0.x (or use something else) so we can avoid dependabot security warnings.

From instrumentation/opentelemetry-instrumentation-pyramid/tests/pyramid_base_test.py:

```
# opentelemetry-instrumentation-pyramid uses werkzeug==0.16.1 which has
# werkzeug.wrappers.BaseResponse. This is not the case for newer versions of
# werkzeug like the one lint uses.
from werkzeug.wrappers import BaseResponse  # pylint: disable=no-name-in-module
```

**Comment by arunk1988** [comment]
Hi @xrmx , looking into it..will open a PR shortly.
