### ISSUE TITLE
failed to run flask test locally

### ISSUE THREAD

**Issue by 123liuziming** [open-telemetry/opentelemetry-python-contrib#2613]
### Describe your environment

OS: (e.g, Ubuntu)
Python version: (e.g., Python 3.8.10)
Package version: (e.g., 0.46.0)

### What happened?

![image](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/32130965/19da4437-117b-494a-9c72-76d6f2285129)

### Steps to Reproduce

Go to your Contrib repo directory. cd ~/git/opentelemetry-python-contrib.
Create a virtual env in your Contrib repo directory. python3 -m venv my_test_venv.
Activate your virtual env. source my_test_venv/bin/activate.
Make sure you have tox installed. pip install tox.
Run tests for a package. (e.g. tox -e test-instrumentation-flask.)

### Expected Result

The rest run successfully

### Actual Result

test-instrumentation-flask: install_deps> python -I -m pip install pytest pytest-benchmark -c dev-requirements.txt
test-instrumentation-flask: commands_pre[0]> pip install 'opentelemetry-api@git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api'
Collecting opentelemetry-api@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api
  Cloning https://github.com/open-telemetry/opentelemetry-python.git (to revision main) to /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-codeb0bh/opentelemetry-api_4e06e609e9184336a42bdfe27f437eaa
  Running command git clone --filter=blob:none --quiet https://github.com/open-telemetry/opentelemetry-python.git /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-codeb0bh/opentelemetry-api_4e06e609e9184336a42bdfe27f437eaa
  Resolved https://github.com/open-telemetry/opentelemetry-python.git to commit 7b29953324b9b9dfedfec77705836c64eac05ad6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting deprecated>=1.2.6 (from opentelemetry-api@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting importlib-metadata<=7.1,>=6.0 (from opentelemetry-api@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api)
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting wrapt<2,>=1.10 (from deprecated>=1.2.6->opentelemetry-api@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api)
  Using cached wrapt-1.16.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (6.6 kB)
Collecting zipp>=0.5 (from importlib-metadata<=7.1,>=6.0->opentelemetry-api@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-api&subdirectory=opentelemetry-api)
  Using cached zipp-3.19.2-py3-none-any.whl.metadata (3.6 kB)
Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Using cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Using cached wrapt-1.16.0-cp312-cp312-macosx_10_9_x86_64.whl (37 kB)
Using cached zipp-3.19.2-py3-none-any.whl (9.0 kB)
Building wheels for collected packages: opentelemetry-api
  Building wheel for opentelemetry-api (pyproject.toml) ... done
  Created wheel for opentelemetry-api: filename=opentelemetry_api-1.26.0.dev0-py3-none-any.whl size=59975 sha256=360da1cee09c3d2349a02680c4b1caf724d6e8fd99a0e3aec42e2eb8153c9263
  Stored in directory: /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-ephem-wheel-cache-d5n9dhc7/wheels/e2/80/31/72409b670a50d751e9a17533aa70b43f99d84e1ea7cecd754a
Successfully built opentelemetry-api
Installing collected packages: zipp, wrapt, importlib-metadata, deprecated, opentelemetry-api
Successfully installed deprecated-1.2.14 importlib-metadata-7.1.0 opentelemetry-api-1.26.0.dev0 wrapt-1.16.0 zipp-3.19.2
test-instrumentation-flask: commands_pre[1]> pip install 'opentelemetry-semantic-conventions@git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions'
Collecting opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions
  Cloning https://github.com/open-telemetry/opentelemetry-python.git (to revision main) to /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-hy1fja10/opentelemetry-semantic-conventions_bc8d17baf91b440d9957d830b75bf942
  Running command git clone --filter=blob:none --quiet https://github.com/open-telemetry/opentelemetry-python.git /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-hy1fja10/opentelemetry-semantic-conventions_bc8d17baf91b440d9957d830b75bf942
  Resolved https://github.com/open-telemetry/opentelemetry-python.git to commit 7b29953324b9b9dfedfec77705836c64eac05ad6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: opentelemetry-api==1.26.0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions) (1.26.0.dev0)
Requirement already satisfied: deprecated>=1.2.6 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions) (1.2.14)
Requirement already satisfied: importlib-metadata<=7.1,>=6.0 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions) (7.1.0)
Requirement already satisfied: wrapt<2,>=1.10 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api==1.26.0.dev->opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions) (1.16.0)
Requirement already satisfied: zipp>=0.5 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api==1.26.0.dev->opentelemetry-semantic-conventions@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-semantic-conventions&subdirectory=opentelemetry-semantic-conventions) (3.19.2)
Building wheels for collected packages: opentelemetry-semantic-conventions
  Building wheel for opentelemetry-semantic-conventions (pyproject.toml) ... done
  Created wheel for opentelemetry-semantic-conventions: filename=opentelemetry_semantic_conventions-0.47b0.dev0-py3-none-any.whl size=134701 sha256=6beeb9674331b9ad8fbbbf09268a08a28048add593b7d804b7f01234e720e3df
  Stored in directory: /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-ephem-wheel-cache-u75js69b/wheels/72/54/3d/57bda7793b9b8332da7ea79b4bedeeebbbbbee6fa7c6b40af7
Successfully built opentelemetry-semantic-conventions
Installing collected packages: opentelemetry-semantic-conventions
Successfully installed opentelemetry-semantic-conventions-0.47b0.dev0
test-instrumentation-flask: commands_pre[2]> pip install 'opentelemetry-sdk@git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk'
Collecting opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk
  Cloning https://github.com/open-telemetry/opentelemetry-python.git (to revision main) to /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-ey6o_3mf/opentelemetry-sdk_d43e99d0e973425f97b2d9532c46ddc2
  Running command git clone --filter=blob:none --quiet https://github.com/open-telemetry/opentelemetry-python.git /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-ey6o_3mf/opentelemetry-sdk_d43e99d0e973425f97b2d9532c46ddc2
  Resolved https://github.com/open-telemetry/opentelemetry-python.git to commit 7b29953324b9b9dfedfec77705836c64eac05ad6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: opentelemetry-api==1.26.0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (1.26.0.dev0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.47b0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (0.47b0.dev0)
Collecting typing-extensions>=3.7.4 (from opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: deprecated>=1.2.6 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (1.2.14)
Requirement already satisfied: importlib-metadata<=7.1,>=6.0 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (7.1.0)
Requirement already satisfied: wrapt<2,>=1.10 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api==1.26.0.dev->opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (1.16.0)
Requirement already satisfied: zipp>=0.5 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api==1.26.0.dev->opentelemetry-sdk@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-sdk&subdirectory=opentelemetry-sdk) (3.19.2)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Building wheels for collected packages: opentelemetry-sdk
  Building wheel for opentelemetry-sdk (pyproject.toml) ... done
  Created wheel for opentelemetry-sdk: filename=opentelemetry_sdk-1.26.0.dev0-py3-none-any.whl size=107377 sha256=7f5037c6380a80bbaf0766bd5b2ed6350493f97d1c7dab5557bc2a5a0562f0ae
  Stored in directory: /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-ephem-wheel-cache-ps_7zjji/wheels/44/da/ea/735276bdc8d81e6b01c68a04af0f3cb7e97108dcbd87075852
Successfully built opentelemetry-sdk
Installing collected packages: typing-extensions, opentelemetry-sdk
Successfully installed opentelemetry-sdk-1.26.0.dev0 typing-extensions-4.12.2
test-instrumentation-flask: commands_pre[3]> pip install 'opentelemetry-test-utils@git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils'
Collecting opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils
  Cloning https://github.com/open-telemetry/opentelemetry-python.git (to revision main) to /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-889sqsp9/opentelemetry-test-utils_cd8003aee99e4587860def6b660b60b9
  Running command git clone --filter=blob:none --quiet https://github.com/open-telemetry/opentelemetry-python.git /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-install-889sqsp9/opentelemetry-test-utils_cd8003aee99e4587860def6b660b60b9
  Resolved https://github.com/open-telemetry/opentelemetry-python.git to commit 7b29953324b9b9dfedfec77705836c64eac05ad6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting asgiref~=3.0 (from opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils)
  Using cached asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: opentelemetry-api==1.26.0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (1.26.0.dev0)
Requirement already satisfied: opentelemetry-sdk==1.26.0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (1.26.0.dev0)
Requirement already satisfied: deprecated>=1.2.6 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (1.2.14)
Requirement already satisfied: importlib-metadata<=7.1,>=6.0 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-api==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (7.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.47b0.dev in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-sdk==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (0.47b0.dev0)
Requirement already satisfied: typing-extensions>=3.7.4 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from opentelemetry-sdk==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (4.12.2)
Requirement already satisfied: wrapt<2,>=1.10 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (1.16.0)
Requirement already satisfied: zipp>=0.5 in ./.tox/test-instrumentation-flask/lib/python3.12/site-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api==1.26.0.dev->opentelemetry-test-utils@ git+https://github.com/open-telemetry/opentelemetry-python.git@main#egg=opentelemetry-test-utils&subdirectory=tests/opentelemetry-test-utils) (3.19.2)
Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)
Building wheels for collected packages: opentelemetry-test-utils
  Building wheel for opentelemetry-test-utils (pyproject.toml) ... done
  Created wheel for opentelemetry-test-utils: filename=opentelemetry_test_utils-0.47b0.dev0-py3-none-any.whl size=14353 sha256=320ce548115897406794b4c900a002eb5296b73a2b67ed8108d205a398f96275
  Stored in directory: /private/var/folders/7c/xvg9tyv929d1mqbd44ygh8400000gp/T/pip-ephem-wheel-cache-si_7f3je/wheels/80/8f/98/b099669afe5bd79c33fc6368bd14f7bc1576293c12267cfa57
Successfully built opentelemetry-test-utils
Installing collected packages: asgiref, opentelemetry-test-utils
Successfully installed asgiref-3.8.1 opentelemetry-test-utils-0.47b0.dev0
test-instrumentation-flask: commands[0]> pytest /Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests
============================= test session starts ==============================
platform darwin -- Python 3.12.3, pytest-7.4.4, pluggy-1.5.0 -- /Users/liuxiaoming/opentelemetry-python-contrib/.tox/test-instrumentation-flask/bin/python
cachedir: .tox/test-instrumentation-flask/.pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/liuxiaoming/opentelemetry-python-contrib
configfile: pytest.ini
plugins: benchmark-4.0.0
collected 0 items / 6 errors

==================================== ERRORS ====================================
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/base_test.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/base_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/base_test.py:18: in <module>
    import flask
E   ModuleNotFoundError: No module named 'flask'
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/test_automatic.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/test_automatic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/test_automatic.py:15: in <module>
    import flask
E   ModuleNotFoundError: No module named 'flask'
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/test_copy_context.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/test_copy_context.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/test_copy_context.py:14: in <module>
    import flask
E   ModuleNotFoundError: No module named 'flask'
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/test_multithreading.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/test_multithreading.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/test_multithreading.py:15: in <module>
    import flask
E   ModuleNotFoundError: No module named 'flask'
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/test_programmatic.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/test_programmatic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/test_programmatic.py:19: in <module>
    from flask import Flask, request
E   ModuleNotFoundError: No module named 'flask'
_ ERROR collecting instrumentation/opentelemetry-instrumentation-flask/tests/test_sqlcommenter.py _
ImportError while importing test module '/Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests/test_sqlcommenter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
instrumentation/opentelemetry-instrumentation-flask/tests/test_sqlcommenter.py:15: in <module>
    import flask
E   ModuleNotFoundError: No module named 'flask'
!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 6 errors in 0.24s ===============================
test-instrumentation-flask: exit 2 (2.70 seconds) /Users/liuxiaoming/opentelemetry-python-contrib> pytest /Users/liuxiaoming/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-flask/tests pid=45832
  test-instrumentation-flask: FAIL code 2 (81.41=setup[5.06]+cmd[16.27,20.07,15.09,22.21,2.70] seconds)
  evaluation failed :( (81.76 seconds)

### Would you like to implement a fix?

None

**Comment by emdneto** [comment]
It's because you're not selecting which test-requirements.txt file to use. See https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tox.ini#L122 

```
    ; opentelemetry-instrumentation-flask
    ; The numbers at the end of the environment names
    ; below mean these dependencies are being used:
    ; 0: Flask ==2.1.3 Werkzeug <3.0.0
    ; 1: Flask ==2.2.0 Werkzeug <3.0.0
    ; 2: Flask >=3.0.0 Werkzeug >=3.0.0
    py3{8,9,10,11,12}-test-instrumentation-flask-{0,1}
    py3{8,9,10,11,12}-test-instrumentation-flask-{2}
```

If you use, for example,` tox -e py311-test-instrumentation-flask-0`, it should work. You can see all possible combinations using: `tox list | grep flask`

**Comment by 123liuziming** [comment]
> It's because you're not selecting which test-requirements.txt file to use. See https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tox.ini#L122
> 
> ```
>     ; opentelemetry-instrumentation-flask
>     ; The numbers at the end of the environment names
>     ; below mean these dependencies are being used:
>     ; 0: Flask ==2.1.3 Werkzeug <3.0.0
>     ; 1: Flask ==2.2.0 Werkzeug <3.0.0
>     ; 2: Flask >=3.0.0 Werkzeug >=3.0.0
>     py3{8,9,10,11,12}-test-instrumentation-flask-{0,1}
>     py3{8,9,10,11,12}-test-instrumentation-flask-{2}
> ```
> 
> If you use, for example,` tox -e py311-test-instrumentation-flask-0`, it should work. You can see all possible combinations using: `tox list | grep flask`

Thanks! May be we could polish the readme.
