### ISSUE TITLE
opentelemetry-instrumentation-fastapi: HTTP semantic convention stability migration

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/opentelemetry-python-contrib#2676]
### What problem do you want to solve?
 
HTTP semantic convention stability migration for `opentelemetry-instrumentation-fastapi`. Here is the [plan](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/migration-guide.md)

### Describe the solution you'd like
Implement the semconv opt-in feature for fastapi

### Additional Context

Part of this https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2453

### Would you like to implement a fix?

None

**Comment by xrmx** [comment]
Fixed by #2682
