### ISSUE TITLE
opentelemetry-instrumentation-jinja2: semantic convention stability migration

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/opentelemetry-python-contrib#2677]
### What problem do you want to solve?
 
semantic convention stability migration for `opentelemetry-instrumentation-jinja2`.

### Describe the solution you'd like
Implement the semconv opt-in feature for jinja2

### Additional Context

Part of this https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2453

### Would you like to implement a fix?

None

**Comment by knarfli** [comment]
Will work on this issue, please assign to me.

**Comment by the-chandru** [comment]
I am working on it.

**Comment by the-chandru** [comment]
changes are done, I will raise the PR soon.

**Comment by lzchen** [comment]
Closed due to https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2798#issuecomment-2291696860
