### ISSUE TITLE
opentelemetry-instrumentation-urllib: HTTP semantic convention stability migration

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/opentelemetry-python-contrib#2680]
### What problem do you want to solve?
 
HTTP semantic convention stability migration for `opentelemetry-instrumentation-urllib `. Here is the [plan](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/migration-guide.md)

### Describe the solution you'd like
Implement the semconv opt-in feature for urllib

### Additional Context

Part of this https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2453

### Would you like to implement a fix?

None

**Comment by FraserYu** [comment]
Could you please assign this issue to me?

**Comment by lzchen** [comment]
@the-chandru 

Oops sorry did not see your comment, I've submitted a draft PR already so hopefully you didn't get too deep into it.

**Comment by the-chandru** [comment]
Hi @lzchen  - that's fine :) I shall pick a different one.
