### ISSUE TITLE
Improve Jinja2 templating in test case

### ISSUE THREAD

**Issue by qiuge615** [open-telemetry/opentelemetry-python-contrib#2696]
### What problem do you want to solve?

Current open telemetry-instrumentation-jinja2 test case uses default value for autoescape. This can be improved.

### Describe the solution you'd like

Set proper value for autoescape for jinja2 templating.

### Would you like to implement a fix?

Yes

**Comment by shijiadong2022** [comment]
I will work on this one and submit a PR soon

**Comment by emdneto** [comment]
It looks like this is a duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2398

**Comment by qiuge615** [comment]
@emdneto Thanks for your help, close this issue.
