### ISSUE TITLE
Upgrade Django version in test requirements file

### ISSUE THREAD

**Issue by qiuge615** [open-telemetry/opentelemetry-python-contrib#2697]
### What problem do you want to solve?

Upgrade Django version to avoid potential issue in test requirements file.

### Describe the solution you'd like

Upgrade the Django version to higher version in test requirements file.

### Would you like to implement a fix?

Yes

**Comment by qiuge615** [comment]
I will create a PR to upgrade the version.

**Comment by xrmx** [comment]
This will be fixed by https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2700
