### ISSUE TITLE
opentelemetry-instrumentation-asgi: do not set `url.full` attribute for server spans

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/opentelemetry-python-contrib#2698]
### Describe your environment

instrumentation-asgi: 0.47b0.dev

### What happened?

asgi instrumentation is emitting `url.full` attribute in server spans

### Steps to Reproduce

Run any example of asgi instrumentation with new semconv opt-in enabled 

```python
import fastapi
import os
import logging
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider, sampling
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor,
    ConsoleSpanExporter,
)
# Specify "http", "http/dup" or ""
os.environ["OTEL_SEMCONV_STABILITY_OPT_IN"] = "http"
logging.basicConfig(level=logging.DEBUG)

provider = TracerProvider()
processor = BatchSpanProcessor(ConsoleSpanExporter())
provider.add_span_processor(processor)
trace.set_tracer_provider(provider)
tracer = trace.get_tracer(__name__)

app = fastapi.FastAPI()

@app.get("/foobar")
async def foobar():
    return {"message": "hello world"}

FastAPIInstrumentor.instrument_app(app)
```

### Expected Result

```json
"attributes": {
        "url.scheme": "http",
        "server.address": "127.0.0.1:8000",
        "server.port": 8000,
        "network.protocol.version": "1.1",
        "url.path": "/foobar",
        "http.request.method": "GET",
        "user_agent.original": "curl/7.68.0",
        "client.address": "127.0.0.1",
        "client.port": 45854,
        "http.route": "/foobar",
        "http.response.status_code": 200
    },
  ```

### Actual Result

Server span Attributes with `url.full` which isn't necessary for server span:
```json
"attributes": {
        "url.scheme": "http",
        "server.address": "127.0.0.1:8000",
        "server.port": 8000,
        "network.protocol.version": "1.1",
        "url.path": "/foobar",
        "url.full": "http://127.0.0.1:8000/foobar",
        "http.request.method": "GET",
        "user_agent.original": "curl/7.68.0",
        "client.address": "127.0.0.1",
        "client.port": 45854,
        "http.route": "/foobar",
        "http.response.status_code": 200
    },
```

### Additional context
Seems we are setting `http.url` (for old semconv) since always but isn't really necessary anymore

https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2682#issuecomment-2223277707

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.11.0/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions
### Would you like to implement a fix?

None

**Comment by shijiadong2022** [comment]
I'd like to work on this one and will submit a PR

**Comment by shijiadong2022** [comment]
@emdneto two questions on this issue
1, Is the expectation to remove http.url attribute for all libs? If so we can apply the change in _semconv.py for all libs.
2, Is this change only applied to new semconv? OR to not set http.url for both old and new semconv?

**Comment by lzchen** [comment]
@shijiadong2022 

Seems like we've always recorded `http.url` for old sem conv so this change would just be removing it for `url.full` for new semconv.

**Comment by emdneto** [comment]
Right. I would just pay attention to `http/dup` mode, according to the migration guide:
> http/dup - emit both the old and the stable HTTP and networking conventions, allowing for a phased rollout of the stable semantic conventions.

**Comment by emdneto** [comment]
@shijiadong2022 are you stil working on this?

**Comment by shijiadong2022** [comment]
I am working on it.

**Comment by shijiadong2022** [comment]
@emdneto when you get a chance can you review my PR? Thanks.
