### ISSUE TITLE
Should celery instrumentation comply with messaging semantic conventions?

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-python-contrib#271]
I'm not sure if Celery must comply with messaging semantic conventions.
But
From [messaging semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md):
- span name SHOULD be set to the message destination name and the operation. Celery violates it.
- required `messaging.system` attribute is not set
- `messaging.destination_kind` is not set

**Comment by lzchen** [comment]
Already being tracked [here](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/140).
