### ISSUE TITLE
Add support for `mysql-connector-python` v9

### ISSUE THREAD

**Issue by omikader** [open-telemetry/opentelemetry-python-contrib#2720]
### What problem do you want to solve?

The `mysql-connector-python` package had a [major version bump on July 1, 2024](https://pypi.org/project/mysql-connector-python/9.0.0/). However, the [`opentelemetry-instrumentation-mysql`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/e6c27e08007c4acf2a3fa9f903c52c4656b9ea62/instrumentation/opentelemetry-instrumentation-mysql/src/opentelemetry/instrumentation/mysql/package.py#L16) plugin only supports 8.x

### Describe the solution you'd like

It would be great if `opentelemetry-instrumentation-mysql` worked for `mysql-connector-python >= 8.0` vs `~= 8.0`

### Describe alternatives you've considered

It is worth noting that the 9.0.0 [changelog](https://dev.mysql.com/doc/relnotes/connector-python/en/news-9-0-0.html) for `mysql-connector-python` includes [opentelemetry support](https://dev.mysql.com/doc/connector-python/en/connector-python-opentelemetry.html), but I prefer to have the auto-instrumentation capabilities provided by this library as opposed to explicitly/manually instrumenting MySQL connections.

### Additional Context

I did a quick pass and I don't think their API had any breaking changes so I think it might be as easy as just relaxing the version constraints and trying it out. Happy to open a PR if it's actually that easy 😅 

### Would you like to implement a fix?

Yes

**Comment by xrmx** [comment]
@omikader please give it a try! You have to:
- update project.optional-dependencies in pyproject.toml
- update src/opentelemetry/instrumentation/mysql/package.py
- add a new version of test-requirements.txt using version 9 of the library and update tox.ini accordingly
- run tox -e generate
