### ISSUE TITLE
exporter-datadog: docstring does not match arguments

### ISSUE THREAD

**Issue by alertedsnake** [open-telemetry/opentelemetry-python-contrib#274]
The docstring here:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py#L68
says it expects a list, but what it really expects is a string containing a comma-separated list of tags.

Do I fix the docstring, do I change the code code to accept a real list ,or do I change the code to accept *either* a list or the current string?  I'm also working on #154 and would really prefer both objects accept the same parameters if possible.. but this is just odd, and IMHO not very pythonic.

What do we prefer for things like this?

(I'm happy to do the work, again, since I'm already working on related stuff)

**Comment by lzchen** [comment]
@alertedsnake 
I would simply change the docstring to reflect the actual code.
