### ISSUE TITLE
`http.server.duration` metric description is wrong

### ISSUE THREAD

**Issue by KyriosGN0** [open-telemetry/opentelemetry-python-contrib#2753]
### Describe your environment

OS: K8S
Python version: 3.11
Package version: 0.46b0

### What happened?

our Otel Collectors are dropping metrics caused due to a description in some metrics not being set correctly, this was fine in 0.45b0, it seems that it was reverted/overridden [here](https://github.com/open-telemetry/opentelemetry-python-contrib/compare/v0.45b0...v0.46b0#diff-2c109e76591442fd2a0e5ac717f0148877d9e99cbc76619e4876942c9c86543dR551)
as a result we see the errors like in this [issue](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2298)

### Steps to Reproduce

1. set up otel collectors in k8s
2. setup fastAPI apps with auto-instrumentation 

### Expected Result

no errors 

### Actual Result

metrics being dropped as result of mismatch in description 

### Would you like to implement a fix?

None

**Comment by StevenPenn** [comment]
I'll try to work on this.

**Comment by emdneto** [comment]
@KyriosGN0, are you facing the issue with the new version?

**Comment by StevenPenn** [comment]
I found the current description of "http.server.duration" and "http.server.request.duration" is not consistent with the "open telemetry.io". 
https://opentelemetry.io/docs/specs/semconv/non-normative/http-migration/#http-server-duration-metric
So, I'll create a PR soon to fix this issue.

**Comment by emdneto** [comment]
@StevenPenn, could you please be more clear about where it isn't consistent? Which instrumentation? We did recent changes in several instrumentation to make it compatible with new semantic conventions, so any suggestion is appreciated.

**Comment by StevenPenn** [comment]
Hi @emdneto, sorry for the late reply, the PR is still in compliance process.

**Comment by StevenPenn** [comment]
I found the "**http.server.duration**" is updated to "**http.server.request.duration**" according to the [https://opentelemetry.io/docs/specs/semconv/non-normative/http-migration/#http-server-duration-metric](url).

<img width="706" alt="Screenshot 2024-08-13 at 10 07 41" src="https://github.com/user-attachments/assets/449aa38b-498a-473b-8b5a-45e8594c2025">

But in our repo, the description of "**http.server.duration**" and "**http.server.request.duration**" is mixed.
Such as:
- The description of some "**http.server.duration**" is "**Duration of HTTP server requests.**" or "**measures the duration of the inbound HTTP request**". I think it should be "Measures the duration of inbound HTTP requests."
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-aiohttp-server/src/opentelemetry/instrumentation/aiohttp_server/__init__.py#L207C1-L211C6
- The description of some "**http.server.request.duration**" is "**measures the duration of the inbound HTTP request**". I think it should be "Duration of HTTP server requests."

**Comment by emdneto** [comment]
@StevenPenn Thanks, I noticed that. Let me know if you are open to working on this or someone else can take it over

**Comment by StevenPenn** [comment]
> @StevenPenn Thanks, I noticed that. Let me know if you are open to working on this or someone else can take it over

Sure, I am working on it and will create PR as soon as possible.
