### ISSUE TITLE
Firestore, Google Cloud Tasks, Snowflake Instrumentation

### ISSUE THREAD

**Issue by silviumarcu** [open-telemetry/opentelemetry-python-contrib#2806]
### What problem do you want to solve?

I could not find any out of the box instumentors for Firestore, GC Tasks or Snowflake.

### Describe the solution you'd like

I was planning to add instumentors for the libs mentioned above but I am not sure if it'll be of interest. Would you be happy with me submitting PRs for those?

### Would you like to implement a fix?

Yes

**Comment by zhihali** [comment]
I think to get the quicker response, join the weekly SIG is a better choice, discuss these with the maintainers directly. I'm also interest in those tools😄

**Comment by silviumarcu** [comment]
Thank you @lzchen, I will close this and jump on slack/SIG to continue.
