### ISSUE TITLE
Please upload all missing version for opentelemetry-instrumentation-aiohttp-server

### ISSUE THREAD

**Issue by LeoQuote** [open-telemetry/opentelemetry-python-contrib#2824]
### Describe your environment

OS: Not Relevant
Python version: Not Relevant
Package version: Not Relevant

### What happened?

previsously the issue https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2053 was resolved by pypi, they resolved the 518 gave the community the permission to upload packages, the latest package 0.47b0 was uploaded, but not for the older versions.

I suggest upload all previous version to support more versions

### Steps to Reproduce

pip install opentelemetry-distro==0.43b0 && opentelemetry-bootstrap -a install

### Expected Result

opentelemetry-instrumentation-aiohttp-server was installed 

### Actual Result

```
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-aiohttp-server==0.43b0 (from versions: 0.47b0.dev0, 0.47b0)
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.43b0

```

### Would you like to implement a fix?

No

**Comment by lzchen** [comment]
@LeoQuote 

I've gone ahead and released older versions of `opentelemetry-instrumentation-aiohttp-server` since it's creation. Hopefully it resolves your ask.

https://pypi.org/project/opentelemetry-instrumentation-aiohttp-server/#history
