### ISSUE TITLE
HTTPX: type mismatch in values passed to the request/response hooks

### ISSUE THREAD

**Issue by burritoatspoton** [open-telemetry/opentelemetry-python-contrib#2899]
### Describe your environment

OS: MacOS 14.5
Python version: 3.12.7
Package version: 0.48.b0

### What happened?

When instrumenting `httpx` clients e.g. via `HTTPXClientInstrumentor.instrument_client`, users can pass `request_hook` and `response_hook` callables which accept namedtuples `RequestInfo`/`ResponseInfo` ([type definitions](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/v0.48b0/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L235-L259)). These tuples contain a `header` field typed as `Optional[List[Tuple[bytes, bytes]]]`. However, at runtime this field seems to be copied verbatim from `request.headers`/`response.headers`, making it an instance of `httpx.Headers`. The same applies to a `url` field in `RequestInfo` (tuple of values vs `httpx.URL`). Should the typehints be updated?

### Steps to Reproduce

```python
def request_hook(span, request_info):
    print(f"{type(request_info.headers)=} {type(request_info.url)=}")

with httpx.Client() as client:
    HTTPXClientInstrumentor.instrument_client(client, request_hook=request_hook)
    client.get("https://example.com")
```

### Expected Result

```
type(request_info.headers)=<class 'list'> type(request_info.url)=<class 'tuple'>
```

### Actual Result

```
type(request_info.headers)=<class 'httpx.Headers'> type(request_info.url)=<class 'httpx.URL'>
```

### Would you like to implement a fix?

None

**Comment by Kludex** [comment]
I've created the PR above to handle this.
