### ISSUE TITLE
Update instrumentations usage examples

### ISSUE THREAD

**Issue by lonewolf3739** [open-telemetry/opentelemetry-python-contrib#292]

**Comment by lonewolf3739** [comment]
@lzchen I am thinking of updating examples with minimal working code using console exporter and pointing users to exporter section of docs if they have want to export traces elsewhere (could be zipkin or jaeger or something else), does that make sense? any concerns?

**Comment by lzchen** [comment]
@lonewolf3739 
I think the point of leaving the usages in the docstrings to be minimal was that we did not want to take a dependency on the SDK at all. I think example files would be more appropriate to have the minimal working code. Thoughts?

**Comment by lonewolf3739** [comment]
Yes, the idea was to make snippet examples fully functional so that they emit traces to console/backend. Referencing to working examples directory certainly helps and we don't have to repeat trace pipeline boilerplate in all the instrumentations.

**Comment by lzchen** [comment]
Cool, closing this in favor of the other issue.
