### ISSUE TITLE
HTTPXClientInstrumentor.instrument_client is no longer a staticmethod, and documentation is out of date

### ISSUE THREAD

**Issue by robotadam** [open-telemetry/opentelemetry-python-contrib#2998]
### Describe your environment

OS: Debian bookworm, docker
Python version: 3.11
Package version: 0.49

### What happened?

In PR #2909 `HTTPXClientInstrumentor.instrument_client` was changed from a `staticmethod` to an instance method. This breaks existing usage, as described in the docs:
```python
import httpx
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor

url = "https://some.url/get"

with httpx.Client(transport=telemetry_transport) as client:
    HTTPXClientInstrumentor.instrument_client(client)
    response = client.get(url)
```

Since this change, the code must use
```python
with httpx.Client(transport=telemetry_transport) as client:
    HTTPXClientInstrumentor().instrument_client(client)
```

### Steps to Reproduce

```python
import httpx
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor

url = "http://example.com/get"

with httpx.Client() as client:
    HTTPXClientInstrumentor.instrument_client(client)
    response = client.get(url)
```

### Expected Result

Expected that the client is instrumented with no errors.

### Actual Result

```
TypeError: HTTPXClientInstrumentor.instrument_client() missing 1 required positional argument: 'client'
```

### Additional context

This was called out as a breaking change in the [changelog](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/v0.49b0/CHANGELOG.md#breaking-changes), but without a description of what to change.

I'll also note that `uninstrument_client` is still a staticmethod, so there might be some confusion now that these are not symmetric.

### Would you like to implement a fix?

None

**Comment by xrmx** [comment]
Yeah, we didn't have a single test that used it as a static method so I missed it :sweat: 

If you look at the code I think it's easy to make it a staticmethod again because AFAICS it's using it only for calling another staticmethod of the same class.

**Comment by robotadam** [comment]
@xrmx Thanks for the quick look!
