### ISSUE TITLE
Warning Logs with response_format in opentelemetry-instrumentation-openai-v2

### ISSUE THREAD

**Issue by raptium** [open-telemetry/opentelemetry-python-contrib#3052]
When using opentelemetry-instrumentation-openai-v2, I receive the following warning when setting the response_format parameter as a dictionary:

```
WARNING:opentelemetry.attributes:Invalid type dict for attribute 'gen_ai.openai.request.response_format' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types\
```

The OpenAI Python Client and [API Reference](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) indicate that response_format can be a dictionary with a key "type" (values: "text", "json_object", "json_schema"). However, the [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/gen-ai.md#openai-attributes) specify that this attribute should be a plain string.

The current implementation attempts to log the entire dictionary, causing a type mismatch. The relevant code can be found 

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d330ab3dd055f7da69f273d2cf1074dd128dfd62/instrumentation-genai/opentelemetry-instrumentation-openai-v2/src/opentelemetry/instrumentation/openai_v2/utils.py#L205-L207

**Comment by codefromthecrypt** [comment]
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/3073
