### ISSUE TITLE
Update database driver instrumentor docs for instrument_connection

### ISSUE THREAD

**Issue by tammy-baylis-swi** [open-telemetry/opentelemetry-python-contrib#3089]
### What problem do you want to solve?

I would be helpful if existing database driver instrumentors got doc and docstring updates to better describe `instrument_connection` and how it should be used. Currently their `Usage` examples show how to use `instrument`, but not `instrument_connection`. Some of the docs do not have docstring at all for `instrument_connection`.

### Describe the solution you'd like

Update the docs and docstrings of these instrumentors that have `instrument_connection` methods defined:

- [x] [aiopg](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-aiopg/src/opentelemetry/instrumentation/aiopg/__init__.py)
- [x] [mysql-connector](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-mysql/src/opentelemetry/instrumentation/mysql/__init__.py)
- [x] [mysqlclient](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-mysqlclient/src/opentelemetry/instrumentation/mysqlclient/__init__.py)
- [x] [psycopg](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-psycopg/src/opentelemetry/instrumentation/psycopg/__init__.py)
- [x] [psycopg2](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-psycopg2/src/opentelemetry/instrumentation/psycopg2/__init__.py)
- [x] [pymysql](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-pymysql/src/opentelemetry/instrumentation/pymysql/__init__.py)
- [x] [sqlite3](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-sqlite3/src/opentelemetry/instrumentation/sqlite3/__init__.py)

I am excluding [dbapi](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-dbapi/src/opentelemetry/instrumentation/dbapi/__init__.py) because it is more like a shared integration between instrumentors for concrete db drivers.

### Would you like to implement a fix?

None

**Comment by beijiez** [comment]
Hey! Great issue. I'd like to take this on

**Comment by tammy-baylis-swi** [comment]
Thanks @beijiez for volunteering! Assigned to you.
