### ISSUE TITLE
opentelemetry-bootstrap --action=install would install with UV/Poetry instead of pip

### ISSUE THREAD

**Issue by idan-rahamim-lendbuzz** [open-telemetry/opentelemetry-python-contrib#3158]
### What problem do you want to solve?

Make bootstrap faster

### Describe the solution you'd like

opentelemetry-bootstrap --action=install would install with UV/Poetry instead of pip

**Comment by xrmx** [comment]
Bootstrapping with uv is already documented here https://opentelemetry.io/docs/zero-code/python/#bootstrap-using-uv
