### ISSUE TITLE
Suggestion: opentelemetry-instrumentation-grpc client should either be an actual gRPC client-side interceptor or be renamed

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-python-contrib#322]
The [gRPC client "interceptor"](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/c265e2f035f0757aa8b3757003641c87edc70007/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_client.py#L78-L80) isn't currently an actual client-side interceptor (in the sense of, e.g., subclassing any or all of the [client-side interceptor types](https://grpc.github.io/grpc/python/grpc.html#grpc.intercept_channel)) and therefore can't be provided to [`grpc.intercept_channel`](https://grpc.github.io/grpc/python/grpc.html#grpc.intercept_channel). This seems pretty confusing to me.

I think the best approach would be to change up the implementation a bit so that it actually can be used as a real interceptor. I _believe_, but haven't verified, that this would be pretty doable; I know I've seen problems in other gRPC implementations where actual interceptors don't have access to some of the information you might want for instrumentation purposes, but based on a super preliminary look at the current code I think that's not the case here.

Short of that, it might make sense to rename the relevant code so it's less misleading?

**Comment by alertedsnake** [comment]
I'm with you here - this was the approach I took when rewriting the server side, and it would be good to have them be consistent, and also modern.
