### ISSUE TITLE
Broken links to project in a few READMEs

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-python-contrib#323]
- https://github.com/open-telemetry/opentelemetry-python-contrib/blob/5fc26d3264293a4898c18b911cbcfe83dbc6a313/instrumentation/opentelemetry-instrumentation-aiohttp-client/setup.cfg#L22
- https://github.com/open-telemetry/opentelemetry-python-contrib/blob/5fc26d3264293a4898c18b911cbcfe83dbc6a313/instrumentation/opentelemetry-instrumentation-asyncpg/setup.cfg#L22
- Maybe more

These links are missing "tree/main" and give 404

**Comment by cynthiakedu** [comment]
Can I take this issue?

**Comment by aabmass** [comment]
Thanks @cynthiakedu assigned to you 🙂
