### ISSUE TITLE
Add a link to examples folder in core repo for every instrumentation

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#328]
As discussed in 02/11/2021 SIG, we want to have a link in the "References" section in each instrumentation so users can find related examples in the core repo for the instrumentations they are using.

**Comment by lzchen** [comment]
https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples

**Comment by dhruv-vora** [comment]
Can I take this issue?

**Comment by owais** [comment]
@dhruv-vora assigned to you
