### ISSUE TITLE
Move common instrumentation utils to own module

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [open-telemetry/opentelemetry-python-contrib#33]
Based on https://github.com/open-telemetry/opentelemetry-python-contrib/pull/21/files#r406962832.

There are many utilities around that should be moved to its own package to make them reusable by other instrumentations.

**Comment by codeboten** [comment]
This is too general of an issue at this point. Some common code has already been moved. Closing and will open new issues as needed.
