### ISSUE TITLE
Missing pypi listing: opentelemetry-util-http

### ISSUE THREAD

**Issue by sambarnes** [open-telemetry/opentelemetry-python-contrib#339]
**Describe your environment**
> Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

The pypi listing for opentelemetry-util-http appears to have been dropped: https://pypi.org/project/opentelemetry-util-http/
If there is another listing elsewhere that I should be using instead, please let me know and I can close this!

Though, this is the link in the project's subfolder, so I figured it was the official one.

**Steps to reproduce**
```
poetry add opentelemetry-instrumentation-fastapi==0.18b0

Updating dependencies
Resolving dependencies... (1.2s)

  SolverProblemError

  Because opentelemetry-instrumentation-fastapi (0.18b0) depends on opentelemetry-util-http (0.18b0) which doesn't match any versions, opentelemetry-instrumentation-fastapi is forbidden.
  So, because app depends on opentelemetry-instrumentation-fastapi (0.18b0), version solving failed.
```

Same behavior with `pipenv install opentelemetry-instrumentation-fastapi==0.18b0`

**What is the expected behavior?**
Successfully installing `opentelemetry-instrumentation-fastapi` and its sub-dependency `opentelemetry-util-http`

**What is the actual behavior?**
Missing listing for `opentelemetry-util-http` so dependency resolution fails

**Comment by codeboten** [comment]
The `opentelemetry-util-http` package was just released: https://pypi.org/project/opentelemetry-util-http/0.18b0/

**Comment by sambarnes** [comment]
Right on! Really appreciate the quick response there. Can confirm it was able to install

Closing 👍
