### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#35]
Need to agree on where the documentation for all the instrumentation packages will live. I suggest as a starting point it just lives with the package in pypi.

**Comment by wilguo** [comment]
Hi! Is this issue still available? I would love to pick it up as a first issue!

**Comment by codeboten** [comment]
hey @wilguo, the issue is still opened but currently this repo is not being used yet. It still needs quite a bit of work before it can be used. The issues in the core opentelemetry-python repo are likely a better place to look for tasks that can help the project get to GA (https://github.com/open-telemetry/opentelemetry-python/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by codeboten** [comment]
This is already done.
