### ISSUE TITLE
gRPC Client Instrument: Why do we need to define channel_type?

### ISSUE THREAD

**Issue by dgildeh** [open-telemetry/opentelemetry-python-contrib#365]
I've just spent a few hours over the past 2 weeks debugging as to why my local gRPC trace propagation works between 2 services on an insecure gRPC channel, but as soon as I deploy to Google Cloud Run (which requires ssl secured requests) the trace ID wasn't propagated to my backend service. 

GrpcInstrumentorClient().instrument(channel_type='secure')

Turns out that when you call the instrumentation library for gRPC, you need to set channel_type='secure' for secure channels for those to be instrumented in the gRPC client calling the backend service, which is why insecure channels were propagating (default instrumentation) and my secure channels weren't. I ended up writing this code for it to work:

```
    def get_channel(self, host:str, port:int) -> grpc.Channel:
        """
        Get a secure channel initialised to make service-to-service calls
        on Google Cloud Run
        :param host:      The hostname of the service to connect to
        :param port:      The port to connect to on the service
        :returns:         A secure gRPC channel
        """

        if port == 443:
            # Setup secure channel - Google Cloud Run will provide certs and JWT authentication
            # automatically
            logger.info(f"Connecting to {host}:{port} on secure channel...")
            GrpcInstrumentorClient().instrument(channel_type='secure')
            ssl = grpc.ssl_channel_credentials()
            jwt = grpc.access_token_call_credentials(self.get_token(f"https://{host}"))
            composite_credentials = grpc.composite_channel_credentials(
                ssl, jwt
            )
            channel = grpc.secure_channel(f"{host}:{port}", composite_credentials)
            return channel
        else:
            logger.info(f"Connecting to {host}:{port} on insecure channel...")
            GrpcInstrumentorClient().instrument()
            channel = grpc.insecure_channel(f"{host}:{port}")
            return channel
```

Why does the user need to define which type of channel they're using to connect? Can we not wrap both types of channel automatically so the user gets it all working with the example code in the comments?

Also - need to get the README.md up to date with clear documentation, right now all the documentation on how to instrument gRPC is only in the code comments so wasn't obvious to find!

**Comment by aabmass** [comment]
> Why does the user need to define which type of channel they're using to connect? Can we not wrap both types of channel automatically so the user gets it all working with the example code in the comments?

Looking at the code, this definitely sounds like a bug https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2d9df106455de7b1b5aa3dfe180059fe9366d039/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/__init__.py#L178-L190

**Comment by alertedsnake** [comment]
If you just don't set either one, you automatically get both, that's what the code on 186 there does.  I added this because I agree with you, we shouldn't have to specify, it should just handle this automatically.  The code on 179-182 is the legacy stuff, which I preserved to be backwards compatible.

Just omit the flag and you should be fine.

**Comment by dgildeh** [comment]
OK, I have 0.17b0 installed, which I got stuck on due to other OpenTelemetry modules that only worked on that version, looks like you've fixed this in a newer version from reading the code. Will try and upgrade to latest, but with everything iterating at its own pace, I've had a few issues where module dependencies between the API, SDK, Google Cloud Exporter, Google Cloud Propagator, and all the instrumentors on my project don't all have the same versions and play well together.

Will upgrade and try again - I see you've also fixed missing dependency issues in your setup.py which is good in latest version!

Will test and close once its all working

**Comment by owais** [comment]
Sounds like this has been fixed and is not an issue anymore so closing. 

Feel free to re-open if this is still a problem.
