### ISSUE TITLE
Filter out health check request in grpc

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-python-contrib#373]
**Is your feature request related to a problem?**
As of 0.18b1, `opentelemetry-instrumentation-grpc` doesn't have the feature to exclude trace propagation to the specific endpoints. Because of this, gRPC servers always send health check request traces to the backend via the exporter as you see in the screenshot below:
![image](https://user-images.githubusercontent.com/145104/111555143-ae4fe500-877f-11eb-99c8-3ae83ae972ed.png)

**Describe the solution you'd like**
It would be nice if opentelemetry-instrumentation-grpc could have something similar to `OTEL_PYTHON_FLASK_EXCLUDED_URLS` in `opentelemetry-instrumentation-flask`.

**Describe alternatives you've considered**
Each exporters support filter option to avoid sending unnecessary traces to the backend.

**Additional context**
Health checking is the common practice in Kubernetes and the traces for such requests sometimes pollute the Trace dashboard and leads to unnecessary costs for SaaS services.

**Comment by jan25** [comment]
I could give this a shot if not already picked up :)

**Comment by lzchen** [comment]
@jan25 
Sure thing.

**Comment by rahulgupta92** [comment]
Is this feature being worked upon or has been implemented? Any suggestions/workarounds for excluding such requests?

**Comment by lzchen** [comment]
@jan25 
Any updates on this?

**Comment by avzis** [comment]
@lzchen @ymotongpoo 
I'm looking for a good first issue, is this still relevant?

**Comment by ymotongpoo** [comment]
@avzis Yes, I think so. I'm working on Go version in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2572, and you can port it to Python.

**Comment by lzchen** [comment]
@avzis 
I'll assign this to you.

**Comment by ymotongpoo** [comment]
So, is @avzis working on this now? Because https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2572 is merged, now I can port it to Python now if necessary.

**Comment by lzchen** [comment]
@avzis 
Are you currently working on this? I can assign it to @ymotongpoo if not.

**Comment by avzis** [comment]
hi, yes

**Comment by avzis** [comment]
i mean "yes i'm working on it", sorry for not being clear

**Comment by ymotongpoo** [comment]
oh, I have implemented mostly in #1241 but for unit tests.

**Comment by avzis** [comment]
ok, so you finish it..
ill take another issue
good luck :)
