### ISSUE TITLE
Provide instrumentations a way to exclude_urls that is not using environment variables

### ISSUE THREAD

**Issue by cdvv7788** [open-telemetry/opentelemetry-python-contrib#375]
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L40

**Is your feature request related to a problem?**
I want to get the urls to exclude from somewhere else than environment variables.

**Describe the solution you'd like**
Providing an argument to `exclude_urls`, using as default `_exclude_urls` (generated from environment variable) should be an option for other setups.

**Describe alternatives you've considered**
The fastapi instrumentation just adds a middleware. I copied that method with the additional variable as input.

**Additional context**
This is a simple addition, in case it is up to consideration. I can send a PR if that is ok.

**Comment by owais** [comment]
>  This is a simple addition, in case it is up to consideration. I can send a PR if that is ok.

@cdvv7788 Please feel free to send one or more :)

**Comment by ivergara** [comment]
Isn't this issue closed by #486?

**Comment by cdvv7788** [comment]
That is correct. Thanks!
