### ISSUE TITLE
Updating redis instrumentation to use instrumentor interface

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#38]
Currently the redis instrumentation documents using the patch interface directly, this should be updated once this issue is resolved: https://github.com/open-telemetry/opentelemetry-python/issues/554

Here's documentation:
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/21/files/676c3499819fcab55d0de47c7ef8555f81bb0894#diff-a42497cde4dba9f19c87f87a001c4cc8R28

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/open-telemetry/opentelemetry-python/pull/595.
