### ISSUE TITLE
gRPC instrumentation should lower-case metadata

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-python-contrib#382]
**Describe your environment**
Current version of gRPC instrumentation

**Steps to reproduce**
Any of
- Trying to set (in `inject()`) a carrier key with non-lowercase chars
- Trying to extract a key with non-lowercase chars (have to iterate over `keys()` instead)

**What is the expected behavior?**
- gRPC client instrumentation's setter passed to `inject()` should convert keys to lowercase. gRPC will throw an exception if you set non-lowercase chars in metadata. https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2f088f8de06043c1f56d092a9f28e408a434f895/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_client.py#L57-L60
- gRPC server instrumentation's getter passed to `extract()` should convert `get('FoO')` -> `metadata['foo']`. It is currently using `DictGetter()` which doesn't handle this https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2f088f8de06043c1f56d092a9f28e408a434f895/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_server.py#L178

**What is the actual behavior?**
- Clients calls raise an exception and fail when a propagator is set that doesn't use all lowercase
- Server calls will not propagate when a propagator is set that doesn't use all lowercase

**Comment by NickSulistio** [comment]
Can you assign this bug to me? @NickSulistio

cc @alolita

**Comment by aabmass** [comment]
I think there is an existing PR which may address this, let me check with the author and link it

**Comment by aabmass** [comment]
For more context see https://github.com/grpc/grpc/issues/9863

The code linked in the issue is gone but the issue remains the same

**Comment by owais** [comment]
Fixed in: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/392
