### ISSUE TITLE
OTEL_PYTHON_FASTAPI_EXCLUDED_URLS doen't seem to have any effect

### ISSUE THREAD

**Issue by juliankeppel** [open-telemetry/opentelemetry-python-contrib#390]
**Describe your environment**
We use this lib for sending traces of our APIs based on FastAPI/Hypercorn to Jaeger. The APIs are hosted on a Kubernetes-Cluster.

Versions/dependencies used:
python = 3.8
fastapi = 0.63.0
opentelemetry-api = 1.0.0rc1
opentelemetry-sdk = 1.0.0rc1
opentelemetry-instrumentation-fastapi =0.18b1
opentelemetry-exporter-jaeger =1.0.0rc1
opentelemetry-propagator-jaeger = 1.0.0rc1
hypercorn = 0.11.2

We want to exclude some "internal" paths (liveness/readiness checks, docs, ...) and tried two different ways of defining the paths to exclude:
* in the application code with `os.environ["OTEL_PYTHON_FASTAPI_EXCLUDED_URLS"] = "docs,internal/.*"`
* in the Dockerfile with `ENV OTEL_PYTHON_FASTAPI_EXCLUDED_URLS="docs,internal/.*"`

We also tried "docs,internal/liveness,internal/readiness" to ensure it's no problem with the regex itself.

**What is the expected behavior?**
We expect that the paths defined with `OTEL_PYTHON_FASTAPI_EXCLUDED_URLS` are excluded from tracing and thus should not show up in Jaeger.

**What is the actual behavior?**
In Jaeger, we see all the paths, regardless what we tried so far. It seems that the excluding mechanism doesn't work as expected.

**Comment by owais** [comment]
For anyone wanting to look into this, here are some interesting places to look at:



https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L58

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/634c2ac0aec716e7a660b124367d7be50bda8fcd/instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py#L188-L190

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/634c2ac0aec716e7a660b124367d7be50bda8fcd/util/opentelemetry-util-http/src/opentelemetry/util/http/__init__.py#L28-L29

**Comment by adamantike** [comment]
I have written the following Dockerfile to try to reproduce the issue, but it correctly excludes the URLs specified by the `OTEL_PYTHON_FASTAPI_EXCLUDED_URLS` regex:

```dockerfile
FROM python:3.8-slim

RUN pip install --no-cache \
      fastapi=="0.63.0" \
      opentelemetry-api=="1.0.0rc1" \
      opentelemetry-distro=="0.18b0" \
      opentelemetry-sdk=="1.0.0rc1" \
      opentelemetry-instrumentation-fastapi=="0.18b1" \
      hypercorn=="0.11.2"

WORKDIR /app

RUN printf 'import sys \n\
from fastapi import FastAPI \n\
\n\
version = f"{sys.version_info.major}.{sys.version_info.minor}" \n\
app = FastAPI() \n\
\n\
@app.get("/healthcheck/") \n\
async def read_healthcheck(): \n\
    return {"test": "1"} \n\
\n\
@app.get("/docs/") \n\
async def read_docs(): \n\
    return {"docs": "Hello, World!"} \n\
\n\
@app.get("/v1/internal/products/") \n\
async def read_products(): \n\
    return {"products":[]} \n\
' > /app/main.py

ENV OTEL_PYTHON_FASTAPI_EXCLUDED_URLS="docs,internal/.*"

EXPOSE 80

CMD ["opentelemetry-instrument", "--trace-exporter", "console_span", "hypercorn", "main:app", "--bind", "0.0.0.0:80"]
```

To use it:
* Build the Docker image: `docker build -t test-otel-py-contrib-390 .`
* Run it, exposing port 80 of the container: `docker run --rm -p 8080:80 test-otel-py-contrib-390`
* Make requests to URLs: http://localhost:8080/healthcheck/, http://localhost:8080/docs/, http://localhost:8080/v1/internal/products/. Collected spans are displayed in container's standard output.

@juliankeppel, do you have more context regarding how this boilerplate code can resemble your current environment, to have better chances at reproducing the issues? E.g., if you're using auto-instrumentation (or how do you manually instrument the application), if you run the server with a different command, etc.

**Comment by adamantike** [comment]
Also tested with the following Dockerfile, for manual instrumentation:

```dockerfile
FROM python:3.8-slim

RUN pip install --no-cache \
      fastapi=="0.63.0" \
      opentelemetry-api=="1.0.0rc1" \
      opentelemetry-distro=="0.18b0" \
      opentelemetry-sdk=="1.0.0rc1" \
      opentelemetry-instrumentation-fastapi=="0.18b1" \
      hypercorn=="0.11.2"

WORKDIR /app

RUN printf 'from fastapi import FastAPI \n\
from opentelemetry import trace \n\
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor \n\
from opentelemetry.sdk.trace import TracerProvider \n\
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleExportSpanProcessor \n\
\n\
trace.set_tracer_provider(TracerProvider()) \n\
tracer = trace.get_tracer_provider().get_tracer(__name__) \n\
trace.get_tracer_provider().add_span_processor(SimpleExportSpanProcessor(ConsoleSpanExporter())) \n\
\n\
app = FastAPI() \n\
\n\
@app.get("/healthcheck/") \n\
async def read_healthcheck(): \n\
    return {"test": "1"} \n\
\n\
@app.get("/docs/") \n\
async def read_docs(): \n\
    return {"docs": "Hello, World!"} \n\
\n\
@app.get("/v1/internal/products/") \n\
async def read_products(): \n\
    return {"products": []} \n\
\n\
FastAPIInstrumentor.instrument_app(app) \n\
' > /app/main.py

ENV OTEL_PYTHON_FASTAPI_EXCLUDED_URLS="docs,internal/.*"

EXPOSE 80

CMD ["hypercorn", "main:app", "--bind", "0.0.0.0:80"]
```

**Comment by lonewolf3739** [comment]
@juliankeppel did @adamantike comments help? Also want to share that the excluded list is prepared at the time of import for once and if you set the env later it doesn't change https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L26.

**Comment by juliankeppel** [comment]
@lonewolf3739, @adamantike : Sorry for this very late response! I think the problem was basically that I set the environment variable too late so that it wasn't taken into account. It seems to work now. Thank you for your assistance!

**Comment by lonewolf3739** [comment]
Cool, closing the issue.
