### ISSUE TITLE
[redis] Unable to initiate tracer

### ISSUE THREAD

**Issue by ashok-an** [open-telemetry/opentelemetry-python-contrib#405]
**Describe your environment** 
Unable to initiate tracer

**Steps to reproduce**
```
 ## Redis
 from opentelemetry.instrumentation.redis import RedisInstrumentor
 import redis
 RedisInstrumentor().instrument()
 redis_client = redis.StrictRedis(host="localhost", port=6379)
 ```

**What is the expected behavior?**
tracer instance

**What is the actual behavior?**
```
Overriding of current TracerProvider is not allowed
Traceback (most recent call last):
  File "/tmp/tracing/example/scrubber_app.py", line 9, in <module>
    tracer = utils.init_tracer('sample_app')
  File "/tmp/utils.py", line 40, in init_tracer
    trace.get_tracer_provider().add_span_processor(
AttributeError: '_DefaultTracerProvider' object has no attribute 'add_span_processor'
```

**Additional context**
Reference: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/__init__.py

**Comment by dgzlopes** [comment]
I have the same problem, but with the Flask instrumentation.

**Comment by lonewolf3739** [comment]
You need to set the trace pipeline with concrete implementation of tracer provider before adding span processor. Please share more context.

**Comment by codeboten** [comment]
hey @ashok-an and @dgzlopes, in both cases you will need to configure a `TracerProvider` in the code before any instrumentation can make calls to the tracer. If you're using auto-instrumentation, this can be set via environment variables, otherwise you would need something like this in the code:

```
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider

trace.set_tracer_provider(TracerProvider())
```

**Comment by dgzlopes** [comment]
Thanks, @lonewolf3739 and @codeboten!

Fixed my code by moving the TraceProvider configuration to the top. On my case:
```python
# This works!
trace.set_tracer_provider(TracerProvider())
jaeger_exporter = JaegerExporter(
...
)
trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(jaeger_exporter)
)
```
```python
# This doesn't work
jaeger_exporter = JaegerExporter(
...
)
trace.set_tracer_provider(TracerProvider())
trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(jaeger_exporter)
)
```

**Comment by owais** [comment]
@dgzlopes glad you found a way to make it work. What you did to fix it is still the recommended way to setup tracing i.e, registering a global tracer provider before other things. We'll still ship a fix for this in the next release so cases where users cannot control the order in which things are setup will work as expected as well.

**Comment by dgzlopes** [comment]
Thanks for the response @owais! I'll keep that in mind :)
