### ISSUE TITLE
[Flask] Replace span name callback with request and response hooks 

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#410]
Flask instrumentation accepts a span name callback which should be replaced with more generic request/response callbacks (hooks). 

Details: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/408

**Comment by NickSulistio** [comment]
I'll pick this up!

cc @alolita

**Comment by NickSulistio** [comment]
Should we close this issue now? @lzchen
