### ISSUE TITLE
 [urllib] Replace span name callback with request and response hooks 

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#412]
Urrllib instrumentation accepts a span name callback which should be replaced with more generic request/response callbacks (hooks). 

Details: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/408

**Comment by ryokather** [comment]
@owais I'd be happy to take this up and work on the remaining instrumentations that don't have request and response hooks implemented yet!

**Comment by ryokather** [comment]
Been working on this and noticed that while I was able to accomplish this in the `urllib` instrumentation, an HTTPRequest object is not accessible with the way `urllib3` is implemented. What should be passed to the `response_hook` in this case? 

Also if I'm not mistaken an issue doesn't exist for request and response hooks for `asgi` which is necessary for the starlette and fastapi instrumentations. I can create a new issue for this and take it on as well.

**Comment by lzchen** [comment]
Finished with #576
