### ISSUE TITLE
add note about cloning core repo in contrib doc

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#414]
The contributing guidelines should mention the need to clone the core repo for users to run tests locally:

```
git clone https://github.com/open-telemetry/opentelemetry-python.git opentelemetry-python-core
```

**Comment by dhruv-vora** [comment]
Hey @codeboten, I can do this one. Can you assign it to me?

**Comment by codeboten** [comment]
sure, thanks!
