### ISSUE TITLE
Jaeger exporter fails if scheme is specified in endpoint URL

### ISSUE THREAD

**Issue by atrepczik** [open-telemetry/opentelemetry-python-contrib#429]
**Describe your environment**
Python 3.8.5
opentelemetry-api 1.0.0
opentelemetry-sdk 1.0.0
opentelemetry-exporter-jaeger-proto-grpc 1.0.0

**Steps to reproduce**
If the environment variable of `OTEL_EXPORTER_JAEGER_ENDPOINT` is specified as `http://localhost:14250` like the default value in [OpenTelemetry Environment Variable Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter), the Jaeger gRPC exporter fails sending spans as the underlying library is not able to do DNS resolution for `http://localhost:14250`.

If the scheme part is omitted in the (e.g. `localhost:14250`), everything works as expected.

**What is the expected behavior?**
The default value from the spec document should work, like it does for the Java agent. Alternatively, it should be documented that this must be configured differently for Python.

**What is the actual behavior?**
Spans are not sent to Jaeger. The application produces a traceback.

```
Traceback (most recent call last):
  File "/home/atrepczik/workspace/flask-opentelemetry/venv/lib/python3.8/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 331, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/home/atrepczik/workspace/flask-opentelemetry/venv/lib/python3.8/site-packages/opentelemetry/exporter/jaeger/proto/grpc/__init__.py", line 164, in export
    self._collector_grpc_client.PostSpans(request)
  File "/home/atrepczik/workspace/flask-opentelemetry/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/atrepczik/workspace/flask-opentelemetry/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for service: http://localhost:14250"
	debug_error_string = "{"created":"@1618232615.769967660","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2137,"referenced_errors":[{"created":"@1618232615.769964180","description":"DNS resolution failed for service: http://localhost:14250","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":361,"grpc_status":14,"referenced_errors":[{"created":"@1618232615.769904855","description":"C-ares status is not ARES_SUCCESS qtype=A name=http://localhost:14250 is_balancer=0: Could not contact DNS servers","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":716,"referenced_errors":[{"created":"@1618232615.768847611","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name=http://localhost:14250 is_balancer=0: Could not contact DNS servers","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":716}]}]}]}"
```

**Comment by lonewolf3739** [comment]
@atrepczik  This was addressed in https://github.com/open-telemetry/opentelemetry-python/pull/1771 and released in new version. Please update the version and let us know if this is still a problem. Thanks.
