### ISSUE TITLE
Flask: Conditionally create SERVER spans

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#446]
Part of #445

**Comment by pravarag** [comment]
@owais  I would like to work on this issue as a beginner. Kindly let me know if it's okay to pick this issue or not 🙂

**Comment by owais** [comment]
Hi @pravarag. Yes, you can pick it up but be warned that it might sound simpler than it is. We've had at least one other person attempt this only to find out it was more complicated than it looked :) 

I don't want to discourage you but just trying to set the expectations. I've removed "good first issue" label from this ticket as it was a bit misleading I think.

All things considered, this is not a hard or complex issue but definitely not a byte-sized, beginner friendly problem either. Happy to assign it to you.

**Comment by pravarag** [comment]
Thanks @owais , if possible could you please help me in finding a beginner friendly issue to work on 🙂 , I'll be happy to take that.

**Comment by owais** [comment]
https://github.com/open-telemetry/opentelemetry-python-contrib/labels/good%20first%20issue
https://github.com/open-telemetry/opentelemetry-python/labels/good%20first%20issue

@pravarag ^

**Comment by ashu658** [comment]
Hi @owais 
I would like to work on this as my first issue!

**Comment by owais** [comment]
Done
