### ISSUE TITLE
Django: Conditionally create SERVER spans

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#448]
Part of #445

**Comment by sanketmehta28** [comment]
Hi @owais : I would like to work on this as my first contribution to Opentelemetry.
Can you please assign it to me?

**Comment by owais** [comment]
Assigned. @ashu658 was planning to work on #445 as well. Please coordinate so you don't work on the same tickets.

**Comment by sanketmehta28** [comment]
Sure, We are from the same team. we will coordinate with each other.

**Comment by sanketmehta28** [comment]
You can close this issue as the PR mentioned above is merged into main branch
