### ISSUE TITLE
Add labels to entry level tasks for new contributors

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-python-contrib#45]
Hi,

based on https://github.com/open-telemetry/community/issues/469 I have added **open-telemetry/opentelemetry-python-contrib** to Up For Grabs:

https://up-for-grabs.net/#/filters?names=662

There are currently no issues with label [help wanted](https://github.com/open-telemetry/opentelemetry-python-contrib/labels/help%20wanted). Please add this label to your entry level tasks, so people can find a way to contribute easily. 

If "help wanted" is not the right label, let me know and I can change it (e.g. to "good first issue" or "up-for-grabs"), or you can provide a pull request by editing https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/opentelemetry-python-contrib.yml

Thanks!

**Comment by ffe4** [comment]
@codeboten the `help wanted` tag is registered for both `opentelemetry-python` and `opentelemetry-python-contrib`. Should I create a PR to change both to `good first issue` or are we fine with this?

Quote from the website:
>What sort of tasks are a good fit?
>
>- Tasks should take no longer than a few nights' worth of work
>- Tasks should stand alone - avoid core functionality on which other tasks depend
>- Tasks should be well described with pointers to help the implementer
>
>We suggest the label up-for-grabs but using a different name is also acceptable.
