### ISSUE TITLE
FastAPI:  Conditionally create SERVER spans

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#451]
Part of #445

**Comment by sanketmehta28** [comment]
Hi @owais : Can you please assign it to me?

**Comment by sanketmehta28** [comment]
I can see that we already have resolved the same type of issue for ASGI in [PR ](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/843/)
As fastapi internally uses asgi middleware, it automatically resolves the same for FastAPI. (unittest is the proof)
So should we close this issue?

**Comment by owais** [comment]
Can we add a test to FastAPI package to verify the behaviour so we catch any breakage in future?

**Comment by sanketmehta28** [comment]
Test case has already been added as a part of the PR mentioned in above comment

**Comment by owais** [comment]
Oh nice! I thought it would contain test for ASGI package. Sounds good. I'll close this one but may be we should add a test case to ASGI package as well?

**Comment by sanketmehta28** [comment]
yes Agreed.

**Comment by owais** [comment]
The issue has been resolved already. You can open a new issue or just submit a PR without an issue if you'd like.

**Comment by sanketmehta28** [comment]
Here is the PR for ASGI unit test: [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/899)
