### ISSUE TITLE
sqlalchemy: TypeError: cannot create weak reference to 'pyodbc.Cursor' object

### ISSUE THREAD

**Issue by jomasti** [open-telemetry/opentelemetry-python-contrib#460]
**Describe your environment** 
See the repo provided below for a simple reproduction environment. I was using Python 3.8.8 when running it locally.

**Steps to reproduce**
Provided a reproduction repo: https://github.com/jomasti/opentelemetry-instrumentation-sqlalchemy-pyodbc-bug

**What is the expected behavior?**
I expected the query to work successfully when the engine is instrumented. The code in the repo above works fine with 0.18b1.

**What is the actual behavior?**
Ran into `TypeError: cannot create weak reference to 'pyodbc.Cursor' object`.

**Additional context**
#315 appears to be the culprit.

**Comment by ewolz3** [comment]
For reference, I have the same error when I try to instrument SQLAlchemy used with an Oracle database. 

```
2021-05-04T10:57:11.571-04:00 [ERR] self.data[ref(key, self._remove)] = value
2021-05-04T10:57:11.571-04:00 [ERR] TypeError: cannot create weak reference to 'cx_Oracle.Cursor' object
2021-05-04T10:57:11.571-04:00 [ERR] The above exception was the direct cause of the following exception:
```
