### ISSUE TITLE
status_code attribute with requests library

### ISSUE THREAD

**Issue by ankitnayan** [open-telemetry/opentelemetry-python-contrib#464]
I have been using the requests library to call external APIs. The spans generated do not have attributes `http.status_code` populated. It is empty. It would be very helpful to know if the external calls responded with status code 5xx. 

I did a sample call to `https://w3schools.com/xyz` which returns `404` status code. Below is the list of attributes I received. 

```
["http.method:GET","http.status_code:","http.url:https://w3schools.com/xyz"]
```

Is this expected?

**Comment by lonewolf3739** [comment]
No, I don't think this is expected behaviour.

**Comment by ankitnayan** [comment]
Though I don't think this is an issue just at `opentelemetry-instrumentation-requests`. I have other APIs in the application which return 5xx but the server spans have no error labels. Shall I create an issue at the opentelemetry-python repo?

Also, would it help if I upload the repo for the test application that I have used?

**Comment by lonewolf3739** [comment]
@ankitnayan I did a quick check with requests instrumentation and it works fine. Here is the output for get request to `https://w3schools.com/xyz`. 
```
{
    "name": "HTTP GET",
    "context": {
        "trace_id": "0xfdfa378b4f3fa55505028a1273093daa",
        "span_id": "0x889dabdda7e2a46e",
        "trace_state": "[]"
    },
    "kind": "SpanKind.CLIENT",
    "parent_id": null,
    "start_time": "2021-04-21T15:46:48.753149Z",
    "end_time": "2021-04-21T15:46:53.311108Z",
    "status": {
        "status_code": "ERROR"
    },
    "attributes": {
        "http.method": "GET",
        "http.url": "https://w3schools.com/xyz",
        "http.status_code": 404
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.1.0",
        "service.name": "unknown_service"
    }
}
```

Where are you checking the received span attributes?

**Comment by lonewolf3739** [comment]
> Though I don't think this is an issue just at `opentelemetry-instrumentation-requests`. I have other APIs in the application which return 5xx but the server spans have no error labels. Shall I create an issue at the opentelemetry-python repo?
> 
> Also, would it help if I upload the repo for the test application that I have used?

Yes, please create separate issue and Yes, a test application repo would always be helpful.

**Comment by ankitnayan** [comment]
You are right, `status_code` is there. I was converting all attributes to string which was giving me an empty string for `status_code` since it is type `INT`
