### ISSUE TITLE
Flask auto-instrumentation w/ debug=True doesn't work

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#477]
**Describe your environment** 
Using the auto-instrumentation example https://opentelemetry-python.readthedocs.io/en/latest/examples/auto-instrumentation/README.html and enabling `debug=True` in `app.run` disables instrumentation.

**Steps to reproduce**
Follow the example and update the code to enable debug mode in flask

**What is the expected behavior?**
Traces are emitted

**What is the actual behavior?**
No trace is emitted

**Comment by codeboten** [comment]
This appears to be a limitation when using the reloader, maybe related to https://github.com/open-telemetry/opentelemetry-python/issues/1794

**Comment by lzchen** [comment]
@ocelotl 
Is this resolved?

**Comment by ocelotl** [comment]
@lzchen, yes closing :+1:

**Comment by tha2015** [comment]
It looks like a limitation of the new version ( See https://github.com/open-telemetry/opentelemetry-python/issues/1800#issuecomment-828648346 ). And although it was documented, I really hope it can be supported.

**Comment by NathanielRN** [comment]
This was closed in https://github.com/open-telemetry/opentelemetry-python/pull/1795 with an update to the documentation explaining how to get around this issue.

However I agree with @tha2015 that this is really easy to miss, so I mentioned in this new issue https://github.com/open-telemetry/opentelemetry-python-contrib/issues/546#issuecomment-866221083 that we should probably come up with another solution to make the issue more obvious.
