### ISSUE TITLE
opentelemetry-instrumentation-django cannot support Dajngo 1.11

### ISSUE THREAD

**Issue by unique0lai** [open-telemetry/opentelemetry-python-contrib#512]
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2bd60536cc889768c54170757d7715a483d8b22f/instrumentation/opentelemetry-instrumentation-django/src/opentelemetry/instrumentation/django/middleware.py#L174

https://docs.djangoproject.com/en/2.2/ref/urlresolvers/#django.urls.ResolverMatch.route
"route" is not exists before Django 2.2

**Comment by daneah** [comment]
Django 1.11 ended mainstream support 3 years ago, and LTS support ended just over 1 year ago ([handy table](https://endoflife.date/django)). I'd guess it's is a bit too old to support at this point?

That said, it would be good to understand from a design perspective the intent for support planned for other frameworks. I looked in the contribution guidelines and READMEs but didn't find anything too obvious!

**Comment by ocelotl** [comment]
> Django 1.11 ended mainstream support 3 years ago, and LTS support ended just over 1 year ago ([handy table](https://endoflife.date/django)). I'd guess it's is a bit too old to support at this point?
> 
> That said, it would be good to understand from a design perspective the intent for support planned for other frameworks. I looked in the contribution guidelines and READMEs but didn't find anything too obvious!

We haven't made a decision on which versions of which frameworks are to be supported. Nevertheless, this may no longer be relevant after #475 is merged.

**Comment by unique0lai** [comment]
OK, if it can not support Django 1.11, the install_required should be update. the supported Django version should be clear.

**Comment by owais** [comment]
> Django 1.11 ended mainstream support 3 years ago, and LTS support ended just over 1 year ago (handy table). I'd guess it's is a bit too old to support at this point?
> That said, it would be good to understand from a design perspective the intent for support planned for other frameworks. I looked in the contribution guidelines and READMEs but didn't find anything too obvious!
 
Like @ocelotl said, we don't have any guidelines yet but in general I think we wouldn't add support for very old versions but if we already support a version, I don't think we'd drop it as the library is EOLed unless it becomes too painful to support very old and latest versions at the same time.
