### ISSUE TITLE
How to deal with the problem of format display of psycopg2's SQL placeholder parameter (%s)

### ISSUE THREAD

**Issue by caowenbin** [open-telemetry/opentelemetry-python-contrib#534]
If the SQL contains a parameter placeholder (% s), the tracking result will still be displayed as is. I want to format the parameter value to make it a real SQL?
![image](https://user-images.githubusercontent.com/6927071/120950423-553d8f00-c779-11eb-9984-47e6d358087b.png)
I hope for the result:
![image](https://user-images.githubusercontent.com/6927071/120950560-9df54800-c779-11eb-8f3e-88347ab15a55.png)

**Comment by owais** [comment]
This is done deliberately in order to not leak PII or capture large values. You can still capture them by enabling `capture_parameters`. Docs: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/dbapi/dbapi.html#api
