### ISSUE TITLE
MySQLInstrumentor not working

### ISSUE THREAD

**Issue by chhaosh** [open-telemetry/opentelemetry-python-contrib#540]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

python 3.9
opentelemetry-api==1.3.0
opentelemetry-sdk==1.3.0
opentelemetry-exporter-otlp==1.3.0
opentelemetry-instrumentation-flask==0.22b0
opentelemetry-instrumentation-requests==0.22b0
opentelemetry-instrumentation-redis==0.22b0
opentelemetry-instrumentation-mysql==0.22b0
opentelemetry-instrumentation-elasticsearch==0.22b0

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

Tried example from https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/mysql/mysql.html
and also set otlp exportor
resource = Resource(attributes={
    "service.name": "sample-flask-manual"
})
otlp_exporter = OTLPSpanExporter()
trace.set_tracer_provider(TracerProvider(resource=resource))
span_processor = BatchSpanProcessor(otlp_exporter)
trace.get_tracer_provider().add_span_processor(span_processor)

None of below code works to generate trace/span
1. cnx = MySQLInstrumentor().instrument_connection(cnx)
2. cnx = MySQLInstrumentor().instrument_connection(cnx, tracer_provider=trace.get_tracer_provider())
3. MySQLInstrumentor().instrument()

I also tried the redis library
RedisInstrumentor().instrument()
Which works well

**What is the expected behavior?**
What did you expect to see?

Trace emitted for MYSQL call

**What is the actual behavior?**
What did you see instead?

Nothing

**Additional context**

**Comment by lzchen** [comment]
@chhaosh 
Does `MySQLInstrumentor().instrument()` work?

**Comment by tammy-baylis-swi** [comment]
Old issue, but I've been bumping into the same thing. In my setup, in-code instrumentation of mysql-connector does not work if the driver import and connection creation are done like this:

```
from mysql.connector import connect

MySQLInstrumentor().instrument()
cnx = connect(host=db_host, #etc)
```

But it does work if I do it [like this](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/07c3324a3bcf80ee716f90b2456f59af08b685fa/instrumentation/opentelemetry-instrumentation-mysql/src/opentelemetry/instrumentation/mysql/__init__.py#L26-L31):

```
import mysql.connector

MySQLInstrumentor().instrument()
cnx = mysql.connector.connect(host=db_host, #etc)
```

**Comment by tammy-baylis-swi** [comment]
I'm going to close this but please feel free to reopen if the above change in import and method call doesn't help.

**Comment by xrmx** [comment]
A quick test would be checking if moving the import down the _instrument, _uninstrument helper would make it work. Then maybe we can even think of passing it as dotted import path string (after checking it's fine for the dbapi wrapper)
