### ISSUE TITLE
opentelemetry-util-http requiring asgiref

### ISSUE THREAD

**Issue by cdvv7788** [open-telemetry/opentelemetry-python-contrib#547]
**Steps to reproduce**
Install `opentelemetry-util-http`. It will install `asgiref`.

**What is the expected behavior?**
This dependency is not installed.

**What is the actual behavior?**
`asgiref` is installed.

**Additional context**
In the code for `opentelemetry-util-http` I don't see `asgiref` being used at all. Unless there is a good reason to keep it around, I am using `ExcludeList` outside of ASGI/WSGI environments, and I would prefer getting rid of the dependency in this place. If it is ok to remove it, it should be trivial. I can create the PR, just need confirmation.

**Comment by lzchen** [comment]
I believe this can be removed.

**Comment by cdvv7788** [comment]
I will try to remove it this weekend. How can I mark it as not stale?

**Comment by codeboten** [comment]
I added the triaged label, that should do it @cdvv7788!
