### ISSUE TITLE
opentelemetry-instrumentation-httpx package is not in PyPI repository

### ISSUE THREAD

**Issue by LtTempletonPeck** [open-telemetry/opentelemetry-python-contrib#573]
**Describe your environment** 
```
Kernel: 5.11.4-1-rt11-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 
Desktop: Xfce 4.16.0 
Distro: Manjaro Linux base: Arch Linux
Python: 3.8
Poetry: 1.1.6
Pip: 20.3.1
```

**Steps to reproduce**
```
$ pip install opentelemetry-instrumentation-httpx
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-httpx
ERROR: No matching distribution found for opentelemetry-instrumentation-httpx
```

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
opentelemetry-instrumentation-httpx package is not in PyPI [repository](https://pypi.org/project/opentelemetry-instrumentation-httpx/) 

**Additional context**
Even the pypi package badge is broken on the httpx instrumentation [page](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx)

**Comment by lzchen** [comment]
@LtTempletonPeck 
`opentelemetry-instrumentation-httpx` will be released in our next release (sometime next week).

**Comment by lzchen** [comment]
Fixed: https://pypi.org/project/opentelemetry-instrumentation-httpx/
