### ISSUE TITLE
Datadog exporter to use service_name from Resource

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#574]
From this [comment](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/570#issuecomment-876933086)

**Comment by ericmustin** [comment]
Please assign thanks! 😊

**Comment by lzchen** [comment]
@ericmustin 
Are you still working on this?

**Comment by lzchen** [comment]
@ericmustin 
Any plans on working on this?

**Comment by ericmustin** [comment]
@lzchen Hey, sorry. I had some time scheduled for this but then I uh, quit my employer. So, unfort i have a bunch of $newjob stuff to do and this isnt a huge priority for me. @majorgreys Would probably be the right person here for all things Datadog moving forward, or at least, he can put you in touch with the appropriate ppl. fwiw i think there are plans to simply deprecate this exporter as the datadog-agent now accepts otlp natively (experimental), but i'll defer on that to @majorgreys

**Comment by lzchen** [comment]
@ericmustin 

Thanks for the reply. I'll unassign you for the time being.

**Comment by srikanthccv** [comment]
See https://github.com/open-telemetry/opentelemetry-python-contrib/pull/900 and https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1366
