### ISSUE TITLE
Decide what to do w/ elastic instrumentation for version 7+

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#620]
The elastic instrumentation fails as of version 7.14.0, this was blocking CI due to some failures in the multithreaded tests that hangs indefinitely. The tests have been removed from tox, this issue is to decide what to do next.

More context:
https://github.com/elastic/elasticsearch-py/releases/tag/v7.14.0

https://elasticsearch-py.readthedocs.io/en/v7.14.0/transports.html#product-check-on-first-request

**Comment by owais** [comment]
It should be pretty easy to mock the API check request and ensure it returns with `X-Elastic-Product: Elasticsearch` header.

**Comment by aabmass** [comment]
More context from Alex's PR and slack, the tox output shows:

```
test_elasticsearch.py::TestElasticsearchIntegration::test_dsl_create FAILED                                                                        [  8%]
test_elasticsearch.py::TestElasticsearchIntegration::test_dsl_index FAILED                                                                         [ 16%]
test_elasticsearch.py::TestElasticsearchIntegration::test_dsl_search FAILED                                                                        [ 25%]
test_elasticsearch.py::TestElasticsearchIntegration::test_instrumentor FAILED                                                                      [ 33%]
test_elasticsearch.py::TestElasticsearchIntegration::test_multithread 
```

and the error messages (for the ones that failed and didn't hang) say
```
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```

I agree it should be easy to mock. But will that fix the hanging `test_multithread` case, or is this potentially a bug in the upstream elastic search client?

**Comment by owais** [comment]
Yeah we'll need to dig deeper. Mocking and making it accept the connection would be the first step anyway.
