### ISSUE TITLE
Upgrade to Pylint 2.10.0

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#625]
**Describe your environment** 
Github Actions CI with Python 3.9

**Steps to reproduce**

- Run `tox -e lint` and wait for the command to fail or complete
- Activate the tox venv for lint: `source .tox/lint/bin/activate`
- Install pylint 2.10 or newer: `pip install 'pylint>=2.10.0'`
- Run `pylint instrumentation/opentelemetry-instrumentation-flask/src/opentelemetry/`

pylint will freeze forever. This does not happen with all packages. So far I've seen `flask` and `httpx` instrumentations trigger this behavior.  

**What is the expected behavior?**
pylint should run and finish in a reasonable amount of time.

**What is the actual behavior?**
pylint 2.10 freezes indefinitely on some packages.

**Comment by owais** [comment]
We should probably also report this to pylint as a bug.

**Comment by srikanthccv** [comment]
Fixed in #923
