### ISSUE TITLE
Allow usage of httpx 0.19.*

### ISSUE THREAD

**Issue by TomerHeber** [open-telemetry/opentelemetry-python-contrib#668]
httpx 0.19.0
opentelemetry-instrumentation-httpx 0.24b0

**Steps to reproduce**
Start the application.

**What is the expected behavior?**
No error messages.

**What is the actual behavior?**
`DependencyConflict: requested: "httpx >= 0.18.0, < 0.19.0" but found: "httpx 0.19.0"`

I'm wondering why opentelemetry-instrumentation-httpx is configured to support only 0.18.* and not anything above 0.19.*
If there are no concerns, could it allow 0.19.* as well?

https://github.com/open-telemetry/opentelemetry-python-contrib/blame/97e9f2f9ef6c775108ab30946a8668f64f37a4d9/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/package.py#L16

(Sorry. I opened it as a bug, but this is not a real bug).

**Comment by owais** [comment]
If it works, we should enable it. PRs welcome :)

**Comment by srikanthccv** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/866
