### ISSUE TITLE
Add native support for threading (new instrumentation package)

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#737]
OpenCensus has native integration for the threading module that automatically propagates tracing context across threads. It would be nice to port it over to OpenTelemetry.

OpenCensus Threading integration: https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-threading

**Comment by rdpravin1895** [comment]
Currently, whats the best way to propagate tracing context across threads? I have been looking for it, but cannot find any reference snippet

**Comment by owais** [comment]
Passing context as an function argument to the thread and then setting the received context on the other side. There is no automated solution.

**Comment by jsmolina** [comment]
I did it by passing context and then re-attaching it:
```
from opentelemetry import context

def execute_ec2_func(method, data, ctx):
    context.attach(ctx)
    return method(**data)
```

Then the boto3 methods are called passing current context:
```
loop.run_in_executor(
 self.executor,
 execute_ec2_func,
 self.ec2.start_instances,
 {"InstanceIds": instance_ids},
 context.get_current(),
)
```

**Comment by pridhi-arora** [comment]
Thanks, @srikanthccv. Looking forward to work on this.

**Comment by pridhi-arora** [comment]
What do we mean by `propagate tracing context across threads`? @srikanthccv Can you shed some light on this? Thanks in advance.

**Comment by ocelotl** [comment]
@bobthemighty

**Comment by bobthemighty** [comment]
@ocelotl  like this?

**Comment by changemyminds** [comment]
Any update news for this PR? or could I provide the PR about this threading feature?
