### ISSUE TITLE
Open Telemetry for GCP Traces / Stackdriver

### ISSUE THREAD

**Issue by Talador12** [open-telemetry/opentelemetry-python-contrib#769]
**Describe the solution you'd like**
A contributed example for exporting open telemetry results to GCP's trace service and/or Stackdriver
https://cloud.google.com/trace/docs
FastAPI and Flask examples could prove useful. Currently there are examples for Stackdriver on GCP's docs:
1) https://cloud.google.com/trace/docs/quickstart#instrumentation
2) https://cloud.google.com/trace/docs/setup/python-ot
3) https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi

Importantly, the first example is for OpenCensus and not OpenTelemetry. OpenTelemetry is possible on GCP so this would be a huge win to have examples of this for basic python API servers.

The second example is missing from this repo, and could be an easy win

The third link is for fast-api, which could be a good place for the second example

**Describe alternatives you've considered**
Using OpenCensus instead of OpenTelemetry because the docs already exist - but I would rather push forward with a new pattern for Open Telemetry.

**Comment by srikanthccv** [comment]
Please see https://github.com/GoogleCloudPlatform/opentelemetry-operations-python
