### ISSUE TITLE
Release opentelemetry-python-contrib

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-python-contrib#833]
Dear @open-telemetry/opentelemetry-python-contrib-maintainers could we get a new release of the package? 
There's been few changes since the last release (https://github.com/open-telemetry/opentelemetry-python-contrib/compare/v0.26b1...main) - I'm especially interested in AWS lambda flush timeout, so that it could be used in https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/src/otel/otel_sdk/requirements.txt

**Comment by codeboten** [comment]
@owais is this something you're planning on doing?
