### ISSUE TITLE
aiohttp instrumentation: Function create_trace_config has no span_name argument.

### ISSUE THREAD

**Issue by Olegt0rr** [open-telemetry/opentelemetry-python-contrib#848]
## Docs usage example
Ref: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/aiohttp_client/aiohttp_client.html#usage
```python
import aiohttp
from opentelemetry.instrumentation.aiohttp_client import (
    create_trace_config,
    url_path_span_name
)
import yarl

def strip_query_params(url: yarl.URL) -> str:
    return str(url.with_query(None))

async with aiohttp.ClientSession(trace_configs=[create_trace_config(
        # Remove all query params from the URL attribute on the span.
        url_filter=strip_query_params,
        # Use the URL's path as the span name.
        span_name=url_path_span_name
)]) as session:
    async with session.get(url) as response:
        await response.text()
```

## Bug
Function `create_trace_config` has no `span_name` argument.

```python
def create_trace_config(
    url_filter: _UrlFilterT = None,
    request_hook: _RequestHookT = None,
    response_hook: _ResponseHookT = None,
    tracer_provider: TracerProvider = None,
) -> aiohttp.TraceConfig:
    ...
```

**Comment by Olegt0rr** [comment]
Also looks weird that current solution starts span with name `f"HTTP {http_method}"` and then prompts to change it through `request_hook` callback

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d01efe5c5023110447de1741107e53b009b5886e/instrumentation/opentelemetry-instrumentation-aiohttp-client/src/opentelemetry/instrumentation/aiohttp_client/__init__.py#L200-L210

**Comment by owais** [comment]
Proposed patch looks good to me. Happy to merge a PR if one is sent :)

**Comment by lzchen** [comment]
@owais 
I thought we were trying to move away from using a span name callback and utilize the request/response hooks instead?

Like here: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/409

**Comment by owais** [comment]
@lzchen  This isn't a callback and since it is documented, it looked like a mistake but you're right, we already support request/response hooks which solve this problem. May be we should just update the docs instead.

**Comment by Olegt0rr** [comment]
Okay, I'll revert changes and update the docs.

Should we remove `url_path_span_name` since it's not usable anymore?

**Comment by lzchen** [comment]
@Olegt0rr 

Yes it doesn't seem like `url_path_span_name` is used so feel free to remove it. I think updating the docs to remove `span_name` is enough for this issue.

**Comment by Olegt0rr** [comment]
@lzchen, ready :)
