### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-python-contrib#861]
Dear @open-telemetry/opentelemetry-python-contrib-maintainers , any chances of getting a new release of the contrib? It's been 27 days since the last one and there are some particularly important features pending release.
Thanks in advance!

**Comment by lzchen** [comment]
@kubawach 
We are following our monthly release cadence. New release will most likely be out sometime next week.

**Comment by kubawach** [comment]
Thanks, will keep waiting then :)
