### ISSUE TITLE
DataDog trace exporter should support span events

### ISSUE THREAD

**Issue by Alan-R** [open-telemetry/opentelemetry-python-contrib#863]
**Is your feature request related to a problem?**
I create events using add_event() in OpenTelemetry, and they don't appear in DataDog.
exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py says:

> span events and span links are not supported except for extracting exception event context

**Describe the solution you'd like**
I'd like for it to support span events.
One possibility would be to translate them into dummy spans.

**Describe alternatives you've considered**
Manually creating dummy spans that effectively say:
 ```
 with create_new_span("event-text", attributes=event_attributes):
    pass
```

**Additional context**
Although making them into spans would make trace bigger and limit the maximum number of "real" spans in a single trace, it would preserve all the important things about the event: the timestamp, the name and the attributes.

**Comment by owais** [comment]
@majorgreys FYI ^

**Comment by Alan-R** [comment]
If a "suitable" PR would be considered which translated events into dummy spans, I would investigate creating and contributing one. Creating one looks pretty straightforward.

**Comment by owais** [comment]
@Alan-R I think we need to involve someone from Datadog here so they can weigh in what works for their product. I don't think the Python SIG can make this decision as this is a very vendor specific component. If you are a customer, might be worth it to let your support engineers know about this and request this as a feature.

**Comment by Alan-R** [comment]
I pointed them to this in a support email right after posting this. We'll see what they want to do. I gather that majorygrays is likely a maintainer for this code. From looking at the GUI, there doesn't seem to be any GUI element to display events, so they may not have something equivalent in native DataDog.

**Comment by srikanthccv** [comment]
Given that the exporter is [deprecated](https://github.com/open-telemetry/opentelemetry-python-contrib/commit/1bf9e0c51f800574acfff6e722dc586fe310bd01), I think we can close this issue. @Alan-R Feel free to re-open if you think otherwise.
