### ISSUE TITLE
Pyramid tween only handles HTTPException

### ISSUE THREAD

**Issue by gregbuehler** [open-telemetry/opentelemetry-python-contrib#888]
**Describe your environment** 
Seeing this exhibited in Pyramid 1.10 and as far back as Pyramid 1.7.

**Steps to reproduce**
Raise a non-HTTPException. 

**What is the expected behavior?**
Tweens should process normally.

**What is the actual behavior?**
An error for use of `response_or_exception` before assignment is raised.

**Additional context**
The problem exists here https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-pyramid/src/opentelemetry/instrumentation/pyramid/callbacks.py#L146-L157. It seems there should be an additional exception case for `BaseException` to initialize `response_or_exception`.

**Comment by owais** [comment]
Proposed fix makes sense. PRs welcome :)
