### ISSUE TITLE
Add missing license and manifests to the instrumentation packages.

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-python-contrib#893]
Continued from https://github.com/open-telemetry/opentelemetry-python-contrib/pull/616

**Comment by Sunilwali679** [comment]
@lzchen I am seeing the manifest file is missing in the below directory and it should be more . is this required to add the files in the below folder are not 

https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-confluent-kafka
https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette

can i work on this ??

**Comment by Sunilwali679** [comment]
@lzchen  License file is missing in https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis

**Comment by Sunilwali679** [comment]
can i work on this ??

**Comment by Sunilwali679** [comment]
can u please add as a contributor or co-author to this issue . We are from same community and working on this issue together .  

"login": "rahuldimri",
"id": 107100022,

"login": "rahulhacker",
"id": 20458598,

**Comment by lzchen** [comment]
@Sunilwali679 
I believe those users have to comment on this issue for me to assign them as well.

**Comment by rahuldimri** [comment]
As we are working with Sunil on this issue. Please assign this to me.

**Comment by rahulhacker** [comment]
@lzchen : I am working with @Sunilwali679  on this issue, please assign this to me also

**Comment by srikanthccv** [comment]
I think this is a trivial issue that doesn't require any actual code changes. I am not sure what three of you going to do here. Please just someone take this up and create one PR.
