### ISSUE TITLE
Capture HTTP request/response headers as span attributes

### ISSUE THREAD

**Issue by ashu658** [open-telemetry/opentelemetry-python-contrib#906]
**Is your feature request related to a problem?**
Python agent is not able to capture custom headers as of now. The specifications for capturing request/response headers is defined here [http-request-response-header](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-request-and-response-headers)

**Describe the solution you'd like**
This feature aims to capture custom request/response headers with the help of environment variables.I think these environment variables should be same for all the frameworks (something like OTEL_PYTHON_CAPTURE_REQUEST_HEADERS, OTEL_PYTHON_CAPTURE_RESPONSE_HEADERS) and the request/response headers will only be added in case of a server span.

Currently, some frameworks like falcon and django captures custom request headers with the help of environment variables (i.e. OTEL_PYTHON_FALCON_TRACED_REQUEST_ATTRS etc). I suggest we should change the environment variable from being framework specific to be general for all the frameworks.

We can open multiple sub-issues to add support and test cases for each framework.

**Additional context**
With conditional server span creation #445 added we can ensure single server span creation and no two frameworks capturing the same headers.

**Comment by owais** [comment]
> I think these environment variables should be same for all the frameworks (something like OTEL_PYTHON_CAPTURE_REQUEST_HEADERS, OTEL_PYTHON_CAPTURE_RESPONSE_HEADERS) and the request/response headers will only be added in case of a server span.

It would be ideal if we could have same env vars for all Otel SDKs. Does the spec recommend anything?

**Comment by ashu658** [comment]
Sure we can have the same env vars for all SDKs. We can only keep the prefix 'OTEL' to distinguish these env vars are used by otel sdks.
No, the spec doesn’t recommend anything. I see you have already asked for the specifications of env vars [here](https://github.com/open-telemetry/opentelemetry-specification/pull/1898#discussion_r700374972) but I don't think there has been further discussion around that.

**Comment by ashu658** [comment]
sure :)

**Comment by ashu658** [comment]
> I think we can go ahead with `OTEL_PYTHON_` env vars for now but you could also submit a PR in parallel the SDK spec proposing env vars for this functionality.

Raised a PR proposing env vars https://github.com/open-telemetry/opentelemetry-specification/pull/2461. Please have a look.

**Comment by ashu658** [comment]
> As part of this work, we should add an example of this usage for each instrumentation under `configuration` section of docstrings.

Created #1023 for adding docstrings for instrumentations where changes are already merged.

**Comment by srikanthccv** [comment]
@ashu658 Can be this be closed now?

**Comment by ashu658** [comment]
Yes @srikanthccv it can be closed.

**Comment by nabheet** [comment]
Does this capture functionality work for client libraries too, like `httpx`?
