### ISSUE TITLE
Restore prometheus remote write exporter

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#933]
This issue tracks the work to restore the prometheus remote write exporter. It is a follow up to issue https://github.com/open-telemetry/opentelemetry-python/issues/2291 which restores the prometheus exporter in the core repo.

**Comment by Doron-Bargo** [comment]
Hi @codeboten any update on restoring the Prometheus remote write exporter?
I notice it exists under metrics branch but never pushed to the main.

**Comment by vasireddy99** [comment]
Looks like we now have Prometheus remote write exporter in the `main` (branch)[https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-prometheus].

**Comment by lzchen** [comment]
@vasireddy99 

The current prometheus exporter that you are linking to is the pull-based prometheus exporter. We have yet to implement the remote-write exporter in the main branch using the updated metrics api/sdks.

**Comment by codeboten** [comment]
The current exporter that @vasireddy99 linked is the pull based exporter, @Doron-Bargo no one has taken on the work to bring back the remote write exporter. Would love help here if anyone has time for it

**Comment by haarakdy** [comment]
@codeboten   what is the difference between `prometheus remote write exporter` and the exporter I use currently 0.17b0 ?

**Comment by srikanthccv** [comment]
What you are using is based on the old API&SDK design which is no longer supported. There have been some significant changes since then and this issue is to restore the exporter to make it work with new API.
