### ISSUE TITLE
opentelemetry-instrumentation-httpx

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#946]

**Comment by nstawski** [comment]
I would like to take this issue.

**Comment by nstawski** [comment]
It looks like httpx also doesn’t need changes:

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a8edcf6a5234ce31be2b39d4adc7e7d0bb633239/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L319
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a8edcf6a5234ce31be2b39d4adc7e7d0bb633239/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L311

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a8edcf6a5234ce31be2b39d4adc7e7d0bb633239/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L396
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a8edcf6a5234ce31be2b39d4adc7e7d0bb633239/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L391
