### ISSUE TITLE
AttributeError: 'NonRecordingSpan' object has no attribute 'kind'

### ISSUE THREAD

**Issue by seanpile** [open-telemetry/opentelemetry-python-contrib#998]
Recent PR #952 seems to have introduced a regression in our code; when using a non-recording span, the flask instrumentation is breaking.  See the stacktrace below:

```
  File "lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 632, in __call__
    start_response(status, headers)
  File "lib/python3.9/site-packages/opentelemetry/instrumentation/flask/__init__.py", line 156, in _start_response
    if span.kind == trace.SpanKind.SERVER:
AttributeError: 'NonRecordingSpan' object has no attribute 'kind'
```

My expectation is that using a non-recording span should be fine to use safely, and not cause downstream errors.  I'm using the following libraries:

- opentelemetry-api==1.10.0                                                                                                                                                      
- opentelemetry-exporter-otlp-proto-grpc==1.10.0                                                                                                                                 
- opentelemetry-instrumentation-flask==0.29b0                                                                                                                                    
- opentelemetry-instrumentation-requests==0.29b0                                                                                                                                 
- opentelemetry-instrumentation-sqlalchemy==0.29b0                                                                                                                               
- opentelemetry-sdk==1.10.0                                                                                                                                                      
- opentelemetry-semantic-conventions==0.29b0

**Comment by srikanthccv** [comment]
Note to people who run into this issue: did a hot fix release for affected packages.
